### PR TITLE
Add admonition for Identity property

### PR DESCRIPTION
**Pull request by akeller**
## Description

Closes https://github.com/camunda/camunda-docs/issues/2309.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [x] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — DISMISSED** [review]

**Review by Ben-Sheppard — CHANGES_REQUESTED** [review]
This change is only applicable for version 8.2, from 8.3 onwards we have corrected the behaviour [here](https://github.com/camunda-cloud/identity/issues/1817)

**Review by christinaausley — APPROVED** [review]
@akeller I went ahead and removed this from `8.3` and `next` 👍

**Review by alexcorremans — DISMISSED** [review]

**Review by Ben-Sheppard — APPROVED** [review]
LGTM - just a thought, this is likely to be necessary in 8.1 (I think) but maybe 8.2 is enough for now

**Comment by christinaausley** [comment]
> LGTM - just a thought, this is likely to be necessary in 8.1 (I think) but maybe 8.2 is enough for now

Would it be worth creating an issue to revisit if this could change in the future? I lose track looking at so many PRs 😜

**Comment by Ben-Sheppard** [comment]
> > LGTM - just a thought, this is likely to be necessary in 8.1 (I think) but maybe 8.2 is enough for now
> 
> Would it be worth creating an issue to revisit if this could change in the future? I lose track looking at so many PRs 😜

It could be hah though the code in 8.1 will also be affected by the admonition (its only resolved in 8.3 +) so it would be good to have it there and then we can just merge IMO :D

**Comment by akeller** [comment]
I will add to 8.1 and we can get this merged.

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
