### PR TITLE
feat: Tasklist REST API Explorer

### LINKED ISSUE #3296: Implement API Explorer for Tasklist REST API
Following the success of https://github.com/camunda/camunda-docs/issues/3114, we should introduce an OpenAPI Explorer for the Tasklist REST API.

Docs on finding the OpenAPI spec are at https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/tasklist-api-rest-overview/.

## Implementation notes

See [this Slack conversation](https://camunda.slack.com/archives/C043W5V88M7/p1707491114379069) about working with the HTO team to improve the descriptions in the Tasklist OpenAPI spec. This is probably a thing we will want to do retroactively to the Operate API explorer, and other API explorers moving forward, because it adds so much valuable context to the explorer. 

This is what it looks like in the Tasklist explorer with descriptions filled in: 

image

### PR DESCRIPTION
**Pull request by pepopowitz**
## Description

Resolves #3296.

Adds an API Explorer for the Tasklist REST API.

## What it looks like

image

## Preview site

https://loquacious-pika-a05ac2.netlify.app/docs/apis-tools/tasklist-api-rest/tasklist-api-rest-overview/

Note that only the Tasklist REST docs for versions 8.4 * vNext have been updated to link to this new explorer.

## How does the user get to the Tasklist REST API Explorer?

Sidebar navigation options are added to the `next` and `8.4` versions, in the Tasklist REST API sections.

## Related: OpenAPI spec updates

As discussed [in Slack](https://camunda.slack.com/archives/C043W5V88M7/p1707491114379069), implementing this API Explorer includes migrating descriptions from [the current Tasklist REST API documentation](https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/controllers/tasklist-api-rest-task-controller/) to the OpenAPI spec for the Tasklist REST API. 

Without this work, we'd have lost a lot of good descriptive context for our Tasklist REST docs. 

Currently, the OpenAPI spec has only been updated on the version included in this docs repo. The HTO team will be migrating these changes into their source, so that future updates of this spec will include the descriptions.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
Me on a call not even 10 min ago "The Tasklist REST API Explorer isn't quite ready for showtime yet, so check with @pepopowitz on his progress there"

@pepopowitz: Literally pushed the PR an hour ago

**Comment by pepopowitz** [comment]
> 👋 🤖 🤔 Hello! Did you make your changes in all the right places?
> 
> These files were changed only in _docs/_. You might want to duplicate these changes in _versioned_docs/version-8.4/_.
> 
> * docs/apis-tools/tasklist-api-rest/sidebar-schema.js
> 
> You may have done this intentionally, but we wanted to point it out in case you didn't. You can read more about the versioning within our docs in our [documentation guidelines](https://github.com/camunda/camunda-docs/blob/c666b7e5e35bfe31468ce4ac679ea7b62ab86d73/howtos/documentation-guidelines.md#versions).

This is kind of a funny thing. This _is_ an intentional difference between vNext and v8.4. Standalone sidebar schemas work in vNext, because we can import them, because the root sidebar schema is a JavaScript file. Standalone sidebar schemas, and JavaScript-based schemas, do not work in numbered versions, and the root schema is a JSON file so we can't import them anyway.

**Review by akeller — COMMENTED** [review]
I'm not sure if this is feedback for the PR or the schema, but the names seem quite verbose.

image

I would expect something more in line with the action performed rather than the result - get a task, search tasks, etc. in the sidebar. A great example is the [Stripe API](https://docs.stripe.com/api/charges).

Similar to my question on [another PR](https://github.com/camunda/camunda-docs/pull/3332#pullrequestreview-1883025987), can we make it clearer what auth is possible for SaaS vs. SM? Or would that be something we need to document outside of the explorer experience?

Overall I love the amount of detail that I can see here. Lots of good adds!

**Comment by pepopowitz** [comment]
> Similar to my question on https://github.com/camunda/camunda-docs/pull/3332#pullrequestreview-1883025987, can we make it clearer what auth is possible for SaaS vs. SM? Or would that be something we need to document outside of the explorer experience?

There might be something we can do in the spec itself to add more details to the auth options! I'll look into this.

**Comment by pepopowitz** [comment]
@akeller With my latest commits, the action names now look like this: 

image

Any context that was previously in the action names that I removed, example "Returns the task," I have moved into the description field of the endpoint. That context is preserved, just in a different location, like this: 

image

I haven't pushed these changes to the preview site, I wanted to get your opinion first.

**Comment by pepopowitz** [comment]
@akeller also in a recent commit, and also not yet pushed to the preview site: 

I've added a description to the cookie-based authentication option, to clarify that it is only available for Self-Managed clusters: 

image


What do you think?

**Comment by akeller** [comment]
@pepopowitz I like both of these changes. Thank you for preserving the info as a description. That's much more in line with what I would expect.

**Comment by christian-konrad** [comment]
@pepopowitz these are fantastic changes! Thanks a lot!

So clean.
We can even make it cleaner:
 
image

"Get form" and "Get variables" are sufficient I believe!

**Comment by pepopowitz** [comment]
> @pepopowitz these are fantastic changes! Thanks a lot!
> 
> So clean. We can even make it cleaner:
> 
> "Get form" and "Get variables" are sufficient I believe!

1. To align with the remaining actions, which include the `a` article when dealing with one item, I'll make those "Get a form" and "Get a variable". 
2. There is also "Get task details," and I'll change that to "Get a task."
3. Once those changes are pushed up, I'll also pass along a diff including all changes that I've made to the spec for this PR, so the HTO team can see them all in one place for making the changes at the actual source.

**Comment by pepopowitz** [comment]
@christian-konrad and @houssain-barouni, [here is a diff](https://github.com/camunda/camunda-docs/compare/14c601dce73b7a7961f28b2e107daacbb197bae4..6dbd309#diff-3e86737f3349c1d2d9f495ab59d3991780f9c0294367774c2140b7aca26ddf9c) showing all of the changes I've now made to the Tasklist REST API OpenAPI spec for this PR. 

(If it doesn't take you directly to it, the file containing the spec is `api/tasklist/tasklist-openapi.yaml`.)

**Review by akeller — APPROVED** [review]
I ran this locally since I saw the preview site wasn't updated. This looks really great! Love the amount of detail that's presented to users. Great work here @pepopowitz!

**Pull request merged**
