### PR TITLE
fix: url to token issuer

### PR DESCRIPTION
**Pull request by Zelldon**
## Description

Run into this issue with @ce-dmelnych we had to fix the path before connecting.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by ce-dmelnych — DISMISSED** [review]

**Comment by christinaausley** [comment]
Hi @Zelldon  -- are you planning to have this for merge next week upon release?

**Comment by Zelldon** [comment]
@christinaausley, tbh it was just a drive-by fix, and I had not much time to look into it more. I think it can also be merged later. I'm off tomorrow.

**Comment by christinaausley** [comment]
@Zelldon Also happy to backport for you and get this merged 👍

**Comment by Zelldon** [comment]
Sorry @christinaausley I didn't came to it yet. What would backporting mean here? Do we have separate stable branches or is it on different folders (like we had in the past). Sorry I'm not that familiar anymore with the process here.

**Comment by Zelldon** [comment]
Nevermind I guess it would be this https://github.com/camunda/camunda-docs/blob/main/howtos/versioning.md

**Comment by Zelldon** [comment]
@christinaausley I did it on 8.3 and 8.2, for 8.1 I didn't found the file. Let me know when I did something wrong.

**Review by christinaausley — APPROVED** [review]
Stellar! Thank you @Zelldon! 🌟

**Pull request merged**
