### PR TITLE
add new web modeler deploy config

### PR DESCRIPTION
**Pull request by conceptualshark**
## Description

Relates to https://github.com/camunda/web-modeler/issues/10571 - no changes needed; the documents on deployment pipelines/stages look compatible with the expected self managed behavior, and may only need screenshot updates when the SaaS and SM visuals are aligned

Implements to https://github.com/camunda/web-modeler/issues/10570 - added the ID field to the SM web modeler config table, and updated references to the Docker distro to include the option in Helm as well.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by conceptualshark** [comment]
@nithinssabu My instinct here was to mark the new ID field as Required in some way, as it sounds like you will be unable to deploy without it? If this is the case, it would be handy to list which other config options are required vs not, and I could add those in as well, or follow up.

**Review by mesellings — APPROVED** [review]
Lgtm, nothing useful to add - great work! 👍 🚀 🥇

**Comment by nithinssabu** [comment]
> @nithinssabu My instinct here was to mark the new ID field as Required in some way, as it sounds like you will be unable to deploy without it? If this is the case, it would be handy to list which other config options are required vs not, and I could add those in as well, or follow up.

@conceptualshark If the ID field is not present or unique, then the application won't start up and the reason will be clear from the error message. In my opinion, it's fine to not have this in the documentation.

**Review by nithinssabu — APPROVED** [review]
Thank you 🙂

**Pull request merged**
