### PR TITLE
version the link to the grafana dashboard config

### LINKED ISSUE #3796: Link to Grafana Dashboard configuration should be versioned
The docs provide a link to an extremely valuable Grafana dashboard configuration:

https://github.com/camunda/camunda-docs/blob/f582f712930036c2e885fac5566b25da869a243c/docs/self-managed/zeebe-deployment/operations/metrics.md?plain=1#L96-L99

However, since new Zeebe releases may introduce new metrics and sometimes rename existing ones, we should point customers to a dashboard configuration that fits to their Zeebe version, e.g. https://github.com/camunda/zeebe/blob/stable/8.5/monitor/grafana/zeebe.json

Similar versioned link issues: #3795 #3743

### PR DESCRIPTION
**Pull request by conceptualshark**
## Description

Resolves #3796 

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by akeller** [comment]
Do you have a docs backlog item or reminder set to revisit this when 8.6 goes live?

**Comment by christinaausley** [comment]
> Do you have a docs backlog item or reminder set to revisit this when 8.6 goes live?

@conceptualshark I have a few of these links I check upon release, too. How would you feel about a shared Google Sheet to track these in one place? If you have a better idea for tracking, I'm all ears!

**Comment by conceptualshark** [comment]
> > Do you have a docs backlog item or reminder set to revisit this when 8.6 goes live?
> 
> @conceptualshark I have a few of these links I check upon release, too. How would you feel about a shared Google Sheet to track these in one place? If you have a better idea for tracking, I'm all ears!

@christinaausley I think this is the simplest solution for now - it works for me!

**Comment by christinaausley** [comment]
@conceptualshark Shared [the file](https://docs.google.com/spreadsheets/d/1q2F308phdRotistKaCW1qa1NmL96BRLn9ttarWDfOto/edit?usp=sharing) with you 👍

**Review by christinaausley — APPROVED** [review]

**Comment by akeller** [comment]
@conceptualshark, once reviewed, you can hit the "squash and merge" button, or I can periodically come through and do it. Doesn't matter to me!

**Pull request merged**
