### PR TITLE
chore(context-pad): document as non-alpha feature

### PR DESCRIPTION
**Pull request by philippfromme**
## Description

Changes the context pad documentation from alpha to non-alpha since it's now enabled by default and not considered an alpha feature anymore.

Closes https://github.com/camunda/camunda-docs/issues/3992

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [x] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by akeller** [comment]
@philippfromme, you'll need a redirect here to get the build ✅. Is this ready for a review (or assistance)?

**Comment by philippfromme** [comment]
> @philippfromme, you'll need a redirect here to get the build ✅. Is this ready for a review (or assistance)?

Thanks for the hint. I'll try to fix it.

**Comment by christinaausley** [comment]
@philippfromme Just let me know if I can help 😄

**Comment by philippfromme** [comment]
> @philippfromme Just let me know if I can help 😄

I added a redirect but unfortunately it's still failing. 😢

**Comment by christinaausley** [comment]
@philippfromme You were close -- just made a minor tweak.

**Comment by christinaausley** [comment]
@philippfromme Is this also ready for review?

**Comment by philippfromme** [comment]
This is ready for review.

**Review by christinaausley — DISMISSED** [review]
Nice work on this!

**Review by christinaausley — APPROVED** [review]

**Comment by philippfromme** [comment]
@christinaausley Can we go ahead and merge this?

**Pull request merged**
