### PR TITLE
feat: document changes to exported records

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

With the introduction of generalized command distribution we've had some breaking changes for custom exporterd that consume distribution records. This section explains what it's been replaced by.

## When should this change go live?

with the 8.3 release

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — APPROVED** [review]
As this is a breaking change, do we need to note elsewhere in relevant documentation as an admonition? If not, you can disregard and merge when ready, but wanted to double check.

**Comment by christinaausley** [comment]
Also @remcowesterhoud, please sign the CLA -- you should only have to do this once 👍

**Comment by remcowesterhoud** [comment]
> Also @remcowesterhoud, please sign the CLA -- you should only have to do this once 👍 

I did. It's complaining about you 😄

**Comment by christinaausley** [comment]
> > Also @remcowesterhoud, please sign the CLA -- you should only have to do this once 👍
> 
> I did. It's complaining about you 😄

This is what I get for going through open PRs at 6 a.m. 😄

**Review by koevskinikola — APPROVED** [review]
LGTM :100:

**Pull request merged**
