### PR TITLE
Docs landing page card hyperlinks

### PR DESCRIPTION
**Pull request by mesellings**
## Description

CSS fix to remove hyperlink padding on docs landing page card components.

Previously, there was padding around card hyperlinks when hovering:

image

- This is now fixed so the entire card area is hyperlinked.
- Tested in Google Chrome and Firefox

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [X] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by mesellings** [comment]
@pepopowitz I've tagged you as the reviewer, just to check you are happy with the fix - this can go out whenever you have a chance to review it, it is non-critical but be good to release this week hopefully?

**Review by pepopowitz — APPROVED** [review]
💪  Looks great!

**Comment by akeller** [comment]
@MaxTru this will be fixed with our next docs release. Thanks @mesellings for jumping on this!

**Comment by mesellings** [comment]
@MaxTru This is now live in the latest docs release this morning - thanks for spotting this initially 👍

**Pull request merged**
