### PR TITLE
Added support for PKCS12 password protected TLS config

### PR DESCRIPTION
**Pull request by EuroLew**
## Description

Add documentation about how to use the new TLS configuration with a PKCS12 file. This adds details about the configuration file fields and the expected contents of the PKCS12 file.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Review by christinaausley — COMMENTED** [review]
@EuroLew Is this only applicable to the `next` version of docs, or also the previous versions and current version of docs?

**Comment by EuroLew** [comment]
> @EuroLew Is this only applicable to the `next` version of docs, or also the previous versions and current version of docs?

This should apply only to the `next` version of docs. These changes will not apply currently and are not back ported.

**Comment by christinaausley** [comment]
CC @npepinpe for review 👍

**Review by npepinpe — APPROVED** [review]
:+1:

**Comment by christinaausley** [comment]
@EuroLew Can I go ahead and merge this, or does it need to wait until release next month?

**Comment by npepinpe** [comment]
It can be merged now :+1:

**Pull request merged**
