### PR TITLE
Improve docs for unsupported multi-tenancy features in 8.3

### LINKED ISSUE #2781: Make unsupported multi-tenancy features more visible
### Description

Add unsupported functionality in the scope of multi-tenancy in the dedicated conceptual page for multi-tenancy.

```[tasklist]
### AC
- [x] Document unsupported (custom tenant) signal broadcasting for `8.3`
- [x] Document unsupported (custom tenant) resource deletion for `8.3`
- [x] Note that the above features are supported for the `<default>` tenant.
- [x] Document that Go client doesn't support multi-tenancy for `8.3`
- [x] Document that CLI client doesn't support multi-tenancy for `8.3`
```

### PR DESCRIPTION
**Pull request by koevskinikola**
## Description

Increase the visibility of unsupported multi-tenancy features and clients in Camunda 8.3.

This includes signal broadcasting and resource deletion, as well as the GO and CLI clients.

closes #2781 

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by koevskinikola** [comment]
@felix-mueller I've assigned you as a reviewer as an FYI.

**Review by felix-mueller — DISMISSED** [review]
Lgtm

**Review by christinaausley — APPROVED** [review]

**Comment by akeller** [comment]
Will this functionality be available in 8.4? Or unsure? 

I'm unsure if we need to add to the `/next/` docs via `/docs`.

**Comment by koevskinikola** [comment]
Hey @akeller yes, Signal Broadcasting and Resource Deletion will be available with `8.4`, both topics (https://github.com/camunda/zeebe/issues/12653 and https://github.com/camunda/zeebe/issues/14279) are already in progress.

**Comment by koevskinikola** [comment]
@akeller I'm merging this PR. There are already PRs for `8.4` /  `/next` that document support for [Signal broadcast](https://github.com/camunda/camunda-docs/pull/2822) and [Resource Deletion](https://github.com/camunda/camunda-docs/pull/2850). They're just on hold until the code is merged.

Support for the Go and CLI clients is up next.

**Pull request merged**
