### PR TITLE
docs(concepts): Improve Execution Listener documentation

### PR DESCRIPTION
**Pull request by ce-dmelnych**
## Description

Relates to: https://github.com/camunda/camunda/issues/16217

This PR improves the documentation for Execution Listeners. It builds on the initial documentation and received feedback to improve clarity and provide more comprehensive guidance for developers.

Scope:
- Added details about the blocking behavior of ELs
- Described how the system handles incidents raised during EL job or expression failures.
- Updated limitations section.
- Enhanced documentation structure and added references to relevant resources & code example.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by ce-dmelnych** [comment]
Preview environment with update [Execution Listeners page](https://preview.docs.camunda.cloud/pr-4233/docs/next/components/concepts/execution-listeners/).

**Review by tmetzke — APPROVED** [review]
🚀 Thanks, @ce-dmelnych, that will help users understand listeners a lot better 👍

**Comment by mesellings** [comment]
@tmetzke I will do a review for you now 👍

**Review by mesellings — APPROVED** [review]
@ce-dmelnych I have completed the review and made commits directly into the branch:
* Edits for structure (headings, tables)
* Readability, active voice edits
* Style guide edits (for example, we do not use "e.g.", but rather "for example," or "such as")

Happy to approve, nice work! 👍

**Comment by mesellings** [comment]
@ce-dmelnych Would you like me to merge this?

**Comment by ce-dmelnych** [comment]
@mesellings Thank you for your efforts! The documentation looks great with your improvements 🎉 

One small note: it might be better to present the text under `Job execution failure` and `Expression evaluation failure` headings as paragraphs instead of list items. Using items could potentially confuse users by making the explanations appear fragmented.

What do you think?

**Comment by mesellings** [comment]
> https://preview.docs.camunda.cloud/pr-4233/index.html

I would normally try and avoid very verbose paragraphs like this if I can (hence splitting the sentences into bullets) to avoid cognitive overload when reading, but as you know the subject matter better than I do, happy if you want to have these as paragraphs, but perhaps split the sentences on new lines?

**Comment by mesellings** [comment]
@ce-dmelnych Sounds good! 👍

**Comment by mesellings** [comment]
@ce-dmelnych I still have the branch open, want me to make the changes quickly?

**Comment by ce-dmelnych** [comment]
> @ce-dmelnych I still have the branch open, want me to make the changes quickly?

@mesellings
That would be great, thank you!

**Comment by mesellings** [comment]
@ce-dmelnych changes made, all good to go:
* Changed bullets to paras
* Removed superfluous line as now not needed

image

**Review by mesellings — APPROVED** [review]
Approved 👍

**Comment by ce-dmelnych** [comment]
@mesellings
I'm happy for it to be merged now, no need to wait. Thanks for checking!

**Pull request merged**
