### PR TITLE
feat(guides): add experimentation disclaimer

### PR DESCRIPTION
**Pull request by HanselIdes**
## Description

Resolves https://github.com/camunda/camunda-docs/issues/2889
Related to https://github.com/camunda/product-hub/issues/890

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [x] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by christinaausley** [comment]
Did you only want this in the next version of docs, or the existing `8.3`?

**Comment by HanselIdes** [comment]
@christinaausley this should be backdated, as it affect all users regardless of version

**Review by christinaausley — APPROVED** [review]
Backported here, but any **big** changes should likely be adjusted along the way regardless, just keep me updated.

Additionally, need a note to remove this note when we are done with experiments 👍

**Comment by HanselIdes** [comment]
@christinaausley I added a note that it should be removed after https://github.com/camunda/product-hub/issues/890 is closed

**Comment by christinaausley** [comment]
Oh, I just meant make a note in https://github.com/camunda/product-hub/issues/890 🤣 I'll remove this from the docs, and get this merged for you.

**Review by christinaausley — APPROVED** [review]

**Review by akeller — APPROVED** [review]
I like that you kept it quite generic here. It's unclear if we are testing the page or the product, which in this case is nice ambiguity.

**Pull request merged**
