### PR TITLE
Add design, automate, improve to group guides

### LINKED ISSUE #2614: Introduce groupings for Guides
Our Guides section has grown! Let's introduce some groups or sections to organize this content better. Currently, these docs live under "Next steps".

* **Design**
  * Any content re: modeling BPMN & DMN
  * Forms
* **Automate**
  * Any Connectors guides
  * Cluster creation
  * Client credentials
* **Improve**
 * Any Optimize guides
 * SDLC & CI/CD (DevOps lifecycle)

Content that doesn't fit into these groups should be identified & removed or repurposed. Content that doesn't fit into these groups should remain in **Next steps** to keep this from blocking progress or iterations.

In addition to existing content, we should review the docs backlog for upcoming Guides (issues in this repo).

This is related to feedback and collaboration with https://github.com/camunda/developer-experience/issues/96.

### PR DESCRIPTION
**Pull request by akeller**
## Description

Based on feedback collected internally - https://miro.com/app/board/uXjVMq9qN3E=/

@christinaausley there is some awkwardness introduced here with the naming of guides, including "Automate a process using BPMN" now sitting in the **Design** section. Can you look at the names of these guides and propose changes? Remember that we can change the page title or sidebar title in the metadata. We don't necessarily need to change the URL. 

We should also evaluate what's in the docs issues as known changes to SaaS guides to see if we can properly sort future content into these buckets. Speaking of, I will add @christian-konrad as a reviewer since he's writing a lot of content and may want to float the SDLC/DevOps lifecycle group up one level. 

Closes #2614.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by christinaausley** [comment]
Planning to have a look at this this week, though I'm off Friday. I'll prioritize a handful of naming feedback next week if I'm unable to get to it over the next 2-3 days.

**Comment by christinaausley** [comment]
I would propose the following:

- Design (or create, craft) a process using BPMN
- Design decision tables using DMN
- Create forms with Modeler

- Create a cluster
- Set up your development project
- Set up client connection credentials
- Configure out-of-the-box Connectors
- Target a running workflow (with a state update?)
- Use Connectors in hybrid mode
- Host custom Connectors

- Improve processes with Optimize

I could get crazy creative with the titles, but I'd like users to get used to the new layout before I do that.

**Comment by akeller** [comment]
Great perspective here @christinaausley, keeping the users in mind with too many abrupt changes.

Specifically, I want to change the BPMN guide because the current title is the title of another grouping... which seems super awkward. I like your proposal -> Design a process using BPMN

Let's think of an engaging way to get more feedback internally on the other ideas for the guide names! (That can be another issue scope and not in this PR.)

**Comment by akeller** [comment]
@christinaausley let's get this merged into `/next/` and see if we can get more feedback on it before backporting. Sound good?

**Comment by christinaausley** [comment]
> @christinaausley let's get this merged into `/next/` and see if we can get more feedback on it before backporting. Sound good?

Works for me @akeller 👍

**Pull request merged**
