### PR TITLE
true/false in config docs

### PR DESCRIPTION
**Pull request by akeller**
## Description

Closes https://github.com/camunda/camunda-docs/issues/3047

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Review by mesellings — APPROVED** [review]
I've reviewed the changes, and all the default value changes to lower case look good to me.

Non-blocking: I know it's not part of this PR scope, but I did notice the following:

* For the descriptions, we could standardise and make them less passive. For example, 'When true, Importer module is enabled" > "Enable the Importer module".
* The use of "whether" could be changed to use "if" as per the Camunda writing style guide: https://camunda.com/brand/writing-style-guide/

**Comment by akeller** [comment]
@mesellings, thanks for the review! Can you add an issue to the backlog for this? To be complete, we'll also need to change the config "docs" in the codebase.

**Comment by mesellings** [comment]
> @mesellings, thanks for the review! Can you add an issue to the backlog for this? To be complete, we'll also need to change the config "docs" in the codebase.

Will do - forgive my ignorance, what do you mean by "config docs in the codebase"? Where would this be?

**Comment by conceptualshark** [comment]
If we're going through the trouble of updating these, my preference is to use `inline code` when referring to specific boolean values (or any value), but I don't think we have a company style for this use.

**Comment by akeller** [comment]
> > @mesellings, thanks for the review! Can you add an issue to the backlog for this? To be complete, we'll also need to change the config "docs" in the codebase.
> 
> Will do - forgive my ignorance, what do you mean by "config docs in the codebase"? Where would this be?

On a quick review of the templates, we may not need to change this at all! 

The templates for broker config really drive this documentation. We moved it into the docs to make it easier to discover. At the top of the [page](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/configuration/broker-config/) we link to the [template](https://github.com/camunda/camunda/blob/main/dist/src/main/config/broker.yaml.template).

> A complete broker configuration template is available in the [Zeebe repo](https://github.com/camunda/camunda/blob/main/dist/src/main/config/broker.yaml.template).

We do something similar for gateway config.

**Comment by mesellings** [comment]
Issue created: https://github.com/camunda/camunda-docs/issues/4123

**Pull request merged**
