### PR TITLE
connector task react component

### PR DESCRIPTION
**Pull request by christinaausley**
## Description

Related to https://github.com/camunda/team-connectors/issues/805.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by christinaausley** [comment]
@YanaSegal Upon approval, I'll add this to all references across the docs. I assume this should be backported all the way through?

**Comment by johnBgood** [comment]
@YanaSegal it looks great! :)

**Review by YanaSegal — COMMENTED** [review]
It looks good, i provided a better image for use in this section:
https://github.com/camunda/camunda-docs/pull/3980#issuecomment-2191428022

thanks!

**Comment by christinaausley** [comment]
@YanaSegal Awesome! I'll add this, and adjust all of the references across the docs. Should this be backported all the way through? If I can't get to this today, I'll have it done next week 👍

**Comment by YanaSegal** [comment]
@christinaausley, since the new context pad went out for most in 8.5, we can update the docs from this version. Otherwise, they still need to use the old "wrench" icon.

**Comment by christinaausley** [comment]
@YanaSegal @johnBgood this is ready for final review 👍

**Comment by johnBgood** [comment]
@christinaausley I checked http://localhost:3000/docs/components/connectors/out-of-the-box-connectors/slack/ locally but I think the paths are broken, or did I miss something?
The section is empty:

Screenshot 2024-07-01 at 09 26 48

**Pull request merged**
