### PR TITLE
feat: move GraphQL docs to deprecated folder

### LINKED ISSUE #3427: Move GraphQL docs in “deprecated” folder
With the introduction of the Zeebe REST API for user tasks, there would be 3 APIs to chose from for task management. It's clear that new users will be confused and overloaded. We want to support a kick-a** dev experience, and should keep the API docs entry pages clean.

Hence, let's move the GraphQL API docs into a "deprecated" folder. 

Ensure that references to the pages will not break by doing so.

Bildschirmfoto 2024-03-07 um 15 13 17

### PR DESCRIPTION
**Pull request by christian-konrad**
## Description

Closes #3427

This PR simply introduces a sidebar folder, but does not change the paths of the existing pages.

## When should this change go live?

- [x] This change is not yet live and should not be merged until 8.5 release date (April 9)

## PR Checklist

- [x] Changes are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`).
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by houssain-barouni — APPROVED** [review]

**Comment by christinaausley** [comment]
@christian-konrad Let me know when you would like this removed from Postman, but I'll add a similar note there.

CC @pepopowitz for sidebar syncing.

**Comment by christian-konrad** [comment]
@christinaausley good idea to remove it from Postman! Let's keep it simple for users

**Comment by christinaausley** [comment]
@christian-konrad Sounds good. I'll do that closer to release 👍

**Comment by christinaausley** [comment]
@christian-konrad Is this ready to merge?

**Comment by christian-konrad** [comment]
@christinaausley yes it is, just requires your approval :)

**Pull request merged**
