### PR TITLE
Connector template generator

### PR DESCRIPTION
**Pull request by YanaSegal**
## Description

This feature has been release to prod for SaaS users, and will be release with next alpha for SM users.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by markfarkas-camunda** [comment]
@mesellings could you please review this PR? The feature is already in PROD since the 15th of October, and I have to provide penetration test scenarios where I need to refer to the doc as well

**Comment by mesellings** [comment]
Hi @markfarkas-camunda we're currently away in the US for our team meeting this week, but I will try and take a look this morning before and after the meeting today, otherwise it will be on Monday 👍

**Comment by akeller** [comment]
@markfarkas-camunda I'm confused when you say this has been in PROD since October 15th, but the PR description says it's part of an alpha or minor, and labeled for 8.7. Could you or @mesellings update the description (and possibly the label) to indicate this should be reviewed and released ASAP.

**Review by mesellings — DISMISSED** [review]
@YanaSegal I have reviewed and made comprehensive changes to the doc, but happy with it - great initial work 👍  There is probably some follow-up work to add some more inter-linking to this across the docs (possibly) but I will look at this with the new Connectors work 👍

**Comment by mesellings** [comment]
@markfarkas-camunda @YanaSegal Can I just clarify:
- This is not in prod for 8.6, so will need this doc added to the 8.6 docs (rather than just Next and 8.7)
- Can you adjust the labels from 8.7 to the relevant version if this is the case please?

**Comment by markfarkas-camunda** [comment]
@mesellings this feature is in prod for SaaS, but not yet for self-managed. In this case shall we add the doc also to 8.6 docs?

**Comment by mesellings** [comment]
> https://preview.docs.camunda.cloud/pr-4382/index.html

We can add a 'SaaS only' badge to the page until it is available for SM - if it's available in 8.6 for SaaS then we can/should add it there?

**Comment by mesellings** [comment]
@markfarkas-camunda I have added a "SaaS only" badge to the top of the page, and backported for the 8.6 docs. 
Please re-review and approve if you're happy for the docs to go live 👍  (@YanaSegal only review if you need to).

**Pull request merged**
