### PR TITLE
chore: Tutorial to use Tasklist REST API

### LINKED ISSUE #3247: Create Tutorial to use Tasklist REST API
Today we have this [Tutorial](https://docs.camunda.io/docs/apis-tools/tasklist-api/tasklist-api-tutorial/) explaining how to build a BFF on top of Tasklist GraphQL API.
We also have a [GraphQL to REST API migration guide](https://docs.camunda.io/docs/apis-tools/tasklist-api/tasklist-api-graphql-to-rest-migration/).

We need a new tutorial explaining how to build a BFF on top of Tasklist REST API, for clients starting from scratch.

**Notes**: 
- for 8.5 we will start building Tasklist REST API V2, that needs to be used along with Zeebe user tasks REST API. This may need to be tackled in a new ticket.
-  let's also document how to do an eligibility check for "complete" - i.e. compare user with task assignee before granting access to complete, since the API does not check this

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Description

closes #3247 

This tutorial has a dependency with this [spring-zeebe pull request](https://github.com/camunda-community-hub/spring-zeebe/pull/741) to be merged and new version 8.5.0 of [spring-zeebe](https://github.com/camunda-community-hub/spring-zeebe) to be released

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by christinaausley** [comment]
This is meant to go out with `8.5`, yes?

**Comment by houssain-barouni** [comment]
> This is meant to go out with `8.5`, yes?

Hi @christinaausley , 
yes. If it is too late, we can incorporate it later after the branch-cut. I can backport it to `versioned_docs` of needed.

**Comment by christinaausley** [comment]
No problem @houssain-barouni! I'll get this reviewed today, so should be fine for release.

**Review by christian-konrad — APPROVED** [review]
I made some fixes, language simplifications, self-managed details, and next steps.

The tutorial is great! @houssain-barouni I changed my mind and think we can merge it now, assuming the tutorial will work smooth once 8.5 is released and can be used.

I will still test it next week after the release and open a follow-up issue/PR if it doesn't work, wdyt?

**Comment by christinaausley** [comment]
@houssain-barouni The build issue is that the reference to `/bpmn/apis-tools/api-test-process.bpmn/` does not exist -- has this already been added, or was it removed?

**Comment by houssain-barouni** [comment]
> @houssain-barouni The build issue is that the reference to `/bpmn/apis-tools/api-test-process.bpmn/` does not exist -- has this already been added, or was it removed?

@christian-konrad can you please add the missing file ?

**Comment by christian-konrad** [comment]
@houssain-barouni @christinaausley sorry, done :)

**Review by christian-konrad — APPROVED** [review]

**Pull request merged**
