### PR TITLE
clarify connecting to oidc provider

### PR DESCRIPTION
**Pull request by christinaausley**
## Description

Closes https://github.com/camunda/developer-experience/issues/289.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
**Will add to versioned docs upon approval.**
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineerring DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer.

### CODE REVIEW

**Comment by christinaausley** [comment]
@McAlm You mentioned adding this directly to the helm chart snippet -- can you direct me to where you are referring to?

@McAlm @jonathanlukas Does this small change close out the confusion you've seen among users, or are there additional details I can add?

**Review by jonathanlukas — APPROVED** [review]
lgtm

**Review by akeller — APPROVED** [review]
I'm good with these changes if you are looking to merge.

**Comment by christinaausley** [comment]
@McAlm Merging this in, but let me know if you have specifications for linking to a Helm chart snippet, and I'll adjust in a subsequent PR.

**Pull request merged**
