### PR TITLE
docs(slack-documentation): update the documentation for slack connector

### PR DESCRIPTION
**Pull request by mathias-vandaele**
update the documentation for slack connector, we can now use channel ID to invite users into channel

## Description

https://github.com/camunda/connectors/issues/2695

We can now invite new users into a channel using the `Channel ID` 

It will be available in `8.6.0-alpha4-rc2` of `connectors`
 
## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label) 
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by christinaausley** [comment]
@mathias-vandaele Just let @camunda/tech-writers know when you're ready for review 👍

**Comment by christinaausley** [comment]
@mathias-vandaele Do you want this to go out with the alpha tomorrow? If so, we'll likely need an engineering and technical writer review on this ASAP.

**Comment by akeller** [comment]
Hello @mathias-vandaele - it's the end of my day here in the US, but it's not clear to me if this PR is ready to merge for the alpha release tomorrow. Please remove the `hold` label and ping us on ask-c8-documentation for a review, merge, and release. I've added @sbuettner as a reviewer as well, but feel free to add a different engineering reviewer.

**Comment by mesellings** [comment]
Hi @mathias-vandaele - is this PR ready to merge for the alpha release today please?

If so, please remove the hold label and ping us on ask-c8-documentation for a review, merge, and release, or Slack me directly. We've added @sbuettner as a reviewer as well, but feel free to add a different engineering reviewer.

**Comment by mathias-vandaele** [comment]
> Hi @mathias-vandaele - is this PR ready to merge for the alpha release today please?
> 
> If so, please remove the hold label and ping us on ask-c8-documentation for a review, merge, and release, or Slack me directly. We've added @sbuettner as a reviewer as well, but feel free to add a different engineering reviewer.

Hi @mesellings
It is ready to merge for the alpha released.
The `hold` label has been removed, I also sent a message in the `ask-c8-documentation` channel

**Comment by mesellings** [comment]
Hi @mathias-vandaele thank you - I will perform a review for you and we can get it merged today 👍

**Review by mesellings — APPROVED** [review]
@mathias-vandaele LGTM, I made a few edits as some ordered lists should be bullet lists, and tidied up a few sentence fragments. Approved 👍

**Pull request merged**
