### PR TITLE
feat(saas): document the upcoming Singapore region

### PR DESCRIPTION
**Pull request by multani**
See: https://github.com/camunda/product-hub/issues/2556

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [x] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Review by christinaausley — APPROVED** [review]

**Comment by christinaausley** [comment]
Will this go out with the `8.7` release?

**Comment by multani** [comment]
@christinaausley I will check with product management, but it will go out before that (possibly, end of November/beginning of December)

**Comment by multani** [comment]
@felix-mueller and @jakobfreund can you double check and check @christinaausley's question?

**Comment by felix-mueller** [comment]
@boooczek can you take this one?

**Comment by boooczek** [comment]
Of course. Will do!

W dniu śr., 13.11.2024 o 13:45 Felix Müller ***@***.***>
napisał(a):

**Comment by boooczek** [comment]
@christinaausley @multani, we should release it as soon as we're ready. We don't need to wait for any particular date.

**Review by boooczek — DISMISSED** [review]
lgtm

**Comment by akeller** [comment]
👋 Hi, everyone! I think we should get in the habit of announcing new regions via our [Announcements page](https://docs.camunda.io/docs/reference/announcements/). WDYT?

**Comment by multani** [comment]
@akeller I agree about the announcement! This should definitely be announced somewhere :)
Would that Announcement page be also fit outside of the regular release cycle? (it seems that page is mostly for releases, not for out-of-bound changes)

**Comment by akeller** [comment]
> @akeller I agree about the announcement! This should definitely be announced somewhere :) Would that Announcement page be also fit outside of the regular release cycle? (it seems that page is mostly for releases, not for out-of-bound changes)

Since we are in the 8.7 release cycle, let's announce it there. (FYI, @mesellings, a use case to consider for https://github.com/camunda/developer-experience/issues/326)

BTW, 8.2 is technically unsupported since October, so we shouldn't add this to it.

**Comment by boooczek** [comment]
I think Amy put out an update to announcements.

W dniu wt., 19.11.2024 o 00:00 Amara Graham ***@***.***>
napisał(a):

**Comment by multani** [comment]
> BTW, 8.2 is technically unsupported since October, so we shouldn't add this to it.

I removed the update for 8.2 :+1:

**Comment by multani** [comment]
> Does this just need to be added to announcements before it can go live @multani?

I'm checkinf with @boooczek

**Comment by boooczek** [comment]
@christinaausley availability of the new region is already added to the announcements here: https://camunda.com/blog/2024/11/camunda-alpha-release-november-2024/
Unless you meant some other...? 

Btw: communication in GH doesn't work out well for me and I miss most of the mentions. Moving forward it'd be great if we cold move discussions to project channels with @-mentions. Thanks

**Comment by christinaausley** [comment]
@multani @akeller I added the same announcement to https://docs.camunda.io/docs/next/reference/announcements/ -- WDYT?

**Review by akeller — APPROVED** [review]
Thank you for the changes! We may adjust the announcement strategy in the future, but we'll take care of that within DevEx.

**Comment by multani** [comment]
Thanks @christinaausley and @akeller!

**Comment by christinaausley** [comment]
@multani Would you like this merged and released today?

**Pull request merged**
