### PR TITLE
docs(operations): Fix wrong information about update procedure

### PR DESCRIPTION
**Pull request by ManuelDittmar**
Overview page mentions rolling updates. However, rolling updates are not yet officially supported.

Also, the linked guide describes a cold update procedure.

https://github.com/camunda/product-hub/issues/256

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by christinaausley** [comment]
@ManuelDittmar I am not familiar with shutdown update -- can you explain this for me?

**Comment by ManuelDittmar** [comment]
> @ManuelDittmar I am not familiar with shutdown update -- can you explain this for me?

This term emphasizes the action of shutting down the system before applying the upgrade.

Alternatives:

Offline Upgrade, Cold Upgrade

**Comment by christinaausley** [comment]
I am okay with maintaining this term @ManuelDittmar as we note shutting down beforehand in the update guide. 

However, last question, is this an update or an upgrade? A software update is typically a release containing enhancements to the current version. An upgrade is a whole new version of software that represents a significant change or major improvement.

**Comment by ManuelDittmar** [comment]
@christinaausley That's a good question. It was previously called an update so I continued to call it update. Across the documentation we always classify it as on update. Only in combination with helm we call it an upgrade. In context of helm upgrade is a reserved command.

The update guide applies to both: minor and patch releases. As it's always a newer release within the same major version one can argue that it is an update in both cases.

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
