### PR TITLE
feat(feel): Add new built-in function

### PR DESCRIPTION
**Pull request by lzgabel**
## Description

Extend the FEEL documentation with the following new built-in function:
* https://github.com/camunda/feel-scala/issues/881

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process)
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process)

### CODE REVIEW

**Comment by lzgabel** [comment]
:wave: Hi @saig0, @christinaausley. Please take a moment to review this feature. :bow:

**Comment by akeller** [comment]
Since this is an external contribution, we can review and accept this PR, then backport changes in a separate PR.

**Comment by christinaausley** [comment]
Once @saig0 has approved, I will merge this and backport in a separate PR 👍

**Comment by saig0** [comment]
@christinaausley there is no need to backport the PR. The new function is only available in the next version (8.7).

**Pull request merged**
