### PR TITLE
docs(spring-zeebe-sdk): add missing spring sdk properties

### PR DESCRIPTION
**Pull request by nicpuppa**
## Description

Added missing Spring SDK properties
Added configuration for SaaS and SM cluster connections

closes: #3709 

## When should this change go live?

- [x] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineerring DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer.

### CODE REVIEW

**Comment by nicpuppa** [comment]
> @nicpuppa Is this still in `draft` because you have additional changes incoming, or is this ready for a final review?

Yes, we are adding more changes to the properties. I will ping you once is ready to be reviewed. Thanks @christinaausley 👍

**Comment by ana-vinogradova-camunda** [comment]
@christinaausley this is now ready for the review 🙂

**Review by ana-vinogradova-camunda — APPROVED** [review]
LGTM 👍

**Review by ana-vinogradova-camunda — APPROVED** [review]

**Review by koevskinikola — APPROVED** [review]
LGTM :rocket:

**Review by christinaausley — COMMENTED** [review]
Based on the description, but to confirm, this is **only** for 8.5 and not for the `next` version of docs, yes?

**Comment by ana-vinogradova-camunda** [comment]
> Based on the description, but to confirm, this is **only** for 8.5 and not for the `next` version of docs, yes?

Yes, that's correct.

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
