### PR TITLE
DO NOT MERGE Add Camunda Exporter to Announcements page

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by mesellings** [comment]
Hi @ChrisKujawa we already have a new draft Announcements PR in progress for alpha 2 https://github.com/camunda/camunda-docs/pull/4679 - can I just pull this content out from your PR and add it into this existing PR please?

**Comment by mesellings** [comment]
As agreed with @ChrisKujawa, I'll review this PR then bring the approved content into the draft Announcements PR

**Review by mesellings — DISMISSED** [review]
@ChrisKujawa I've reviewed and made amends directly to the text, I'm going to look at the images next, but looks good - I assume we are allowed/it is okay to expose our architecture to users like this?

**Comment by ChrisKujawa** [comment]
> I assume we are allowed/it is okay to expose our architecture to users like this?

In my opinion we should. I actually wanted to have anyway a better overview for our architecture. I would see this as first step

**Comment by mesellings** [comment]
@ChrisKujawa I've modified the Miro diagram for the harmonized schema - it's just a quick alignment on colours, accessibility (e.g. text on block colours is bad for accessibility), but will do until i can take. alook at our diagramming standards across the board (it's on the wishlist).

image

**Comment by ChrisKujawa** [comment]
Love it ! Thank you 🙏🏼

**Comment by mesellings** [comment]
@ChrisKujawa I've added the second diagram now as well - let me know when you have made your changes.

image


Note: I've locked these two diagrams on the Miro board so we don't change accidentally - Miro can be a bit flaky sometimes).

**Comment by ChrisKujawa** [comment]
Thanks @mesellings for your efforts 👍🏼

**Comment by mesellings** [comment]
@ChrisKujawa Are you happy for me to port the content over into the Announcements PR, or are you waiting for any other reviewer?

**Comment by ChrisKujawa** [comment]
I think we fine now @mesellings. I also got positive feedback from Amara so I think we are good.

**Comment by akeller** [comment]
> I think we fine now @mesellings. I also got positive feedback from Amara so I think we are good.

🧠 🤝 🧠 (even if I'm slower, by 2 min 😆)

**Comment by mesellings** [comment]
@ChrisKujawa I've taken the content from this PR now, so it can be closed - thanks for your help with this, great work 👍 🚀

**Pull request closed without merging**
