### PR TITLE
add helm variant of keycloak instructions, fix link

### PR DESCRIPTION
**Pull request by conceptualshark**
## Description

Fixes broken link in https://github.com/camunda/camunda-docs/issues/4690
Creates a separate Helm section so Helm users do not accidentally follow the full guide and create a duplicate config, resolves https://github.com/camunda/camunda-docs/issues/4684

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by conceptualshark** [comment]
Will backport this once the adjustment is approved.

**Review by jessesimpson36 — DISMISSED** [review]
This works for me.

**Comment by conceptualshark** [comment]
With engineering approval, this has been backported for @camunda/tech-writers review, including some link cleanup.

**Review by christinaausley — APPROVED** [review]
Crisp and clean 🚀

**Pull request merged**
