### PR TITLE
feat(console-sm): add envvar to disable auth

### PR DESCRIPTION
**Pull request by urbanisierung**
## Description

- Relates https://github.com/camunda-cloud/camunda-cloud-management-apps/issues/2887 https://github.com/camunda/product-hub/issues/2160

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer.

### CODE REVIEW

**Comment by urbanisierung** [comment]
@theburi @ultraschuppi Small PR that describes how to disable Authentication for Console. It's basically a new environment variable. Please have a brief look into this.

**Comment by christinaausley** [comment]
Is this needed for the alpha release tomorrow?

**Comment by urbanisierung** [comment]
> Is this needed for the alpha release tomorrow?

No, still waiting for green lights from QA.

**Comment by urbanisierung** [comment]
@christinaausley We finally got green lights from QA. The changes will be part of 8.6 alpha4 - can I just merge this one?

**Review by christinaausley — APPROVED** [review]

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
