### PR TITLE
feat: add documentation for filepicker element

### PR DESCRIPTION
**Pull request by vsgoulart**
## Description

Documentation for new `form-js` element.

Related to https://github.com/camunda/product-hub/issues/2409

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by volodymyr-melnykc** [comment]
I noticed that the visual preview of form component icons is very small. It's not only for a filepicker component but all form components.
The icon size is 12x12px (because the image container has a padding in 20px). It makes it difficult to recognize the icon.

Screenshot 2024-10-28 at 09 59 21

I noticed that this issue already exists and not introduced with this PR: https://docs.camunda.io/docs/components/modeler/forms/form-element-library/forms-element-library-text/
Yet, maybe we should fix it here?
@vsgoulart @christinaausley

**Comment by vsgoulart** [comment]
@volodymyr-melnykc I'll take a look

**Comment by vsgoulart** [comment]
@volodymyr-melnykc Please check the last commit

**Comment by vsgoulart** [comment]
I'll make another commit fixing the previous versions too

**Comment by volodymyr-melnykc** [comment]
@vsgoulart The form component icons look good now, thank you!

**Review by christinaausley — DISMISSED** [review]
Nice work!

**Comment by vsgoulart** [comment]
Now's it's fixed on the versioned docs also

**Review by christinaausley — APPROVED** [review]

**Review by volodymyr-melnykc — APPROVED** [review]

**Comment by mesellings** [comment]
@vsgoulart Are we okay to merge and release this so it is live for the release tomorrow?

**Pull request merged**
