### PR TITLE
fix(self-managed/zeebe): correct MT feature flag

### PR DESCRIPTION
**Pull request by nikku**
## Description

Using the updated flag I got [multi-tenancy working](https://github.com/camunda/camunda-platform/commit/9fc85a1c93c69144d8527c01d73321178de6e55d#diff-3fde9d1a396e140fefc7676e1bd237d67b6864552b6f45af1ebcc27bcd0bb6e9R25).

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by nikku** [comment]
Found the alternative working for MT setup: https://github.com/camunda/camunda-platform/pull/429/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R213.

**Comment by christinaausley** [comment]
@nikku I know other Nico is out on FTO until the new year -- let me know if I can assist with this or review 👍

**Comment by nikku** [comment]
This is [pending clarification from the zeebe team](https://camunda.slack.com/archives/CSQ2E3BT4/p1702303163960329) on what they implemented. Not sure how others can help. But if you want we can of course go ahead and merge this :).

**Comment by christinaausley** [comment]
@nikku if there is no rush on merging this in, we can wait until you have the answers you're looking for 😄

**Comment by akeller** [comment]
I will follow up on this. If the flag is incorrect, we need to get this changed in documentation ASAP.

**Comment by koevskinikola** [comment]
@nikku the MT feature flag is not wrong.

A Zeebe Gateway can be started in two ways:
* Standalone
* Embedded

For the `StandaloneGateway`, the configuration options are documented [here](https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/gateway-config/).

The `EmbeddedGateway` is embedded in the `StandaloneBroker`, and the documentation on how to configure it is a bit dispersed:
* The flag to enable it is documented [here](https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/broker-config/#zeebebrokergateway). And we point to the `Gateway configuration` docs in the same section.
* At the beginning of the [Gateway configuration](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/configuration/gateway-config/) page, we note:
   > If you're configuring a gateway that is embedded inside of a broker (i.e. you've set [zeebe.broker.gateway.enable](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/configuration/broker-config/#zeebebrokergateway)), then you must use zeebe.broker.gateway.* instead of zeebe.gateway.* for any of the configuration options below. For environment variables this means you must use ZEEBE_BROKER_GATEWAY_* instead of ZEEBE_GATEWAY_*.

So the environment variables documented in the [Gateway configuration](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/configuration/gateway-config/) page are correct, when used for the `StandaloneGateway`. And we note at the beginning of the same page how the configuration properties and environment variable names should be adjusted if the embedded Gateway is used.

Should we close this PR?

**Review by koevskinikola — COMMENTED** [review]
@nikku the MT feature flag is not wrong.

A Zeebe Gateway can be started in two ways:
* Standalone
* Embedded

For the `StandaloneGateway`, the configuration options are documented [here](https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/gateway-config/).

The `EmbeddedGateway` is embedded in the `StandaloneBroker`, and the documentation on how to configure it is a bit dispersed:
* The flag to enable it is documented [here](https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/broker-config/#zeebebrokergateway). And we point to the `Gateway configuration` docs in the same section.
* At the beginning of the [Gateway configuration](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/configuration/gateway-config/) page, we note:
   > If you're configuring a gateway that is embedded inside of a broker (i.e. you've set [zeebe.broker.gateway.enable](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/configuration/broker-config/#zeebebrokergateway)), then you must use zeebe.broker.gateway.* instead of zeebe.gateway.* for any of the configuration options below. For environment variables this means you must use ZEEBE_BROKER_GATEWAY_* instead of ZEEBE_GATEWAY_*.

So the environment variables documented in the [Gateway configuration](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/configuration/gateway-config/) page are correct, when used for the `StandaloneGateway`. And we note at the beginning of the same page how the configuration properties and environment variable names should be adjusted if the embedded Gateway is used.

Should we close this PR?

**Comment by nikku** [comment]
Let's close this PR, and consider if we want to follow-up with the following:

As a user I learn how to configure multi-tenancy via https://docs.camunda.io/docs/self-managed/concepts/multi-tenancy/#multi-tenancy-in-camunda-8, linking to the _Zeebe Gateway_ configuration for MT. At this point I have no indication that there exists a related configuration for broker only setups, I'm effectively stuck.

**Pull request closed without merging**
