### PR TITLE
feat(element-templates): added "implementationType" property for execution listeners

### PR DESCRIPTION
**Pull request by AlexanderSkrock**
Supports solving the following issue: https://github.com/bpmn-io/bpmn-js-element-templates/issues/13
Reflects changes in behaviour proposed with: https://github.com/bpmn-io/bpmn-js-element-templates/pull/17

### CODE REVIEW

**Comment by akeller** [comment]
@barmac @nikku can you please review?

**Comment by barmac** [comment]
Hi, I'm on it, but want to first merge the documented feature.

**Comment by akeller** [comment]
> [CLA assistant check](https://cla-assistant.io/camunda/camunda-docs?pullRequest=2667) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda-docs?pullRequest=2667) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda-docs?pullRequest=2667) it.

Hi @AlexanderSkrock, we had some issues with our CLA over the last few days. Can you please sign it?

**Comment by AlexanderSkrock** [comment]
> Hi @AlexanderSkrock, we had some issues with our CLA over the last few days. Can you please sign it?

I just resigned the CLA and according to pull request checks it seems to be alright now.

Kind regards
Alexander Skrock

**Review by barmac — APPROVED** [review]
This documents precisely what was implemented via https://github.com/bpmn-io/bpmn-js-element-templates/pull/17. The documentation change will apply only to the future releases.

**Comment by barmac** [comment]
If there's 👍 from you then I believe it's ready to be merged :)

**Comment by AlexanderSkrock** [comment]
I agree with @barmac , all related pull requests are merged.

**Pull request merged**
