### PR TITLE
Remove mention of OS2.5+ support

### PR DESCRIPTION
**Pull request by johanwelgemoed**
Remove mention of OS2.5+ support since it will only be announced for Camunda 8.4 release when it is supposed across all components.

## When should this change go live?

- [x] This change is not yet live and should not be merged until 8.3 is released (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — APPROVED** [review]

**Comment by akeller** [comment]
Following up here - https://camunda.slack.com/archives/C04QG866E3Z/p1695308089698259?thread_ts=1695276016.988959&cid=C04QG866E3Z

**Comment by johanwelgemoed** [comment]
In original pr I also removed the mention of OS1.3 support from the versioned docs. This was a mistake so I put it back.

**Comment by christinaausley** [comment]
Let me know if you need any additional assistance with this or with the build and when you are ready for final review 👍

**Comment by johanwelgemoed** [comment]
@christinaausley I think this one should be ok to review. When I initially did it I was a bit overzealous and removed the mentioned of OpenSearch support in the `/next` as well as `/versioned` docs. It should actually only be removed for the upcoming version, so I put the mention back in the 8.2 parts.

**Review by christinaausley — APPROVED** [review]
This should be good to go -- but I noticed with versioning you swapped a few things back in/out. To confirm, we will have this removal in the 8.4 version, and the Elasticsearch note should remain in 8.2?

If so, I'll remove the label and merge this late this week/early next week before the release.

**Comment by johanwelgemoed** [comment]
Yes, it stays in 8.2 but is removed from 8.3
________________________________

**Comment by christinaausley** [comment]
@johanwelgemoed Please sign the CLA and we can get this merged 👍 Removed the `hold` label!

**Pull request merged**
