### PR TITLE
docs(kafka): Schema registry documentation

### PR DESCRIPTION
**Pull request by johnBgood**
## Description

Feature Request: support for schema registry in the Kafka connector.
It will be released with **8.6** (not backported).

Related issues: 
- https://github.com/camunda/team-connectors/issues/874
- https://github.com/camunda/team-connectors/issues/646

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Review by mesellings — APPROVED** [review]
@johnBgood I've committed my changes directly to the branch as follows:

* Structural, grammar, readability, standards modifications

I made quite a lot of changes to improve the page that were not connected to this PR, but felt it was worth including them to improve the page and integrate your changes better.

Happy to approve, great job 🚀 👍

**Comment by johnBgood** [comment]
@akeller I guess we can't merge this, right? It's for 8.6.0.

**Comment by mesellings** [comment]
@johnBgood I don't see a reason why we can't merge this into the `Next` docs for the 8.6 release, unless there is something I'm perhaps not aware of?

**Comment by johnBgood** [comment]
Sorry typo...I meant "we can" :) I agree

**Comment by mesellings** [comment]
> Sorry typo...I meant "we can" :) I agree.
> 
> There's a build error though, not sure why

Great - I'll check that out and get this merged 👍

**Comment by mesellings** [comment]
@johnBgood This can be merged now (just needed to merge main in) 👍 I can also merge if you prefer?

**Comment by johnBgood** [comment]
Feel free to proceed, thank you :)

**Pull request merged**
