### PR TITLE
docs(operate): add child instances to supported elements in instance migration guide

### LINKED ISSUE #3924: Document child instances migration in Operate user guide
### Description

In Operate it will be possible to migrate child instances in process instance migration mode.

### TODO

The documentation needs to be updated:

- [x] add child instances to the allowed elements

### Related issues
- https://github.com/camunda/camunda/issues/18594

### PR DESCRIPTION
**Pull request by vitorwtavares**
## Description

Adds child instances to supported elements in instance migration guide.

relates to https://github.com/camunda/camunda/issues/18594
closes #3924 

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by akeller** [comment]
@vitorwtavares is this for alpha3? Or do we need to move quickly and review/release today?

**Comment by vitorwtavares** [comment]
> @vitorwtavares is this for alpha3? Or do we need to move quickly and review/release today?

The current part will most likely be for alpha3, but we do need to move quickly because the 8.5 part will be shipped in a patch this week and this feature was promised to some clients, so that's the urgent part. Given that, if we could prioritize it that would be great.

**Review by pedesen — APPROVED** [review]

**Review by conceptualshark — APPROVED** [review]

**Comment by vitorwtavares** [comment]
@akeller @conceptualshark Can this be merged or does it require additional reviews?

**Comment by christinaausley** [comment]
@vitorwtavares Feel free to merge when you're ready and I'll get a release out 👍

**Comment by akeller** [comment]
Based on the conversation here, let's merge this now. Thanks for the context @vitorwtavares.

**Pull request merged**
