### PR TITLE
Remove stale Connectors update guide

### PR DESCRIPTION
**Pull request by akeller**
## Description

Via https://camunda.slack.com/archives/C02JLRNQQ05/p1731098751001189.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Review by sbuettner — DISMISSED** [review]
🥳

**Comment by akeller** [comment]
@sbuettner, I removed the admonition in the connectors that pointed to the update guide because it also looked stale. Please take a look at that change specifically, but that should correct any link issues detected by the build workflow.

**Comment by akeller** [comment]
@pepopowitz, can you look at these build errors? It looks like the partials aren't playing nice, but I didn't touch them in this PR. Any ideas?

**Comment by pepopowitz** [comment]
Yeah, I'm not sure what this is about either. I pulled the branch locally, and the links it's complaining about work for me.

I kicked off a re-run of build-docs, hoping it was a blip? 🤞

**Pull request closed without merging**
