### PR TITLE
docs(web-modeler): update supported envs for pg-16

### PR DESCRIPTION
**Pull request by JacobiCamunda**
## Description

This updates the supported environments page to reflect the support of Postgres 16.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [x] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
@JacobiCamunda, as this list grows, would it be fair to say 13+ in the future? We don't appear to be deprecating support for older versions, so I'd like to know if we can clean this up or if we need to be specific about the exact major version for any reason.

**Comment by JacobiCamunda** [comment]
> @JacobiCamunda, as this list grows, would it be fair to say 13+ in the future? We don't appear to be deprecating support for older versions, so I'd like to know if we can clean this up or if we need to be specific about the exact major version for any reason.

That's a good idea. But this would imply that we would always support all versions above 13. We do, but when a new version comes out, we have to check that and a new aurora version environment has to be set up for us to run tests again to be sure we really do. Meanwhile, customers could think we support the newest version, when in reality we don't know yet until tested. @jfriedenstab what do you think?

**Comment by jfriedenstab** [comment]
@JacobiCamunda I agree, let's continue to list the specific versions we have tested.

@akeller: We will also remove support for older Postgres versions when they have reached their end-of-life date (according to https://www.postgresql.org/support/versioning/).

**Review by jfriedenstab — APPROVED** [review]

**Comment by akeller** [comment]
Thanks @JacobiCamunda @jfriedenstab, fair enough. If you ever move to support all supported versions (including the most recently released), we should change this, but for now, this makes sense.

**Pull request merged**
