### PR TITLE
Documentation for styling customization in Tasklist

### PR DESCRIPTION
**Pull request by volodymyr-melnykc**
## Description

Closes https://github.com/camunda/camunda-docs/issues/4257

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by mesellings** [comment]
@volodymyr-melnykc Do you want me to do a technical writing review for this once @marcosgvieira has reviewed?

**Comment by mesellings** [comment]
@volodymyr-melnykc Bearing in mind we only have a few days left before alpha 5 release, I will do a review now and add commits to the branch, before @marcosgvieira has performed a review 👍

**Review by mesellings — APPROVED** [review]
@volodymyr-melnykc I've committed some review changes as follows:
* Restructured page to bring the task to the top/front
* Text edits for readability, active voice etc
* Removed the Carbon Design system benefits section - this seemed superfluous?

Lgtm - happy to approve 👍

**Comment by mesellings** [comment]
@volodymyr-melnykc Outside of the scope for this PR bearing in mind the alpha 5 deadline, but I created docs for something similar to this at Boomi - an example of styling might be useful, e.g. show the most common tokens actually in use and how Tasklist could look after the customization.

https://help.boomi.com/docs/Atomsphere/Flow/topics/c-flo-CSS_Using_CSS_Tutorial_39a3be31-b53a-432e-947d-70f34bf1b0e2

**Review by mesellings — APPROVED** [review]
Re-approved after commit

**Comment by volodymyr-melnykc** [comment]
Thank you for the refinements, @mesellings! And thank you for the reference to the Boomi documentation! That's something we can take inspiration from, especially showing how Tasklist can look after CSS customizations. I'll create a follow-up issue for it.

**Review by marcosgvieira — APPROVED** [review]
Nice work @volodymyr-melnykc! LGTM!

**Comment by mesellings** [comment]
@volodymyr-melnykc Shall I merge this for you?

**Pull request merged**
