### PR TITLE
feat(forms): document group element

### PR DESCRIPTION
**Pull request by Skaiir**
Related to bpmn-io/form-js#767

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
@Skaiir 8.3. release is coming closer, so I think we can slowly start reviewing this 👍

**Review by christinaausley — COMMENTED** [review]
This looks good, but I'm slightly worried about our usage of the term "component" given we reference our product (Tasklist, Console, etc) as components. Is there another term we could use here?

**Comment by akeller** [comment]
Does this need to be pulled out of draft? We've cut the 8.3 release, so you'll need to backport these changes to 8.3.

**Comment by akeller** [comment]
Checked in with @Skaiir via DM and sounds like there will be some progress on this tomorrow.

**Comment by Skaiir** [comment]
@christinaausley Hey, I have changed the usage of components and backported. Let me know if there's anything else. 👍

**Review by christinaausley — APPROVED** [review]

**Comment by christinaausley** [comment]
Thank you @Skaiir! Feel free to enable auto-merge, or merge when you are ready. Does this need to go live today with a release?

**Comment by Skaiir** [comment]
@christinaausley No rush, I think we're fine if there's a release happening some time next week :)

**Pull request merged**
