### PR TITLE
clarify dependencies between performance, retention time and disk space

### PR DESCRIPTION
**Pull request by hisImminence**
## Description

Based on the discussions with @chDame, this PR should clarify the dependencies on performance, data retention time configuration and ES disk space more clearly.

* Assigning @chDame to check if this PR _really_ enlightens the mentioned dependencies
* Assigning @rodrigo-lourenco-lopes to verify the technical details make sense
* Assigning @mesellings as the main DRI for this page 

--> this change is relevant for 8.6+

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [x] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Review by mesellings — APPROVED** [review]
Lgtm - I've committed some small changes to help with readability & conciseness 👍

**Review by chDame — APPROVED** [review]
Seems good to me.

**Review by rodrigo-lourenco-lopes — APPROVED** [review]
The new details added make sense. Thanks 🙌

**Comment by akeller** [comment]
Whoops, looked like this was missed. Merging!

**Pull request merged**
