### PR TITLE
fix(aws-marketplace): removes options typically used in testing

### PR DESCRIPTION
**Pull request by jessesimpson36**
## Description

closes: https://github.com/camunda/aws-marketplace-dockerfiles/issues/25

I included some options that one typically does not set in a production instance. things such as setting the zeebe cluster size to 1 and setting a small pvc size for storage.  These options should go back to their default values.

I'm placing a hold on this PR and putting it in draft mode until I guarantee that this configuration works on AWS using the aws marketplace install guide.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by HamzaMasood1 — APPROVED** [review]
Makes sense 👍

**Comment by christinaausley** [comment]
Nothing to add here 😄

**Comment by jessesimpson36** [comment]
I have done my testing on the AWS Marketplace instructions. :+1:

**Comment by christinaausley** [comment]
@jessesimpson36 If you want to backport, feel free to launch in a separate PR 😄 Merging this!

**Pull request merged**
