### PR TITLE
feat(backup): document the "dual-regions backups" feature for C8 SaaS

### PR DESCRIPTION
**Pull request by multani**
## Description

Documentation for the new product feature from https://github.com/camunda/product-hub/issues/1752

## When should this change go live?

- [x] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by christinaausley** [comment]
Applying a `hold` label until I can review -- this is slated for the `8.5` release, yes?

**Comment by multani** [comment]
@christinaausley we aim to release this officially as part of 8.5 Alpha-1 :+1:

**Review by christinaausley — DISMISSED** [review]
This looks good. Is this still in draft because you have additional changes to make? If not, we can go ahead and take it out of draft but retain the `hold` label so this isn't merged too early.

**Comment by multani** [comment]
> This looks good. Is this still in draft because you have additional changes to make? If not, we can go ahead and take it out of draft but retain the `hold` label so this isn't merged too early.

I set it as a draft because I wasn't sure about the wording nor the overall approach :)

I'll open it for review, @theburi can you take a look, thanks!

**Comment by multani** [comment]
(and thanks for the review/fixes @christinaausley ! :bow: )

**Review by felix-mueller — APPROVED** [review]
lgtm

**Comment by akeller** [comment]
Looks good @multani! We'll take it from here and merge and release with the alpha 😎

**Comment by multani** [comment]
Thanks all of you! :bow:

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
