### PR TITLE
Self-Managed > Installation restructure (v2)

### PR DESCRIPTION
**Pull request by akeller**
## Description

Introduces a restructure to the Installation section, only in `/next/`. 

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
@christinaausley @pepopowitz I added redirects as best I could, but please double-check them! They are only on `/next/` at this point.

**Comment by christinaausley** [comment]
@pepopowitz this looks good to me but would like a second set of eyes on the redirects as well.

@hisImminence @aabouzaid @theburi @jessesimpson36 -- any final comments here before we wrap this up?

**Review by aabouzaid — CHANGES_REQUESTED** [review]
The same as @theburi mentioned for the `deploy`, also the `upgrade` page is not there.

**Comment by aabouzaid** [comment]
I've also added the new self-managed icon that was created by the design team.

**Review by pepopowitz — APPROVED** [review]
Redirects look good to me! There's probably a little bit of consolidation that could be done with some of the folders, but I can handle that when we get to release time. We won't really know if we found all of them until then anyway, since vNext redirects aren't checked.

**Comment by christinaausley** [comment]
@aabouzaid @theburi I went ahead and added the `upgrade` doc into the sidebar.

@pepopowitz Can you have a look at why `deploy` isn't showing up on build? I'm looking at lines 810-816 and not sure the best way to format this.

**Review by aabouzaid — CHANGES_REQUESTED** [review]
@christinaausley the `install` and `upgrade` should be under the `deploy` section.

**Comment by pepopowitz** [comment]
@christinaausley re: the "Deploy" page -- as far as I can tell, it _is_ showing up in the sidebar. It's configured as a category, with a docId, so clicking the category name (Deploy) itself takes you to a page. 

This is what I see when I run locally - 

image


I'm having a hard time understanding all the context of this conversation though, so I could very well be missing something.

**Comment by pepopowitz** [comment]
Oh, and if you wanted the "Deploy" _page_ to be a separate left nav option than the "Deploy" _category_, listed at the top ahead of "Amazon (AWS)", you would remove the `link` element from the "Deploy" category, and add the item `"self-managed/installation/deploy/deploy"` to the `items` array of the "Deploy" category.

**Comment by christinaausley** [comment]
Alright @aabouzaid -- I think I've got it this time based on our Slack convo.

**Comment by aabouzaid** [comment]
@christinaausley close but not exactly :sweat_smile: 

I made a small change and how it looks like now:

Screenshot 2024-04-05 at 02-37-52 Camunda 8 Self-Managed Camunda 8 Docs

This is what in [70b8a45](https://github.com/camunda/camunda-docs/pull/3476/commits/70b8a45c797b61a9e47f19a344a6e32df91e9983).

In [8b01b7a](https://github.com/camunda/camunda-docs/pull/3476/commits/8b01b7ac131ceb894d7632adb143e11d56df574c) I've renamed the section `installation` to `setup` since it's a better name that covers all sub-sections (install, upgrade, deploy, etc).

**Review by aabouzaid — APPROVED** [review]

**Review by theburi — APPROVED** [review]

**Comment by christinaausley** [comment]
@pepopowitz Sorry for the overlap here with sidebar syncing, but I think this is good to go. Adding you as a reviewer for one more look.

**Comment by pepopowitz** [comment]
> @pepopowitz Sorry for the overlap here with sidebar syncing, but I think this is good to go. Adding you as a reviewer for one more look.

No worries! Let's get this one merged first, and then I'll redo #3600.

**Review by pepopowitz — DISMISSED** [review]
If @aabouzaid is happy, I am happy!

**Review by pepopowitz — APPROVED** [review]

**Comment by christinaausley** [comment]
@akeller This was our OOO gift to you. Future iterations/adjustments should be made in a separate PR 😄

**Comment by akeller** [comment]
Oh my goodness! Thank you @christinaausley @aabouzaid @pepopowitz! 😍 🥰 Thank you for pushing this through. I hope this gets us well on the way to an improved experience in these docs.

**Pull request merged**
