### PR TITLE
adjust doc card length and descriptions

### PR DESCRIPTION
**Pull request by christinaausley**
## Description

Closes https://github.com/camunda/camunda-docs/issues/2569 and https://github.com/camunda/developer-experience/issues/144.

🍐 **Paired work with @pepopowitz**.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by christinaausley** [comment]
Tuesday update:

@pepopowitz and I met today, and successfully added an Optimize description!

As far as card sizing goes:

`display: -webkit-box;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 2;
    overflow: hidden;`
    
We applied those properties to the `p` element within a card.

1. We need to investigate further which browsers this will/won’t work on (specifically worried about this -webkit-box-orient property, and the value -webkit-box because we only looked at webkit-line-clamp.
2. Apply it via a CSS selector, on the CardLayout component of src/theme/DocCard/index.

Planning to look into this as time allows this week 👍

**Comment by christinaausley** [comment]
> We need to investigate further which browsers this will/won’t work on (specifically worried about this -webkit-box-orient property, and the value -webkit-box because we only looked at webkit-line-clamp.

It looks like less than 1% of global users would run into an issue, and it's only for old _old_ versions and IE browser. I think this should be just fine.

**Comment by christinaausley** [comment]
@pepopowitz I almost cried when I got this (at least, locally) on my first build.

I just added the properties to `src/theme/DocCard/styles.module.css` -- please have a look and let me know if you have any critiques.

I may just update the length of the Console description, since it looks weird as the only overflow fellow.

**Review by MaxTru — APPROVED** [review]

**Review by pepopowitz — APPROVED** [review]
This looks great! I confirmed the expected behavior in Chrome, Firefox, and Safari locally. 💪

**Pull request merged**
