### PR TITLE
Add sentence how to support custom idempotency handling

### PR DESCRIPTION
**Pull request by ingorichtsmeier**
## Description

We describe in words how idempotency can be handled, but a snippet of a process model should make it easier to understand it.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [X] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [X] they are not for an **already released version**.
- [X] I have added changes to the main `/docs` directory (aka `/next/`).
- [X] My changes do not require an Engineering review.
- [X] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer.

### CODE REVIEW

**Comment by christinaausley** [comment]
@berndruecker Mind having a peak at the BPMN?

**Comment by berndruecker** [comment]
I am not a huge fan of having this as a service task - shouldn't that be hidden in a Listener (as soon as Camunda 8 supports it - which is some time next year) @ingorichtsmeier?

But it is not wrong either...

**Comment by christinaausley** [comment]
@ingorichtsmeier you'll need to sign the CLA and address Bernd's comments, then I can approve and merge 👍

**Comment by christinaausley** [comment]
Hi @ingorichtsmeier -- is this still a work in progress?

**Comment by ingorichtsmeier** [comment]
Hi @berndruecker, service task makes it explicit, listener is information hiding. It depends...

Depending on the required ID, a feel expression with `random number()` could be sufficient.

But I would get more real world experience before adding more tips here.

Could you please check the approved, if you think it's OK for publication? I think it helps a lot in customer conversations to have a BPMN example.

**Review by berndruecker — APPROVED** [review]
Still not a big fan of this extra service task - but if you feel it is helpful in conversations lets add it

**Comment by christinaausley** [comment]
@ingorichtsmeier If you are good with this, feel free to merge when ready.

**Pull request merged**
