### PR TITLE
feat: update screenshots to Desktop Modeler 5.26.0

### PR DESCRIPTION
**Pull request by barmac**
Related to https://github.com/camunda/camunda-modeler/issues/4416

## Description

This PR updates the screenshots to Desktop Modeler 5.26.0

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by barmac** [comment]
> 👋 🤖 🤔 Hello! Did you make your changes in all the right places?
> 
> These files were changed only in _versioned_docs/version-8.5/_. You might want to duplicate these changes in _docs/_.
> 
> * versioned_docs/version-8.5/components/modeler/desktop-modeler/img/deploy-icon.png
> * versioned_docs/version-8.5/components/modeler/desktop-modeler/img/start-instance-icon.png
> * versioned_docs/version-8.5/self-managed/modeler/desktop-modeler/img/deploy-icon.png
> 
> You may have done this intentionally, but we wanted to point it out in case you didn't. You can read more about the versioning within our docs in our [documentation guidelines](https://github.com/camunda/camunda-docs/blob/c666b7e5e35bfe31468ce4ac679ea7b62ab86d73/howtos/documentation-guidelines.md#versions).

This does not look right as the mentioned files are replaced in the PR.

**Comment by christinaausley** [comment]
> > 👋 🤖 🤔 Hello! Did you make your changes in all the right places?
> > These files were changed only in _versioned_docs/version-8.5/_. You might want to duplicate these changes in _docs/_.
> > 
> > * versioned_docs/version-8.5/components/modeler/desktop-modeler/img/deploy-icon.png
> > * versioned_docs/version-8.5/components/modeler/desktop-modeler/img/start-instance-icon.png
> > * versioned_docs/version-8.5/self-managed/modeler/desktop-modeler/img/deploy-icon.png
> > 
> > You may have done this intentionally, but we wanted to point it out in case you didn't. You can read more about the versioning within our docs in our [documentation guidelines](https://github.com/camunda/camunda-docs/blob/c666b7e5e35bfe31468ce4ac679ea7b62ab86d73/howtos/documentation-guidelines.md#versions).
> 
> This does not look right as the mentioned files are replaced in the PR.

CC @pepopowitz, not sure if I'm missing something here?

FYI @barmac I'm pushing out a release now, but can ship out another once this is approved 👍

**Comment by barmac** [comment]
Thanks for clarification. That wasn't intentional but just a side effect of the new images being exactly identical as the old ones. So git didn't detect any changes as there were none for these 3 files 😅. That's OK though and we can proceed with the PR.

> FYI @barmac I'm pushing out a release now, but can ship out another once this is approved 👍

Sure, thank you for update.

**Review by akeller — APPROVED** [review]
The footer looks correctly updated for these screenshots, so it gets my 👍

**Pull request merged**
