### PR TITLE
feat(releaseNotes): provide more detailed notes

### PR DESCRIPTION
**Pull request by MaxTru**
Hi @akeller ,

with this PR I am suggesting some pragmatic improvements to the release notes pages. I thought about the following:

* Grouping: I used the buttons to indicate which components are affected by an enhancement. Maybe another tool than "buttons" are more effective to do that (the current buttons impact the heading anchor, which doesn't make sense). I think some sort of grouping is important given we have more an more features for a release.
* Release Dates: This is IMO a key info.
* Links to full changelog: This allows technically interested users to find out more.

Can you please drive this further?

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer.

### CODE REVIEW

**Comment by akeller** [comment]
@MaxTru, quick comment - We have release dates available on the [Announcements page](https://docs.camunda.io/docs/reference/announcements/). Do you expect them in both places? 

Similar question, the release blog and release notes (or what I start to refer to as the changelog) are on the [Update guide](https://docs.camunda.io/docs/self-managed/operational-guides/update-guide/introduction/). Do you expect them in both places?

I'll use this as the next iteration after https://github.com/camunda/camunda-docs/pull/3785.

**Comment by MaxTru** [comment]
> @MaxTru, quick comment - We have release dates available on the [Announcements page](https://docs.camunda.io/docs/reference/announcements/). Do you expect them in both places?

I think it makes sense to have them in both places, yes.

On-top, I think we should deep-link from the announcements page, to release notes page.

> Similar question, the release blog and release notes (or what I start to refer to as the changelog) are on the [Update guide](https://docs.camunda.io/docs/self-managed/operational-guides/update-guide/introduction/). Do you expect them in both places?

Why do we link the changelog from the update guide? I think linking them from release notes would make more sense, doesn't it? Same for link to blog post.

**Comment by akeller** [comment]
> Why do we link the changelog from the update guide? I think linking them from release notes would make more sense, doesn't it? Same for link to blog post.

No reason, just history. Update guide came first. 🙂 

Will take it from here in iterations and add to https://github.com/camunda/developer-experience/issues/304.

**Comment by akeller** [comment]
Closing this will create a new issue, specifically around the groupings.

**Pull request closed without merging**
