### PR TITLE
fix: added helm equivalent values for env vars for generic oidc provider

### PR DESCRIPTION
**Pull request by jessesimpson36**
## Description

Previously, there were environment variables recommended to users who wish to authenticate with an OIDC provider (or Azure).  Existing helm chart users would read this documentation and expect to add env vars rather than configuring the helm chart options designed for this purpose.

This change includes 2 possible views of code snippets on this guide, 
1. One to view the environment variables necessary to configure
2. One to view the equivalent values.yaml variables necessary to edit.

## When should this change go live?

Hopefully prior to 8.4 release.

Also, should be merged after this PR gets merged:
https://github.com/camunda/camunda-platform-helm/pull/1155

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by jessesimpson36** [comment]
2023-12-15-125723_grim
2023-12-15-125715_grim

**Review by christinaausley — APPROVED** [review]
Technical review in latest commit, though @aabouzaid may have additional thoughts.

**Comment by jessesimpson36** [comment]
Ahmed is out for the day, so I'm assigning Hamza

**Comment by christinaausley** [comment]
Given https://github.com/camunda/camunda-platform-helm/pull/1155 is merged in, I'm going to merge this as well 👍

**Comment by jessesimpson36** [comment]
Thank you @christinaausley ! I was just about to write that you can merge it!

**Pull request merged**
