### PR TITLE
Instance migration enhancements

### PR DESCRIPTION
**Pull request by conceptualshark**
## Description

Relates to [#1831](https://github.com/camunda/product-hub/issues/1831), documenting features listed in proto-documentation only. 

Note that screenshot updates are not within scope to move this PR quickly.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Review by gastonpillet01 — DISMISSED** [review]
Instructions look clear for me. Approving.

**Comment by akeller** [comment]
@gastonpillet01, just to confirm - the backporting is correct? From 8.4+?

**Comment by gastonpillet01** [comment]
@akeller - no, the improvements will not be backported. They are available from 8.3.0-alpha3+

**Review by akeller — CHANGES_REQUESTED** [review]
This is only applicable to `/next/`.

**Review by akeller — APPROVED** [review]

**Review by gastonpillet01 — APPROVED** [review]
Approving

**Pull request merged**
