### PR TITLE
Add Components grouping to SM

### PR DESCRIPTION
**Pull request by akeller**
## Description

Low-effort way to start restructuring SM sidebar content. This change is only in `/next/` and may be merged and released to gather feedback.

Goes from this, with each component at the top level of the side bar:
image

To this, with component docs/config in a single group: 
image

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
Internally we've had a lot of opinions about this, so I've added a poll - https://camunda.slack.com/archives/C026U8GBNSW/p1705704967496659

**Review by christinaausley — APPROVED** [review]

**Comment by akeller** [comment]
Something looks a bit off with this PR. Let me update the branch.

**Comment by akeller** [comment]
Interesting, the diff makes it look like there were name changes, but I only wrapped the components in `Components: [].` Since the lines moved a bit, it came across as more changes to the PR.

**Comment by akeller** [comment]
Merging as-is. Will backport as part of the alpha in a separate PR.

**Pull request merged**
