### PR TITLE
Update connecting-the-workflow-engine-with-your-world.md

### PR DESCRIPTION
**Pull request by berndruecker**
softened language around connectors and updated to improved connector infrastructure

From [Slack](https://camunda.slack.com/archives/C026U8GBNSW/p1730729265222839)

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Review by sbuettner — APPROVED** [review]
LGTM

**Comment by mesellings** [comment]
@berndruecker Would you like a TW review on this?

**Review by mesellings — APPROVED** [review]
LGTM - I just made some edits to Connector/connector casing & slight rewording on line 218, and also 'forwardported' your changes to /next/ version docs 👍 🚀

**Comment by mesellings** [comment]
@berndruecker Would you like me to merge and release this for you?

**Comment by akeller** [comment]
> @berndruecker Would you like me to merge and release this for you?

I got it for him :)

**Pull request merged**
