### PR TITLE
How to update your credit card

### PR DESCRIPTION
**Pull request by ultraschuppi**
## What is the purpose of the change

Educate customers on how to complete these steps and be able to send this in the reminder email for payments. 

## Are there related marketing activities

Nope, just user experience :)

## When should this change go live?

As soon as possible so we can remind customers of a missing email. 

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by ultraschuppi** [comment]
@christinaausley heyhey! i just helped @jprcoliveira doing his first steps for contributing to the docs - so technically not my PR ;)

backported the changes to 8.2 already. content+screenshots are handcrafted by @jprcoliveira and will be kept up to date by himself - but he is for sure happy to get a editorial review ;)

**Comment by christinaausley** [comment]
Wahoo @jprcoliveira! Nice work.

- Technical review in my latest commit, if you'd like to take a closer look at the changes I made. I must say, I had a good laugh at the description of "let's swipe another credit card to keep things spicy."
- I added this to the `8.2` versioned sidebar as well. You do want this in the current version of docs and not just the future version, yes?

Let me know if you have any questions 🚀

**Review by christinaausley — APPROVED** [review]

**Comment by jprcoliveira** [comment]
@christinaausley all credit on that description goes to @ultraschuppi (and my lack of coffee today)

And yes, current and future versions of the docs.

**Comment by jprcoliveira** [comment]
@christinaausley merged to main. Anything else needed on my end to go live?

**Comment by akeller** [comment]
@jprcoliveira nope, we'll handle the release.

@christinaausley do you want to do a release today or tomorrow?

**Comment by jprcoliveira** [comment]
Today (Thursday) would be great as we need to send some follow-up emails on this and wanted to add this link :)

**Comment by christinaausley** [comment]
Release going out shortly 🚀

**Pull request merged**
