### PR TITLE
docs: mention docker tag change in upgrade

### PR DESCRIPTION
**Pull request by OmranAbazid**
## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Review by buccarel — DISMISSED** [review]

**Review by christinaausley — APPROVED** [review]

**Comment by christinaausley** [comment]
Hi @OmranAbazid -- can you add a description or link the related issue for this PR? Would you like this to go out with the alpha next week?

**Comment by OmranAbazid** [comment]
Hi @christinaausley 
This is only needed for the next minor.
Here is thr parent issue:
https://github.com/camunda/camunda-optimize/issues/13498

**Comment by OmranAbazid** [comment]
@christinaausley Can you please approve this to be able to merge it.

**Comment by akeller** [comment]
@OmranAbazid, just a heads up: if we merge this, it will be available publicly as early as this week or with alpha5 changes. Is that OK?

**Comment by OmranAbazid** [comment]
> @OmranAbazid, just a heads up: if we merge this, it will be available publicly as early as this week or with alpha5 changes. Is that OK?

@akeller Yea, I think that is fine. I guess it will be available when a user click on the "next" version

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
