### PR TITLE
Adding Overview section and few small changes

### PR DESCRIPTION
**Pull request by theburi**
## Description

I have added an overview section to clarify what this page is about and amended the Authentication section.
This page should be more descriptive about what console API does.
Note: I resubmitted PR to fix an issue email and CLA

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ x ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ x ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ x ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ x ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — DISMISSED** [review]
This looks good to me, though you may want to wait to merge until you have an engineering review as well 👍

**Comment by akeller** [comment]
I updated this branch and backported to 8.3 now that the 8.3 release has been cut and released.

**Review by christinaausley — APPROVED** [review]
Good with this 👍

**Comment by christinaausley** [comment]
Any lingering thoughts @felix-mueller @ultraschuppi or can I go ahead and merge?

**Review by felix-mueller — APPROVED** [review]
lgtm

**Pull request merged**
