### PR TITLE
docs(optimize): instant dashboar copying and rename

### PR DESCRIPTION
**Pull request by misiekhardcore**
related to OPT-7316

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [x] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — DISMISSED** [review]
Thanks for adding in the redirects! This looks good to me. The only comment I have is why would I want to make a copy? Could be useful to note a particular use case.

**Comment by misiekhardcore** [comment]
> Thanks for adding in the redirects! This looks good to me. The only comment I have is why would I want to make a copy? Could be useful to note a particular use case.

Hey @christinaausley! Thanks for your feedback! Yeah, I tried to add redirects as I remembered I was adding them in the past when I renamed one other page.
Let me add some explanation of why this copying is useful and I'll ask you for a review once again

**Review by toco-cam — COMMENTED** [review]
Looks good

**Review by toco-cam — APPROVED** [review]

**Review by christinaausley — APPROVED** [review]
Awesome addition 👍

**Pull request merged**
