### PR TITLE
chore(announcements): simplify changes in supported envs

### PR DESCRIPTION
**Pull request by MaxTru**
* Change for consistency and readability

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by mesellings** [comment]
@MaxTru I'll take a look at this for you 👍

**Review by mesellings — COMMENTED** [review]
Hi @MaxTru, looks good, I made some edits as follows:
* Changed to Amazon OpenSearch rather than AWS (this is how we refer to it in the docs)
* Added a sentence under the heading - ideally, we should always have a sentence underneath headings.
* Front-loaded the content - i.e. put the important information at the front (e.g. changed "Raised minimum OpenJDK version..." to "OpenJDK minimum version raised" ) - helps when people scan pages for info relevant to them.
If you're happy with these changes, let me know and I'll approve the PR 👍

**Comment by MaxTru** [comment]
Great @mesellings ! The changes make a ton of sense and really improve this section. Thank you. Let's merge.

**Review by mesellings — APPROVED** [review]
@MaxTru Approved 👍

**Pull request merged**
