### PR TITLE
feat(self-managed/console): describe tls config

### PR DESCRIPTION
**Pull request by urbanisierung**
## Description

Describes how to configure SSL for Console Self-Managed.

- Console Ticket: https://github.com/camunda-cloud/camunda-cloud-management-apps/issues/3348
- PDP: https://github.com/camunda/product-hub/issues/2457

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).
- [x] I included my new page in the sidebar file(s).
- [ ] I added a redirect for a renamed or deleted page to the .htaccess file.

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by urbanisierung** [comment]
@christinaausley This is a last-minute feature we've implemented for console self-managed (for the 8.6 release). It will be tested hopefully next week, but it would be great if you could have a quick look into the description. Thanks!

**Comment by christinaausley** [comment]
@urbanisierung Happy to have a look -- also adding @conceptualshark for some SM-focused review.

**Review by conceptualshark — COMMENTED** [review]
Two commits added here:

1. I updated the URLs in the application-configs page. This should ensure they're all linking to the correct version of the docs.
2. I organized some of this content into tables to make the steps/requirements a little clearer, but feel free to revert if you'd like me to update the content more as-is.

**Comment by j-lindner** [comment]
Hi, I might miss(understand) something, so apologies if question seems unnecessary: 

Just to clarify: is it correct that Console application consists of both frontend and backend and that both, front- and backend  are served on the same host? And therefore only 1 certificate and 1 set of SSL options is required (other than web modeler, where frontend (webapp) and backend (restapi) run separately)?

If yes, then this looks good to me 👍 

(I didn't test it on a installation as of now though; could try to do that on friday if required, if there is a docker image available)

**Comment by urbanisierung** [comment]
> Just to clarify: is it correct that Console application consists of both frontend and backend and that both, front- and backend are served on the same host? And therefore only 1 certificate and 1 set of SSL options is required (other than web modeler, where frontend (webapp) and backend (restapi) run separately)?

@j-lindner exactly, that's how Console is working in SM. Frontend and Backend are served on the same host (basically the frontend app is served by the backend).

**Comment by urbanisierung** [comment]
> @urbanisierung I added 8.6 labels to this, but please move it out of draft when you are ready.

@akeller Unfortunately we found a dependency in the helm charts that need to be implemented, so the feature won't gonna make it into the 8.6 release :(

**Comment by christinaausley** [comment]
Hi @urbanisierung -- just checking in. Is this still slated for the 8.7 release as of now?

**Comment by urbanisierung** [comment]
> Hi @urbanisierung -- just checking in. Is this still slated for the 8.7 release as of now?

@christinaausley I hope so. One missing piece was implemented and we're waiting now for QA approval.

**Comment by urbanisierung** [comment]
@christinaausley We got green lights from QA. Can you please have a final look? Thanks!

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
