### PR TITLE
docs(operate): add jobKey to incident endpoint

### PR DESCRIPTION
**Pull request by johanwelgemoed**
## Description

Update operate API docs to reflect new field added to incidents endpoint.

Relates only to 8.3.x and /next versions.

relates to: https://github.com/camunda/operate/issues/5700

## When should this change go live?

- [x] This change is not yet live and should be merged as part of 8.3.2 patch release?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — APPROVED** [review]

**Comment by christinaausley** [comment]
@johanwelgemoed Want me to merge this in before releasing today?

**Comment by johanwelgemoed** [comment]
@christinaausley please hold off on this until we merge the actual fix. I will put hold label on this PR until ready (in case someone else wants to merge it :) )

**Comment by akeller** [comment]
@johanwelgemoed do we need to do a docs release to get this change live as well?

**Comment by akeller** [comment]
> @johanwelgemoed do we need to do a docs release to get this change live as well?

Following up on Slack - https://camunda.slack.com/archives/C9B5270DA/p1698771808472949

**Comment by akeller** [comment]
@christinaausley, if we need to do a docs release between now and 8.3.2 going live, we'll need to revert these changes. See [this message on Slack](https://camunda.slack.com/archives/C9B5270DA/p1698771911723689).

**Pull request merged**
