### PR TITLE
feat(zeebe-api): link Zeebe API docs where endpoints are mentioned

### LINKED ISSUE #3586: Link to Zeebe Task API docs from task life cycle docs
Link to Zeebe Task API docs from task life cycle docs

### PR DESCRIPTION
**Pull request by christian-konrad**
## Description

Closes #3586 

## When should this change go live?

- [x] This change or page is part of 8.5.

## PR Checklist

- [x] Changes are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`).
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by christian-konrad** [comment]
@christinaausley another small change to have a complete story in the docs about the new API, closing gaps between documented endpoints and their references

**Comment by christian-konrad** [comment]
@pepopowitz do you mind to check if the links to the API explorers are valid (on main, the sidebars are not yet merged)?

**Comment by pepopowitz** [comment]
> @pepopowitz do you mind to check if the links to the API explorers are valid (on main, the sidebars are not yet merged)?

I will look today!

**Review by pepopowitz — DISMISSED** [review]
Thanks for catching all these!

The links all look correct to me. I opened #3598 to fix an issue where the Zeebe REST API docs were accidentally removed from the sidebars -- that was causing the issue where the sidebars don't appear on the Zeebe REST docs that this PR links to. I confirmed locally that when that fix is applied to this PR, sidebars appear on all the linked docs.

This PR also alerted me to the fact that when #3569 lands, it would create broken links in these docs. I'm going to fix them in that PR, so that we don't have to do a follow-up anywhere. (**Edit**: No, [I had already accounted for them](https://github.com/camunda/camunda-docs/pull/3569/files#diff-f93e47aaa468163d0085ace4422a645c528dd6a3bd9a83934f2fcb697bec4607) 🙃 I _knew_ these changes looked familiar....)

**Review by christinaausley — DISMISSED** [review]

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
