### PR TITLE
Update versioning-process-definitions.md

### PR DESCRIPTION
**Pull request by berndruecker**
Removed outdating text referring to Camunda database (see https://github.com/camunda/camunda-docs/issues/2403)

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
This needs to be backported.

**Comment by christinaausley** [comment]
Hi @berndruecker! Let me know if you would like assistance with backporting 👍

**Review by christinaausley — APPROVED** [review]

**Comment by christinaausley** [comment]
@berndruecker I backported for you, all we require is signing the CLA to merge 👍 Thank you!

**Comment by berndruecker** [comment]
Done (even if I am quite sure I already did that in the past already - whatever)

**Comment by christinaausley** [comment]
> Done (even if I am quite sure I already did that in the past already - whatever)

It has re-required everyone to sign -- IT is looking into it 😄

**Pull request merged**
