### PR TITLE
docs(guides): use registry and repository parameter

### PR DESCRIPTION
**Pull request by ManuelDittmar**
## Description
Bitnami Charts do have docker.io hardcoded as registry, therefore the current guide does not work if you want to update the registry. Also camunda components are now making correct use of registry vs. repository.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Review by aabouzaid — CHANGES_REQUESTED** [review]
I'd suggest using `global.image.registry` given we can use it for all of our components instead of setting that for each component individually.

**Comment by christinaausley** [comment]
@ManuelDittmar Are you just waiting on additional review here?

**Comment by ManuelDittmar** [comment]
@christinaausley yes

**Comment by christinaausley** [comment]
> @christinaausley yes

CC @aabouzaid 😄

**Pull request merged**
