### PR TITLE
Update alerts.md

### PR DESCRIPTION
**Pull request by nareshgoswami1508**
As per our communication in our supprt request this is not supported feature in 8.3.x. And hence the documentation is wrong. It can help others to not waste their time on trying to set up alerts. https://jira.camunda.com/projects/SUPPORT/queues/custom/16/SUPPORT-19639

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
Thank you for your PR @nareshgoswami1508. We'll need to cleanup this PR and backport the changes, but someone on the Camunda side can take care of that. Can you please the CLA? Otherwise we will need to close this PR and open it without being able to attribute the fix to you.

@RomanJRW can you confirm this and help me understand how we can address it in the docs? I think it may need to be floated to the top of the page if it's all alerting, but based on the ticket, I was struggling to follow if it's all alerting or just webhook alerting. I also want to make sure we capture the difference between C7 and C8 functionality.

**Comment by nareshgoswami1508** [comment]
> Thank you for your PR @nareshgoswami1508. We'll need to cleanup this PR and backport the changes, but someone on the Camunda side can take care of that. Can you please the CLA? Otherwise we will need to close this PR and open it without being able to attribute the fix to you.
> 
> @RomanJRW can you confirm this and help me understand how we can address it in the docs? I think it may need to be floated to the top of the page if it's all alerting, but based on the ticket, I was struggling to follow if it's all alerting or just webhook alerting. I also want to make sure we capture the difference between C7 and C8 functionality.

I have  Signed the CLA now. 
Regarding the Alerts feature in optimize, currently we cannot even see the "Alerts" tab in C8-SM optimize. So it is completely not available.

**Comment by akeller** [comment]
I've confirmed the following with @RomanJRW via internal Slack:

Email is available everywhere except C8SM 8.3 and earlier. We should add an admonition about this for C8SM that it is not available in 8.1, 8.2, or 8.3.

We can clarify with an admonition, one-liner, or a label that webhook is only available for C7.

Since I don't have write access to your fork @nareshgoswami1508 I will open a new PR with the changes. Thank you for pointing this out.

**Review by toco-cam — COMMENTED** [review]
Looks good

**Pull request closed without merging**
