### PR TITLE
feat: execute tag manager script right before loading osano.js

### PR DESCRIPTION
**Pull request by pepopowitz**
## Description

Requested by @antantunes (I think, assuming I guessed correctly from the username), [in Slack](https://camunda.slack.com/archives/C026U8GBNSW/p1708440411893479).

Adds a script that does some Google Tag Manager things prior to loading the Osano.js script. 

TBH I don't really know what it is doing and how that's fixing the problem (or even what the problem is to require this change), but I hope that doesn't matter. I recognize it as referencing Google Tag Manager, so it doesn't seem unsafe to me, but 🤷 

[Below is updated:]

Below is a screenshot of the source for a page when running locally, to prove that scripts run in the following sequence in the `head` element: 

1. Google Consent Mode Default Script
2. Osano dependency
3. Google Tag Manager initialization

image

## Implementation notes

To control the order of scripts, including the GTM initialization, I moved things into a custom plugin, which registers two blocks of script for the head prior to the GTM initialization. (Similar to the bpmn-js implementation, which I mentioned previously as another option 😅 FORESHADOWING )

### Old implementation notes
I had to redo how we're loading the script from Osano, because I couldn't get Docusaurus to cooperate with complex scripts embedded directly in a React component (i.e. the `Footer` component, where we were previously loading that script.) I also considered stashing the new code in a script file, and loading that directly before the Osano.js script, but that wouldn't guarantee that the code in the new script file would run prior to loading the Osano.js script. I actually like that the final implementation moved a script load out of a component -- that seems like the kind of thing to use Docusaurus's architecture for.

~This is where I ended up -- adding a couple items to the `headTags` property of the docusaurus configuration. If we wanted to, we could wrap this into a plugin instead of littering it all on the main configuration -- similar to how [the bpmn-js plugin](https://github.com/camunda/camunda-docs/blob/fbfc9fae5828cccdee0a94c4b3c695bdafce4364/static/plugins/bpmn-js/index.js) is configured.

## Testing

Ummmmmm I don't really know how to test that this works? I don't know if the appropriate things run in environments other than production; I also don't know _what_ I'm testing for. Maybe @antantunes can help us out with that?

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
I don't know how to test this, but I ran it locally in an incognito browser and saw the website working as expected. We'll need help from web marketing to understand if this works, or if we need to test it in stage or production 🤷‍♀️

**Comment by antantunes** [comment]
Hey @pepopowitz not really sure how to use github... but the screenshot you have sent is what I requested. From my side you can publish it to production. Thank you !

**Comment by pepopowitz** [comment]
@akeller @antantunes could one of you add an approval to the PR so that I can merge it?

**Review by antantunes — COMMENTED** [review]
@pepopowitz I review this again and the screenshot as well and I see that you have changed order of the scripts. Now I see the GTM script is before the Osano one. The right order should be 1. Google Consent Mode Default Script, 2. Osano Script 3. Google Tag Manager Script

image

**Comment by antantunes** [comment]
Yes it is!

**Comment by pepopowitz** [comment]
> @pepopowitz I review this again and the screenshot as well and I see that you have changed order of the scripts. Now I see the GTM script is before the Osano one. The right order should be 1. Google Consent Mode Default Script, 2. Osano Script 3. Google Tag Manager Script
> 
> image

I'm updating the body to include an updated screenshot, so preserving this for history -- this is the screenshot mentioned previously as mis-ordering the scripts. 

image

**Comment by pepopowitz** [comment]
@antantunes can you take a look at the updated image in the body of this PR in your re-review?

**Review by antantunes — APPROVED** [review]
Hi @pepopowitz, the last screenshot provided looks correct!

**Pull request merged**
