### PR TITLE
Add "Manage Connector Templates" docs

### PR DESCRIPTION
**Pull request by YanaSegal**
As part of https://github.com/camunda/product-hub/issues/1340 I am suggesting the following updates and changes for this page.

- Add docs describing Shared Resources tab in SaaS web-modeler
- Clarify existing docs about Connector templates shared with an organization

Closes https://github.com/camunda/team-connectors/issues/660

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.
- [x] This functionality will be available within the next week (in next web-modeler SaaS release), but we'd like documentation available at launch

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by christinaausley** [comment]
@YanaSegal Will this go out with release next week?

**Comment by akeller** [comment]
@YanaSegal this looks like feedback @ev-codes would implement in this PR. Or are you asking for assistance from DevEx?

If I'm following your comments correctly, we can add a SaaS-only badge. However, everything outside of the Self-Managed section is SaaS-first.

**Comment by YanaSegal** [comment]
> Or are you asking for assistance from DevEx?
@akeller I am asking for your support as the links in the section I mentioned do not directly mention connectors or the editor. i think users that working on SaaS only, will be confused with seeing desktop modeler docs.
This is not blocking us, but makes sense to review it. 

The "shared resources" feature is currently for SaaS only, but this may change in the future.

**Comment by ev-codes** [comment]
@christinaausley may you please take a look at the docs in this PR?

This feature (and these docs) still need to go through the Connectors QA process before I merge, but I'd appreciate you taking a look before the QA process starts.

After your review (and I implement your suggestions), I will:
1. Start (and eventually complete) the QA process for this feature
2. Merge the feature into Web Modeler
3. Mark this PR as "ready for review"

**Comment by christinaausley** [comment]
@ev-codes @YanaSegal This is wonderfully written! Some very small changes in my latest commits, but has my approval.

**Comment by christinaausley** [comment]
> @christinaausley Sure, I'll add the hold label now!
> 
> I had added one before, but removed it because it caused the "Enforce PR labels" check to fail.

Yeah, this is intentional so things don't get accidentally merged. We can remove and it will build clean once we are ready to merge this in 👍

**Comment by ev-codes** [comment]
@christinaausley this PR is fully ready now - may you please approve?

The code has been merged into `web-modeler` and should be released to SaaS customers sometime next week.

Since a link to this doc is prominently featured in the UI, I'd love to have these docs already available before the SaaS release if possible 😄

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
