### PR TITLE
add note on cawemo end of life

### PR DESCRIPTION
**Pull request by christinaausley**
## Description

Related to https://github.com/camunda/camunda-docs-static/pull/429.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

@marcellobarile When can this actually be merged in and live? Placing a `hold` label for now.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by marcellobarile — DISMISSED** [review]

**Review by crobbins215 — COMMENTED** [review]
Checked and looking good, thanks for doing this

**Review by crobbins215 — COMMENTED** [review]
I suggest we also add @christinaausley 

**Transition Options:**
Move to our Web Modeler: Experience the combined power of Cawemo and our Desktop Modeler in a seamless, collaborative environment. For modeling only or Camunda 8 processes.


Move to our Desktop Modeler: Opt for a standalone BPMN modeling experience. Support both Camunda 7 and Camunda 8 processes. 

Move to Cawemo On-Premise: Continue with the familiar Cawemo environment, For modeling only or Camunda 7 processes. Please note that support for Cawemo On-Premise aligns with [Camunda 7 timelines.](https://docs.camunda.org/enterprise/announcement/)

**Comment by christinaausley** [comment]
> @christinaausley thanks for the prompt change! The Cawemo EOL banner will be released on Monday at ~2 PM. Shall I remove the `hold` label right before the prod deployment? Would it be enough?

@marcellobarile I'll go ahead and merge this in upon final approval today, and we can get a release out on Monday when you are ready for this to go live.

**Review by crobbins215 — COMMENTED** [review]
Thankyou, also including links

**Review by marcellobarile — APPROVED** [review]

**Review by crobbins215 — APPROVED** [review]
Yep, this includes the links and matches the customer communication.

**Comment by marcellobarile** [comment]
FYI @christinaausley we are good to go and we will go live today @ 2 PM with the EOL message on Cawemo + C7 documentation announcement

**Comment by christinaausley** [comment]
@marcellobarile I’ll get a release out within the hour then — thanks!

**Pull request merged**
