### PR TITLE
Document tenant-aware broadcast signal RPC

### LINKED ISSUE #2820: Document multi-tenancy support for signals
### Description

Multi-tenancy support for Signal broadcasting is documented for `8.4.0`.

```[tasklist]
### Tasks
- [x] The Zeebe gRPC documentation covers a tenant-aware `BroadcastSignal` RPC.
```

### PR DESCRIPTION
**Pull request by koevskinikola**
## Description

Document the new tenantId properties for the Zeebe BroadcastSignal RPC.

:information_source: The changes will be live after https://github.com/camunda/zeebe/pull/14842 is merged.

closes #2820 

## When should this change go live?

- [x] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — DISMISSED** [review]

**Comment by koevskinikola** [comment]
@christinaausley I added an additional commit ([82b9ff1](https://github.com/camunda/camunda-docs/pull/2822/commits/82b9ff1a40a0f3c10239f3ad05099d2105a19e58)) which removes a possible deployment error since we now support tenant-aware Signal broadcasting.

**Comment by christinaausley** [comment]
> The changes will be live after https://github.com/camunda/zeebe/pull/14842 is merged.

In this case, we should likely add these changes to `8.3` docs, yes? We can keep the hold label on this one until the Zeebe PR is merged in.

**Review by remcowesterhoud — APPROVED** [review]
LGTM!

**Comment by remcowesterhoud** [comment]
> In this case, we should likely add these changes to 8.3 docs, yes? We can keep the hold label on this one until the Zeebe PR is merged in.

No, we shouldn't put it in 8.3. It is an error message that indicates that Signals are not supported yet. This error can occur on 8.3. However, with 8.4 we will support Signals, so we should remove this error for 8.4.

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
