### PR TITLE
feat(8.5): spring sdk oauth scope config

### PR DESCRIPTION
**Pull request by megglos**
## Description

Adds `ZEEBE_TOKEN_SCOPE` env var to sdk config, to make transparent how the client scope can be set with 8.5

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [x] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Review by nicpuppa — DISMISSED** [review]
Not sure if this need to be available in 8.6 and 8.6

**Comment by akeller** [comment]
The file modified in this PR is for `/next` or the preview for 8.7.

**Comment by megglos** [comment]
in the meantime 8.6 was covered with https://github.com/camunda/camunda-docs/pull/4473, only 8.5 is open to be included once the next 8.5 patch is released.

**Comment by akeller** [comment]
@megglos @nicpuppa, I'm admittedly a bit confused about the status of this PR. Do we need to merge this change for 8.7 (current scope of the PR)? Or _just_ 8.5? If it's just for 8.5, we need to adjust this PR.

**Comment by nicpuppa** [comment]
@christinaausley I think this property needs to be added in the 8.5 docs, but I'm honestly not sure about it

**Review by akeller — APPROVED** [review]

**Pull request merged**
