### PR TITLE
Remove Arcade from HTO guide

### PR DESCRIPTION
**Pull request by akeller**
## Description

Arcade experiences are becoming stale, the quick win is to remove them.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Review by conceptualshark — APPROVED** [review]
Looks like all the Arcade instances to me! 👍

**Comment by conceptualshark** [comment]
Do we have a plan (or desire) to recreate these at all, or are they staying removed for the foreseeable future?

**Comment by akeller** [comment]
> Do we have a plan (or desire) to recreate these at all, or are they staying removed for the foreseeable future?

I have no plans and, unfortunately, am unsure about my personal desires here. I was hoping someone had the credentials so we could look into metrics. It's an interesting mechanism, but sustainable maintenance is top of mind for me. If this is something that interests you, bring it to a team meeting, and let's discuss 🙂

**Review by marcosgvieira — APPROVED** [review]
Thanks @akeller. I'm trying to check if we can find the credentials used there and we can take a decision on this later.

**Comment by akeller** [comment]
Since we don't have access to Arcade's credentials, we cannot further evaluate this as an offering we want to maintain/expand. However, we could consider doing something similar in the future with a well-scoped issue, epic, or experiment.

**Pull request merged**
