### PR TITLE
docs(task application): Remove strange backslash

### PR DESCRIPTION
**Pull request by tobiasschaefer**
## Description

Remove "\" in text. I don't know how it got there but it looks strange.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
@christinaausley can you backport in another PR since this is a community contribution?

**Review by christinaausley — APPROVED** [review]

**Comment by christinaausley** [comment]
@akeller It looks like this is the only instance of this in the docs 👍

**Comment by akeller** [comment]
@pepopowitz this is an external contribution that I will merge. Check version fails. Is this expected in this scenario? Or is this an edge case?

**Comment by pepopowitz** [comment]
@akeller it's not expected! I opened https://github.com/camunda/camunda-docs/issues/3358 to address it.

**Pull request merged**
