### PR TITLE
adjust remaining whitelist references

### PR DESCRIPTION
**Pull request by christinaausley**
## Description

Closes https://github.com/camunda/developer-experience/issues/254.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by akeller — COMMENTED** [review]
I'm not sure what the best practice is for handling this from an SEO point of view. Should non-inclusive words for configuration (like access lists) be added to the page meta data?

**Comment by akeller** [comment]
May have overlap with #3405

**Comment by christinaausley** [comment]
Expanding this to close https://github.com/camunda/developer-experience/issues/271.

**Comment by christinaausley** [comment]
> I'm not sure what the best practice is for handling this from an SEO point of view. Should non-inclusive words for configuration (like access lists) be added to the page meta data?

I think it's fine to keep this across meta data, as this is a way for users who may have not considered this rename to still find the related content.

**Review by akeller — DISMISSED** [review]
Approving! If you want to add metadata to manage-ip-allowlists, you can do this in this PR or a future one. Doesn't matter to me.

**Review by akeller — APPROVED** [review]

**Pull request merged**
