### PR TITLE
An update of a link

### PR DESCRIPTION
**Pull request by AnatolyKostrikov**
## Description
1. The list renumbered. 
2. The link updated. 
3. Tags 'Camunda 7, 8 only' updated.
4. Added 'correlationIdMyMessage' example code.
5. The link to .md updated.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [x] This functionality is already available but undocumented.
- [x] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by AnatolyKostrikov** [comment]
BTW, there is one more mistake in [routing-events-to-processes.md](https://docs.camunda.io/docs/components/best-practices/development/routing-events-to-processes/), 

> As a best practice, correlate incoming messages based on one unique artificial attribute (e.g. **correlationIdMyMessage**) created specifically for this communication. Alternatively, you also have the option to select the process instance targeted by a message based on a query involving complex criteria, and then as a second step explicitly correlate the message to the selected process instance.

but the ambiguity in terms:

- Global message reference (aka Message name),
- Business Key

makes it difficult to guess about the correct option for **correlationIdMyMessage**.

**Comment by christinaausley** [comment]
Thank you @AnatolyKostrikov! Looping in @berndruecker regarding your comment in best practices.

**Comment by berndruecker** [comment]
@AnatolyKostrikov: You mean that you would find it easier to follow if the example would also use the `correlationIdMyMessage.` like this:

```
runtimeService
  .createMessageCorrelation("myMessage") // <1>
  .processInstanceVariableEquals("correlationIdMyMessage", myMessage.getCustomCorrelationId()) // <3>
  .correlate();
```

?

That would make sense to me. Are you up to doing another PR maybe 😉

**Comment by AnatolyKostrikov** [comment]
Thank you, Bernd @berndruecker . An unique artificial attribute in my case is UUID that I can generate ahead if Worker will create an object in а sequence diagram later that will be referenced by an Intermediate Catch or Boundary event.

I have added your example into the page.

Christina @christinaausley , I have also updated the names of the sections and am submitting the documents for your review.

**Review by christinaausley — DISMISSED** [review]

**Comment by christinaausley** [comment]
Hi @AnatolyKostrikov -- to merge this into the docs, you will need to sign our CLA.

**Comment by christinaausley** [comment]
Hi @AnatolyKostrikov -- would you mind running `npm run format` in your branch and pushing those changes? It formats our docs alongside Prettier and should solve the build issue here.

**Comment by AnatolyKostrikov** [comment]
@christinaausley , done. 

1. Initial problem was in new paragraph (not mine):

```
:::note
This is the most common case and requires using the [`CreateProcessInstance`](../../../apis-tools/grpc.md#createprocessinstance-rpc) API.
:::
```

Fixed by `npm run format`.

2. The last problem occurred with the file camunda-docs/docs/apis-tools/tasklist-api/tasklist-api-tutorial.md and its versions.

```
Raw Output:
docs/apis-tools/tasklist-api/tasklist-api-tutorial.md:253:-    axiosRef.defaults.headers["Authorization"] =
docs/apis-tools/tasklist-api/tasklist-api-tutorial.md:254:-      `***;
docs/apis-tools/tasklist-api/tasklist-api-tutorial.md:253:+    axiosRef.defaults.headers[
docs/apis-tools/tasklist-api/tasklist-api-tutorial.md:254:+      "Authorization"
docs/apis-tools/tasklist-api/tasklist-api-tutorial.md:255:+    ] = `***;
Error: [prettier] reported by reviewdog 🐶
```

 I didn't edit this file so just rollbacked it from the main branch.

**Comment by christinaausley** [comment]
Thank you for these efforts @AnatolyKostrikov! 🥳

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
