### PR TITLE
fix(self-managed): include deprecation notice for separated ingress

### PR DESCRIPTION
**Pull request by jessesimpson36**
## Description

As part of 
https://github.com/camunda/distribution/issues/290
https://github.com/camunda/camunda-platform-helm/issues/1838

There are some things we want to remove from the helm chart in v8.7 that we want to announce for 8.6. 

1. separated ingresses
2. There were also some things that we planned on dropping support for in v8.6, however, we have decided to keep compatibility with those options until v8.7.

Those items were listed here:  https://docs.camunda.io/docs/self-managed/setup/upgrade/#deprecation-notes

This PR adds an announcement, helm upgrade note, and will put a notice on top of the Combined and Separated Ingress Guide that Separated ingresses will no longer be supported.

## When should this change go live?

Our internal tickets on this topic are scheduled for 8.6-alpha5

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by conceptualshark** [comment]
@jessesimpson36 Let me know if these edits keep your changes intact 👍 I moved them as a deprecation notice to 8.6, with removal slated to 8.7. If the `global.image.tag` notice gets changed, we can remove it from the update guide, and add it as officially removed in the announcements as well.

**Comment by jessesimpson36** [comment]
wow that is so much better!

**Comment by jessesimpson36** [comment]
From Distribution team I will assign @drodriguez-305 to review

**Comment by jessesimpson36** [comment]
Also this change does not need to be backported to 8.5, as this is a notice for 8.6+.

**Review by drodriguez-305 — APPROVED** [review]
LGTM!

**Review by conceptualshark — APPROVED** [review]

**Pull request merged**
