### PR TITLE
doc: Update build-your-own-client.md

### PR DESCRIPTION
**Pull request by houssain-barouni**
Make audience in the example taken from env variable ${ZEEBE_TOKEN_AUDIENCE}

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
Hi @houssain-barouni thank you for your PR! Can you also add your changes to the current version of the docs? 

`versioned_docs` > `version-8.3`

**Comment by houssain-barouni** [comment]
> Hi @houssain-barouni thank you for your PR! Can you also add your changes to the current version of the docs?
> 
> `versioned_docs` > `version-8.3`

Hi @akeller , there is no urgency with these changes, it is a little improvement that can be part of next release docs

**Comment by christinaausley** [comment]
@houssain-barouni I went ahead and backported, but I noticed we have two other references of docs.camunda.io on lines 26 and 83 -- should these be adjusted as well?

**Comment by houssain-barouni** [comment]
> @houssain-barouni I went ahead and backported, but I noticed we have two other references of docs.camunda.io on lines 26 and 83 -- should these be adjusted as well?

thanks @christinaausley 
line 26 is an example so it can be kept as is
line 83 should not be changed

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
