### PR TITLE
docs(rest): Add REST Connector proxy documentation

### PR DESCRIPTION
**Pull request by johnBgood**
## Description

Related to [#3252](https://github.com/camunda/connectors/issues/3252)

To be merged around the November release.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for **8.6** and are in `/versioned_docs` directory.
- [x] My changes are for **8.7.0-alpha1** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by mesellings** [comment]
@johnBgood Does this need to be backported for other versions, or is it ok just for 8.6, next?

**Review by mesellings — APPROVED** [review]
@johnBgood Lgtm - I've committed changes directly to the branch for you 👍

**Comment by johnBgood** [comment]
> @johnBgood Does this need to be backported for other versions, or is it ok just for 8.6, next?

@mesellings It's only 8.6+ :) 
Thanks for your review!

**Comment by johnBgood** [comment]
@mesellings I'll be released next week, so I don't know when we can merge it. I'll let you decide on it :)

**Comment by mesellings** [comment]
@johnBgood Do you mean the dev feature this relies on to work is only released next week or would this work currently (now) before the release?

**Comment by johnBgood** [comment]
@mesellings 
this: 

> Do you mean the dev feature this relies on to work is only released next week

**Comment by mesellings** [comment]
Thanks @johnBgood I'll hold off and release this on Friday then to avoid people trying to use the proxy feature as a result of the docs 👍

**Pull request merged**
