### PR TITLE
resolve web modeler api sidebar

### PR DESCRIPTION
**Pull request by christinaausley**
## Description

Correcting sidebar, which decided to freak out after authentication/authorization changes.

Screenshot 2023-12-15 at 2 19 22 PM

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [x] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by akeller — DISMISSED** [review]

**Comment by christinaausley** [comment]
If this fix doesn't work I'm gonna go cry to @pepopowitz so we can cry together 🥳

**Review by akeller — APPROVED** [review]
I tested this locally and it looked fine, but admittedly I didn't click into Optimize docs.

**Comment by pepopowitz** [comment]
@christinaausley from the build error messages: 

```
- On source page path = /docs/8.2/apis-tools/working-with-apis-tools/:
   -> linking to /docs/next/apis-tools/web-modeler-api/

- On source page path = /docs/apis-tools/working-with-apis-tools/:
   -> linking to /docs/next/apis-tools/web-modeler-api/
```

My initial instinct is that there are pages in both the 8.2 and 8.3 versions of the working-with-api-tools page that are linking to something you changed here. I'll look closer!

**Comment by pepopowitz** [comment]
That looks like it's the case -- [here's the link from the 8.3 docs](https://github.com/camunda/camunda-docs/blob/b78a461d1ac19e40b5da8c8b753be410265726f4/docs/apis-tools/working-with-apis-tools.md?plain=1#L72) that is causing a build error:

```javascript
{
type:"link", href:"/docs/next/apis-tools/web-modeler-api/overview/", label: "Web Modeler API (REST)", docId:"apis-tools/web-modeler-api/overview"
},
```

These cards have a hardcoded href in them, and a docId, because the DocCard component isn't smart enough to look up the href based on a docId. Long-term, that would be a good fix on my end -- I think I should be able to get that href somehow, given a docId, and then we don't have to include href's for anything but the Optimize card.

To get this PR green, I recommend removing the `/next` from the href there, and in the corresponding 8.2 doc.

**Comment by christinaausley** [comment]
@pepopowitz Thank you!

**Review by akeller — APPROVED** [review]

**Comment by akeller** [comment]
@christinaausley @pepopowitz we should merge this and do a docs release. The Web Modeler API docs are currently in a broken state.

**Comment by pepopowitz** [comment]
The "long-term" fix I mentioned, which would prevent us from hardcoding version-specific URLs in these DocCardLists, is tracked at #3078.

**Comment by pepopowitz** [comment]
> we should merge this and do a docs release. The Web Modeler API docs are currently in a broken state.

@akeller I didn't think about this much at the time, but in hindsight I think we were off-base with the urgency of this one. It only affected vNext, which we've said we want people to treat as a playground, and it didn't prevent anyone from getting to the docs that they needed. This needed a fix, but I don't think it required an urgent Friday-afternoon deployment.

**Pull request merged**
