### PR TITLE
Add comprehensive table to release notes page

### PR DESCRIPTION
**Pull request by akeller**
## Description

* Adds table to release notes page (index page)
* Lists all supported versions, including scheduled end of maintenance dates 

👇 Oops, typo'd the date. But it's fixed in the PR itself.
image

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer.

### CODE REVIEW

**Comment by akeller** [comment]
@ev-codes, this PR wouldn't change the info in the drop down, but would it help address https://github.com/camunda/camunda-docs/issues/3749? 

I could add more context to why we still support 1.3 to this page as well.

**Comment by akeller** [comment]
@MaxTru for 8.2-8.4 I linked to the changelog in camunda-platform, thus I call the link "Camunda Platform." Should I call this "Camunda 8 Core" as well, or would this be misleading because not all core components would be available in the camunda-platform repo? 

I kept the "scheduled" terminology in the table, but WDYT? Should I add "Scheduled release notes" to the column header?

**Comment by ev-codes** [comment]
@akeller yes, this would help address https://github.com/camunda/camunda-docs/issues/3749 !

Thank you for considering and addressing the feedback.

> I could add more context to why we still support 1.3 to this page as well.

I think providing more context about 1.3 support is a good idea!

**Comment by MaxTru** [comment]
>@MaxTru for 8.2-8.4 I linked to the changelog in camunda-platform, thus I call the link "Camunda Platform." Should I call this "Camunda 8 Core" as well, or would this be misleading because not all core components would be available in the camunda-platform repo?

Hi @akeller ,
I think your suggestion makes sense since it is just the reality that we used camunda platform for these releases, which is different to the integrated repo we have now.
Thanks

**Comment by akeller** [comment]
@camunda/tech-writers, during review, please note that not all supported versions were in scope for this so we won't backport beyond the current version at this time. 

Also, I added a brief disclaimer for CC 1.3/Optimize 3.7, which I was going to link to https://github.com/camunda/issues/issues/182, but I need to check internally if this is the most up-to-date issue on this topic. Given that this is only part of the PR (and not the focus) I would like to move forward and follow up with another PR if this one is ready to merge.

**Review by conceptualshark — APPROVED** [review]

**Pull request merged**
