### PR TITLE
docs(web-modeler): publish connector templates to org available to admin

### PR DESCRIPTION
**Pull request by JacobiCamunda**
## When should this change go live?

- [x] This change is not yet live and should not be merged until https://github.com/camunda/web-modeler/issues/7675 is deployed to prod (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by JacobiCamunda** [comment]
@jfriedenstab, I added you as a reviewer too because you are reviewing the backend part of the epic. Not a big change in the docs but want to be sure.

@christinaausley, this is a `saas-only` feature, but I changed the versioned docs too. Is this the correct procedure?

**Comment by christinaausley** [comment]
@JacobiCamunda Thank you for backporting! For Connectors docs, yes, we backport in full.

Is this still in `draft` because you are planning to make additional changes?

**Review by jfriedenstab — APPROVED** [review]
Looks good from my end.

**Comment by JacobiCamunda** [comment]
> @JacobiCamunda Thank you for backporting! For Connectors docs, yes, we backport in full.

Thanks. Good to know!
> Is this still in `draft` because you are planning to make additional changes?

I don't plan to change anything anymore.

**Comment by christinaausley** [comment]
@JacobiCamunda You can remove the `hold` label and merge when ready 👍

**Review by christinaausley — APPROVED** [review]

**Comment by JacobiCamunda** [comment]
The last implementation step was merged yesterday and was deployed to prod today. The documentation update can now be merged.

**Comment by christinaausley** [comment]
@JacobiCamunda Are you wanting to see a docs release today in reflection of this?

**Comment by JacobiCamunda** [comment]
> @JacobiCamunda Are you wanting to see a docs release today in reflection of this?

This is not a priority. If you plan to release it in the next few days, it is enough 🙂

**Pull request merged**
