### PR TITLE
chore(play): clarify hybrid mode support

### PR DESCRIPTION
**Pull request by HanselIdes**
## Description

Raised internally (https://camunda.slack.com/archives/C049ZK6J430/p1699360890326709)

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [x] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by HanselIdes** [comment]
@christinaausley PR ready for review and backported as appropriate

**Review by christinaausley — COMMENTED** [review]
Looks good, but one comment:

We do not have `publish-public-processes.md` in `8.2` -- I've routed this link to the latest version of docs, but is this note relevant to `8.2`?

**Comment by HanselIdes** [comment]
> We do not have `publish-public-processes.md` in `8.2` -- I've routed this link to the latest version of docs, but is this note relevant to `8.2`?

Where is publish-public-processes.md?

If it's the start forms, then it's kinda tricky. 
* This is in the Modeler, which runs on `latest` regardless of the cluster version.
* Users can still model start forms, and users will still get a warning during modeling.
* Play automatically sets the linting rules to Zeebe 8.2 when switching into the tab
I'd rather give you context to help you decide for me because I don't know the right answer. What do you think we should do?

**Comment by christinaausley** [comment]
Circling back here @HanselIdes and then I can get this merged 👍

**Comment by HanselIdes** [comment]
@christinaausley I've removed the reference to start forms in the 8.2 documentation. Is that good enough to merge now?

**Comment by christinaausley** [comment]
@HanselIdes Yep! I'll get the build working and merge this in 👍

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
