### PR TITLE
feat: detect crossover links as a PR check

### PR DESCRIPTION
**Pull request by pepopowitz**
## Description

Addresses #1876.

See #2664 for more details and context about how this PR came about. 

This PR introduces [vale](https://vale.sh/) as a markdown linter. It introduces 4 linting rules that detect links that cross over instances or versions of the docs, and runs them as a pull request check.

- The 4 rules are run against only the changes included in the PR.
- If a rule is violated in a PR, a comment is added at the point of violation, as an FYI.
- If a rule is violated in a PR, the check **does not** fail.

An example of a violation can be found [in this prototype PR](https://github.com/camunda/camunda-docs/pull/2664#discussion_r1340415150). It looks like this: 

image

## The crossover validation rules

The rules in this PR are inspired by [our guidance on preferred link format](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#internal-links). There are five of them: 

1. Within the main docs instance, any link that starts with `docs/` but doesn't end with `.md` or `.mdx` triggers a warning (navigating by source file path is preferred).
2. Within the main docs instance, any link that starts with `/optimize/` triggers a warning (using `$optimize$` is preferred).
3. Within the optimize docs instance, any link that starts with `optimize/` but doesn't end with `.md` or `.mdx` triggers a warning (navigating by source file path is preferred).
4. Within the optimize docs instance, any link that starts with `/docs/` triggers a warning (using `$docs$` is preferred).
5. Any link that starts with "https://docs.camunda.io/docs" or "https://docs.camunda.io/optimize" triggers a warning (prefer relative URLs).

This doesn't cover _all_ possible links that could cause cross-version linking, but it covers the large majority of issues we currently have.

## Running the validation locally

This PR **does not** include a command within the package.json to run vale locally. This is because vale is not distributed via npm. It can be installed on a computer via other means (e.g. homebrew) and run in this project directory to validate locally, like this: 

```
vale .
```

Though keep in mind, that runs against _all files_ and currently returns 436 warnings. It requires care and effort to isolate the exact problem when running locally.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by akeller — APPROVED** [review]
My only hesitation is the timing being right before the minor release. That said, we can always back it out if it's too noisy. 

> Though keep in mind, that runs against all files and currently returns 436 warnings. It requires care and effort to isolate the exact problem when running locally.

Is there anything worth cleaning up immediately following the merge of this PR? Or clean up as we encounter it on specific PRs?

**Comment by pepopowitz** [comment]
> My only hesitation is the timing being right before the minor release. That said, we can always back it out if it's too noisy.

As illustrated [in the prototype PR](https://github.com/camunda/camunda-docs/pull/2664#discussion_r1344322253) (see the last few commits), the only lines checked by vale in the check-format workflow are _changed_ lines. There should be no noise from already-existing violations. In addition, the vale warnings are non-blocking -- the check does not go red for improperly formatted URLs. 

I actually think right now is _the best_ time to introduce this change -- this week will bring a lot of PRs, and this should free up some brain-space for other things during review, while ensuring we don't introduce more cross-version/cross-instance links.

**Comment by pepopowitz** [comment]
> Is there anything worth cleaning up immediately following the merge of this PR? Or clean up as we encounter it on specific PRs?

Our next versioning will likely require fixing at least a handful of URLs. The next archiving process will require fixing anything in archived versions. Between those steps catching things on the "old" end and this PR catching things on the "new" end, our number of infractions should only decrease over time. 

We can definitely do some work to fix the 450-ish existing violations proactively. I don't feel that it's critical. If it's up to me, I'd not do anything about the existing violations right now.

**Comment by pepopowitz** [comment]
I did learn in my recent experimentation on the prototype that I want to re-order the format-check steps, so that vale runs before prettier. Prettier failures are blocking, vale are non-blocking -- running vale first will mean both steps run on every change, instead of bailing early.

**Comment by pepopowitz** [comment]
> I did learn in my recent experimentation on the prototype that I want to re-order the format-check steps, so that vale runs before prettier. Prettier failures are blocking, vale are non-blocking -- running vale first will mean both steps run on every change, instead of bailing early. That change is incoming to this PR.

wait a minute, I am being completely dumb. The intention of this PR was to do only Vale!!!!!

One second, ripping out the prettier stuff.

**Comment by pepopowitz** [comment]
oh, and I forgot to add comments to the regular expressions, so hold off on review yet....

**Comment by pepopowitz** [comment]
ok @akeller this is ready for final review.

**Review by akeller — APPROVED** [review]
Thank you for adding the comments!

**Pull request merged**
