### PR TITLE
chore: update operate screenshots

### PR DESCRIPTION
**Pull request by huygur**
## Description

- create an images/operate folder to use all the images from the same place
- update Operate screenshots to match the latest version

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by huygur** [comment]
hey @christinaausley ,

in the `resolve-incidents-update-variables.md` , there is a bpmn process provided here:

```
Every process instance created for the [`order-process.bpmn`](https://docs.camunda.io/assets/files/order-process-2ae29e9d889a3d640464be250206d550.bpmn/) process model requires an `orderValue` so the XOR gateway evaluation will happen properly.
```

when I download it, I see that it doesn't match the screenshots we are using in the documentation. I don't know where I could update this bpmn, but here is the correct one. could you update it if you know where this link points to? 

```
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" xmlns:modeler="http://camunda.org/schema/modeler/1.0" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" id="Definitions_1" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Web Modeler" exporterVersion="cada200" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.2.0" camunda:diagramRelationId="d608f533-c434-4e6b-a7b5-9078caad9567">
  <bpmn:process id="order-process" isExecutable="true">
    <bpmn:startEvent id="order-placed" name="Order Placed">
      <bpmn:outgoing>Flow_0biglsj</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:endEvent id="order-delivered" name="Order Shipped">
      <bpmn:incoming>Flow_0yovrqa</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:exclusiveGateway id="Gateway_1qlqb7o" name="Order Value?" default="Flow_1fosyfk">
      <bpmn:incoming>Flow_1wtuk91</bpmn:incoming>
      <bpmn:outgoing>Flow_1n8m1op</bpmn:outgoing>
      <bpmn:outgoing>Flow_1fosyfk</bpmn:outgoing>
    </bpmn:exclusiveGateway>
    <bpmn:sequenceFlow id="Flow_1n8m1op" name="&#62;=$100" sourceRef="Gateway_1qlqb7o" targetRef="Activity_1w29h40">
      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=orderValue &gt;= 100</bpmn:conditionExpression>
    </bpmn:sequenceFlow>
    <bpmn:exclusiveGateway id="Gateway_0jji7r4">
      <bpmn:incoming>Flow_1g6qdv6</bpmn:incoming>
      <bpmn:incoming>Flow_0vv7a45</bpmn:incoming>
      <bpmn:outgoing>Flow_0yovrqa</bpmn:outgoing>
    </bpmn:exclusiveGateway>
    <bpmn:sequenceFlow id="Flow_0yovrqa" sourceRef="Gateway_0jji7r4" targetRef="order-delivered" />
    <bpmn:sequenceFlow id="Flow_0biglsj" sourceRef="order-placed" targetRef="Activity_0c23arx" />
    <bpmn:serviceTask id="Activity_0c23arx" name="Initiate Payment">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="initiate-payment" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_0biglsj</bpmn:incoming>
      <bpmn:outgoing>Flow_09wy0mk</bpmn:outgoing>
    </bpmn:serviceTask>
    <bpmn:sequenceFlow id="Flow_09wy0mk" sourceRef="Activity_0c23arx" targetRef="Event_0kuuclk" />
    <bpmn:intermediateCatchEvent id="Event_0kuuclk" name="Payment Received">
      <bpmn:incoming>Flow_09wy0mk</bpmn:incoming>
      <bpmn:outgoing>Flow_1wtuk91</bpmn:outgoing>
      <bpmn:messageEventDefinition id="MessageEventDefinition_14ne4ry" messageRef="Message_2f7fdra" />
    </bpmn:intermediateCatchEvent>
    <bpmn:sequenceFlow id="Flow_1wtuk91" sourceRef="Event_0kuuclk" targetRef="Gateway_1qlqb7o" />
    <bpmn:sequenceFlow id="Flow_1fosyfk" sourceRef="Gateway_1qlqb7o" targetRef="Activity_089u4uu" />
    <bpmn:serviceTask id="Activity_089u4uu" name="Ship Without Insurance">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="ship-without-insurance" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_1fosyfk</bpmn:incoming>
      <bpmn:outgoing>Flow_0vv7a45</bpmn:outgoing>
    </bpmn:serviceTask>
    <bpmn:serviceTask id="Activity_1w29h40" name="Ship With Insurance">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="ship-with-insurance" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_1n8m1op</bpmn:incoming>
      <bpmn:outgoing>Flow_1g6qdv6</bpmn:outgoing>
    </bpmn:serviceTask>
    <bpmn:sequenceFlow id="Flow_1g6qdv6" sourceRef="Activity_1w29h40" targetRef="Gateway_0jji7r4" />
    <bpmn:sequenceFlow id="Flow_0vv7a45" sourceRef="Activity_089u4uu" targetRef="Gateway_0jji7r4" />
  </bpmn:process>
  <bpmn:message id="Message_3eb3s1a" name="payment-r">
    <bpmn:extensionElements>
      <zeebe:subscription correlationKey="=1234" />
    </bpmn:extensionElements>
  </bpmn:message>
  <bpmn:message id="Message_2f7fdra" name="payment-received">
    <bpmn:extensionElements>
      <zeebe:subscription correlationKey="=orderId" />
    </bpmn:extensionElements>
  </bpmn:message>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="order-process">
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="order-placed">
        <dc:Bounds x="172" y="102" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="158" y="138" width="65" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="EndEvent_1253stq_di" bpmnElement="order-delivered">
        <dc:Bounds x="962" y="102" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="944" y="141" width="72" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Gateway_1qlqb7o_di" bpmnElement="Gateway_1qlqb7o" isMarkerVisible="true">
        <dc:Bounds x="525" y="95" width="50" height="50" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="517" y="71" width="65" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Gateway_0jji7r4_di" bpmnElement="Gateway_0jji7r4" isMarkerVisible="true">
        <dc:Bounds x="855" y="95" width="50" height="50" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1f5nuem_di" bpmnElement="Activity_0c23arx">
        <dc:Bounds x="260" y="80" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0vecbjl_di" bpmnElement="Event_0kuuclk">
        <dc:Bounds x="412" y="102" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="408" y="145" width="46" height="27" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1foa0rn_di" bpmnElement="Activity_089u4uu">
        <dc:Bounds x="670" y="80" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1dzmmde_di" bpmnElement="Activity_1w29h40">
        <dc:Bounds x="670" y="210" width="100" height="80" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_1n8m1op_di" bpmnElement="Flow_1n8m1op">
        <di:waypoint x="550" y="145" />
        <di:waypoint x="550" y="230" />
        <di:waypoint x="670" y="230" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="571" y="213" width="38" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0yovrqa_di" bpmnElement="Flow_0yovrqa">
        <di:waypoint x="905" y="120" />
        <di:waypoint x="962" y="120" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0biglsj_di" bpmnElement="Flow_0biglsj">
        <di:waypoint x="208" y="120" />
        <di:waypoint x="260" y="120" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_09wy0mk_di" bpmnElement="Flow_09wy0mk">
        <di:waypoint x="360" y="120" />
        <di:waypoint x="412" y="120" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1wtuk91_di" bpmnElement="Flow_1wtuk91">
        <di:waypoint x="448" y="120" />
        <di:waypoint x="525" y="120" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1fosyfk_di" bpmnElement="Flow_1fosyfk">
        <di:waypoint x="575" y="120" />
        <di:waypoint x="670" y="120" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1g6qdv6_di" bpmnElement="Flow_1g6qdv6">
        <di:waypoint x="770" y="250" />
        <di:waypoint x="880" y="250" />
        <di:waypoint x="880" y="145" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0vv7a45_di" bpmnElement="Flow_0vv7a45">
        <di:waypoint x="770" y="120" />
        <di:waypoint x="855" y="120" />
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>

```

**Comment by christinaausley** [comment]
Of course! Happy to adjust.

In the meantime, please sign the CLA so we can get this merged 👍  Thank you!

**Review by christinaausley — APPROVED** [review]

**Comment by christinaausley** [comment]
Feel free to merge when you are ready 👍

**Comment by huygur** [comment]
> Of course! Happy to adjust.
> 

@christinaausley thanks, will you update the bpmn file in this branch or somewhere else? 🤔

**Comment by christinaausley** [comment]
> > Of course! Happy to adjust.
> 
> @christinaausley thanks, will you update the bpmn file in this branch or somewhere else? 🤔

I will handle this separately from your PR 👍

**Comment by pepopowitz** [comment]
> hey @christinaausley ,
> 
> in the `resolve-incidents-update-variables.md` , there is a bpmn process provided here:
> 
> ```
> Every process instance created for the [`order-process.bpmn`](https://docs.camunda.io/assets/files/order-process-2ae29e9d889a3d640464be250206d550.bpmn/) process model requires an `orderValue` so the XOR gateway evaluation will happen properly.
> ```
> 

That referenced bpmn file doesn't appear to be in the source!!! I'm not sure how the production site is serving that file, or where the source for that file exists. 

My recommendation is that we add the file to the source, and use the BPMN plugin that we use elsewhere to render the model.

Example: 

[This doc](https://github.com/camunda/camunda-docs/blob/0b617fc59fbec66685bd19ebb75eb374300ed35a/docs/components/best-practices/architecture/sizing-your-environment.md?plain=1#L32) emits the model for [this file](https://github.com/camunda/camunda-docs/blob/0b617fc59fbec66685bd19ebb75eb374300ed35a/static/bpmn/best-practices/sizing-your-environment-assets/customer_onboarding.bpmn#L1), [on this page](https://docs.camunda.io/docs/next/components/best-practices/architecture/sizing-your-environment/).

**Comment by pepopowitz** [comment]
@christinaausley I don't think this PR should be blocked for the one missing .bpmn file. It will be a lot more of a headache for us to port the bulk of this PR to other versions after I cut the release today, than for us to fix this one file later.

What do you think?

**Comment by christinaausley** [comment]
Agreed -- we can merge here.

**Pull request merged**
