### PR TITLE
feat: redirect current versions

### PR DESCRIPTION
**Pull request by pepopowitz**
## Description

Addresses #2673 and #1246.

1. Adds redirect rules that temporarily redirect any path which specifies the current main docs version (8.2) or current optimize docs version (3.10.0).
2. Updates the version release script to swap those version numbers according to the newly released numbers.

I tested the redirect rules two ways: indirectly with https://htaccess.madewithlove.com/, and directly [by running locally via Docker](https://github.com/camunda/camunda-docs/blob/0958fb2d677d6ea6c4ad8e6a449a59d31f71ee91/howtos/moving-content.md#testing-redirect-rules). 

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [x] This change or page is part of a marketing blog, conference talk, or something else on a schedule. We'd like to have it for the next version release.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by akeller — APPROVED** [review]

**Review by OmranAbazid — APPROVED** [review]

**Comment by OmranAbazid** [comment]
That was quick, thanks!

**Comment by akeller** [comment]
@pepopowitz when this is merged and release, can you announce it on ask-documentation? I imagine other component teams may be interested in this too.

**Comment by pepopowitz** [comment]
The version number is in the incorrect place -- try this instead: https://docs.camunda.io/docs/8.2/guides/. This follows the pattern set by the older versions in the docs, e.g. https://docs.camunda.io/docs/8.1/guides/.

**Comment by OmranAbazid** [comment]
Yep, I missed this for some reason.
It works as expected 💯 
Thanks for clarifying.

**Pull request merged**
