### PR TITLE
Remove {{}} in Optimize update guide links

### PR DESCRIPTION
**Pull request by akeller**
## Description

Related to #2719, fixes build issues by getting docs.camunda.org syntax out. 

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by akeller** [comment]
Oops, sorry for the misleading branch name. I also couldn't easily figure out where this content should point to, so I didn't include links.

**Comment by akeller** [comment]
If this builds, this will take care of all the links in the docs.camunda.org syntax.

However, there will still be instances where `{{<` is used, particularly for referencing the version alias (not something we do on docs.camunda.io, but is an interesting idea!). Because these don't break the build, I will leave them for now.

**Review by conceptualshark — COMMENTED** [review]
Should these links resolve to the versioned docs? Right now, they're sending me to /next, and I am not sure of the Optimize versioned docs can figure out what version it's in without backing out of the current directory.

**Comment by akeller** [comment]
> Should these links resolve to the versioned docs? Right now, they're sending me to /next, and I am not sure of the Optimize versioned docs can figure out what version it's in without backing out of the current directory.

This does look like a bug. Given the links didn't resolve at all previously, but now go to a page that exists, I think it's a risk I'm willing to accept. Also these versions are technically too old to be supported and the C7 docs will move back to docs.camunda.org soon. 

Any concerns with my logic here @conceptualshark?

**Review by conceptualshark — APPROVED** [review]

**Comment by conceptualshark** [comment]
👍 Works for me - happy to approve!

**Pull request merged**
