### PR TITLE
docs(zeebe): update cluster scaling docs

### LINKED ISSUE #2855: Document Broker Scaling API of Zeebe
As part of the Epic https://github.com/camunda/product-hub/issues/1087 document how to scale Zeebe brokers.

Milestones:

- 8.4.0-alpha1
    -  Add basic documentation of Zeebe API
    - Add note that this is preview/experimental feauture
- 8.4.0-alpha2
   - Improve documentation
   - Add how to scale brokers when using C8 helm
-  8.4.0
    - If the feature is stable in Zeebe, remove the preview note
    - Add open-api spec to Postman if required

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

closes #2855 

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by oleschoenburg — APPROVED** [review]
:+1: I only reviewed the content, not wording etc.

:thought_balloon: Maybe we want to document the `dryRun` parameter here? Could be useful for people just trying out things first, getting a feel for the API etc.

**Comment by deepthidevaki** [comment]
> Maybe we want to document the `dryRun` parameter here? Could be useful for people just trying out things first, getting a feel for the API etc.

Good point. I will add that.

**Review by oleschoenburg — DISMISSED** [review]

**Review by christinaausley — APPROVED** [review]

**Comment by deepthidevaki** [comment]
@christinaausley Anything else to do to from my side to merge this PR?

**Comment by christinaausley** [comment]
@deepthidevaki Nope -- I'll go ahead and merge this in.

**Pull request merged**
