### PR TITLE
Document that Optimize alert emails only allow known users

### PR DESCRIPTION
**Pull request by falko**
## Description

A customer was struggling to get Optimize alerts working with an email address that didn't belong to a known user and got the error message:

> Users with the following email addresses are not available for receiving alerts: ...

Related issue: https://github.com/camunda/camunda-optimize/issues/10592

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [x] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer.

### CODE REVIEW

**Comment by akeller** [comment]
@RomanJRW @toco-cam, I'm wondering how we want to position this. Given that the associated issue is a longstanding bug, I'm curious if you would agree with the language indicating this is the expected behavior—only known users can receive Optimize alert emails. 

I also assume this needs to be backported to all supported versions, but please confirm.

**Comment by akeller** [comment]
@christinaausley, are you assigning this to yourself to backport or review? 🙂

**Comment by christinaausley** [comment]
> @christinaausley, are you assigning this to yourself to backport or review? 🙂

Both! @akeller

**Review by akeller — APPROVED** [review]
Thank you!

**Pull request merged**
