### PR TITLE
Update Process Instance Migration concept for 8.4 release

### PR DESCRIPTION
**Pull request by berkaycanbc**
## Description

Removed the danger banner because it will be fixed in Zeebe with PR https://github.com/camunda/zeebe/pull/15621.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {8.4} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by abbasadel — APPROVED** [review]
LGTM

**Review by christinaausley — DISMISSED** [review]

**Comment by akeller** [comment]
Should we also [announce](https://docs.camunda.io/docs/next/reference/announcements/) this feature?

**Comment by berkaycanbc** [comment]
@christinaausley I sent another update that I also removed the danger banner from Operate's page. Please take a look. 👀

**Review by pedesen — APPROVED** [review]
Thx for removing the Operate warning, LGTM :rocket:

**Comment by MaxTru** [comment]
> Should we also [announce](https://docs.camunda.io/docs/next/reference/announcements/) this feature?

No, I don't think this is appropriate. We use the announcements page for: deprecation notices, key changes in support environments.

@akeller maybe from the docs side, we should have an internal policy describing what to include on the announcements page?

**Comment by christinaausley** [comment]
@MaxTru I'll pop an item on my board to create a WCoE doc distinguishing between our release updates, announcements, etc.

**Review by christinaausley — COMMENTED** [review]
If we do not announce this, I would recommend keeping an eye out to see if any users inquire with support as to whether or not this is still an experimental feature 👍

**Review by christinaausley — APPROVED** [review]

**Comment by christinaausley** [comment]
If we do not want this to go out until `8.4`, feel free to go ahead and add a `hold` label.

**Comment by MaxTru** [comment]
> If we do not want this to go out until `8.4`, feel free to go ahead and add a `hold` label.

IMO, since this will be shown on the `next` branch only, we can merge right away

**Comment by abbasadel** [comment]
> Should we also [announce](https://docs.camunda.io/docs/next/reference/announcements/) this feature?

Looking back to other announcements, I see only information about deprecation and breaking changes. 

But you have a good point. It is not easy to find the changes/features between minor versions since the are mentioned only in the "blog post". I think this is worth discussing in the ELT

**Pull request merged**
