### PR TITLE
feat(self-managed): add basic auth for deployments docs

### PR DESCRIPTION
**Pull request by philippfromme**
Adds documentation for the new basic authentication option for deployments to C8 self-managed.

Screenshot will be automated: https://github.com/camunda/camunda-docs-modeler-screenshots/pull/83

image

Closes https://github.com/camunda/camunda-modeler/issues/4285

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer.

### CODE REVIEW

**Comment by barmac** [comment]
As this feature is available in any Camunda version, I think it makes sense to migrate it to also to the supported Camunda versions, i.e. 8.3 and 8.4

**Comment by philippfromme** [comment]
> As this feature is available in any Camunda version, I think it makes sense to migrate it to also to the supported Camunda versions, i.e. 8.3 and 8.4

Only in the latest Camunda Modeler, though. But i'll add it to all versions.

**Comment by philippfromme** [comment]
@christinaausley @barmac Added documentation to versioned docs, too. Ready to review/merge.

**Comment by nikku** [comment]
Works for me :clap:

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
