### PR TITLE
Move Go and CLI client to community section

### PR DESCRIPTION
**Pull request by akeller**
## Description

Structural move for https://github.com/camunda/product-hub/issues/2438.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by megglos** [comment]
@akeller as we have a first [RC release](https://github.com/camunda-community-hub/zeebe-client-go/releases/tag/v8.6.0-RC1) of the community client I would rebase this PR and add commits on top to adjust the module name accordingly for the `next` docs. Afterwards it should be ready for review and merge.

**Comment by akeller** [comment]
> @akeller as we have a first [RC release](https://github.com/camunda-community-hub/zeebe-client-go/releases/tag/v8.6.0-RC1) of the community client I would rebase this PR and add commits on top to adjust the module name (which changed with the move) accordingly for the `next` docs. Afterwards it should be ready for review and merge.

@megglos just to confirm, you will do the rebasing, correct? Do you want to take over assignee?

**Comment by megglos** [comment]
@akeller I updated all zbctl links to the new community location, as it's not an official tool anymore with 8.6 I will replace this with the equivalent REST API reference next with https://github.com/camunda/camunda/issues/22665

**Comment by megglos** [comment]
@akeller can't request review as you were the creator of the PR 🙈 can you still take a look?

**Comment by akeller** [comment]
Approaching the end of my day here, I will review this tomorrow with fresh eyes.

**Review by mesellings — COMMENTED** [review]
I also gave this a non-approval type review just as another set of eyes, and links and references all seem okay, apart from a few on the [Job worker page](https://preview.docs.camunda.cloud/pr-4228/docs/next/apis-tools/community-clients/go-client/job-worker/#backoff-configuration) that may (or may not) need updating, shown in the image below:

image

**Comment by megglos** [comment]
Thanks for spotting @mesellings ! I'll fix those links!

**Comment by akeller** [comment]
Structurally, this looks good. There are some additional pieces I'd like to see cleaned up, including softening the language that makes the CLI client look officially supported: 

> zbctl is the command line interface to interact with Camunda 8.

Instead, say something like:

> zbctl is a community-supported command line interface to interact with Camunda 8.

It's subtle and something we can make more overt if we need to (adding an admonition).

**Comment by mesellings** [comment]
@megglos Shall I make these language softening changes for you, or have you already started making them?

**Comment by megglos** [comment]
> @megglos Shall I make these language softening changes for you, or have you already started making them?
@mesellings 
I was coming here to ask if you or Amara can take it, as I'm out sick. So YES that would be great! Thank you so much!

**Comment by mesellings** [comment]
> > @megglos Shall I make these language softening changes for you, or have you already started making them?
> 
> @mesellings I was coming here to ask if you or Amara can take it, as I'm out sick. So YES that would be great! Thank you so much!

Will do, hope you feel better soon 👍

**Comment by mesellings** [comment]
@akeller @megglos I have added this clarification to the Quick reference and Getting started pages for both the CLI and Go Client Library - are you happy with this or do you think it needs to be called out more?

image

**Comment by akeller** [comment]
@mesellings - I'm happy with this. We can always monitor if it needs something stronger/louder. Thank you!

**Comment by akeller** [comment]
> @akeller @megglos I have added this clarification to the Quick reference and Getting started pages for both the CLI and Go Client Library - are you happy with this or do you think it needs to be called out more?
> 
> image

@aleksander-dytko - do we need to add text about how these tools are deprecated? Or link to the release notes and/or blog about deprecation? @leiicamundi made a good point on another PR that we should be clear about this, even if it will be community-supported.

**Comment by akeller** [comment]
> > @akeller @megglos I have added this clarification to the Quick reference and Getting started pages for both the CLI and Go Client Library - are you happy with this or do you think it needs to be called out more?
> > image
> 
> @aleksander-dytko - do we need to add text about how these tools are deprecated? Or link to the release notes and/or blog about deprecation? @leiicamundi made a good point on another PR that we should be clear about this, even if it will be community-supported.

Adjusted in latest commit.

**Comment by akeller** [comment]
@aleksander-dytko please review so we can merge :)

**Review by aleksander-dytko — DISMISSED** [review]

**Review by mesellings — DISMISSED** [review]
Lgtm 👍 🚀

**Comment by mesellings** [comment]
@akeller do you want me to merge this?

**Comment by akeller** [comment]
@mesellings I almost said yes, but I just realized this PR doesn't have redirects for the moved content.

**Pull request merged**
