### PR TITLE
docs: added ES,OS versions to announcement

### PR DESCRIPTION
**Pull request by igpetrov**
## Description

docs: added ES,OS versions to announcement

## When should this change go live?

Hi team, sorry for urgency, we missed this announcement and would like to release it rather earlier. If possible, this week or early next week would do the trick. Thank you!

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [x] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Review by conceptualshark — APPROVED** [review]

**Comment by igpetrov** [comment]
Hi @mesellings 

Sorry, I didn't see that you were also reviewing. I would actually remove AWS at all (without adding Amazon).

**Comment by mesellings** [comment]
> Hi @mesellings
> 
> Sorry, I didn't see that you were also reviewing. I would actually remove AWS at all (without adding Amazon).

No problem - I must have commented just as it was merged! I suppose we do say Amazon OpenSearch in the docs already though, so perhaps better to be explicit for consistency ? e.g. https://docs.camunda.io/docs/next/self-managed/setup/guides/using-existing-opensearch/

**Comment by igpetrov** [comment]
> > Hi @mesellings
> > Sorry, I didn't see that you were also reviewing. I would actually remove AWS at all (without adding Amazon).
> 
> No problem - I must have commented just as it was merged! I suppose we do say Amazon OpenSearch in the docs already though, so perhaps better to be explicit for consistency ? e.g. https://docs.camunda.io/docs/next/self-managed/setup/guides/using-existing-opensearch/

Strongly supportive for consistency. Do you want me to change it?

**Comment by mesellings** [comment]
> > > Hi @mesellings
> > > Sorry, I didn't see that you were also reviewing. I would actually remove AWS at all (without adding Amazon).
> > 
> > 
> > No problem - I must have commented just as it was merged! I suppose we do say Amazon OpenSearch in the docs already though, so perhaps better to be explicit for consistency ? e.g. https://docs.camunda.io/docs/next/self-managed/setup/guides/using-existing-opensearch/
> 
> Strongly supportive for consistency. Do you want me to change it?

I would go ahead and change it thanks @igpetrov, unless @conceptualshark feels strongly that we should remove it?

**Comment by conceptualshark** [comment]
Consistency works for me here. 👍 Thanks for the catch!

**Pull request merged**
