### PR TITLE
feat: Add docs about new separator element in form-js

### PR DESCRIPTION
**Pull request by vsgoulart**
## When should this change go live?

- [x] This change is not yet live and should not be merged until 8.4.0-alpha1 release
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by pinussilvestrus — APPROVED** [review]

**Review by christinaausley — APPROVED** [review]
Looks good, but applied a `hold` label until we are ready for merge here.

**Comment by akeller** [comment]
Hi folks, I'm not familiar with the timing for `8.4.0-alpha0`, is this a typo? See my internal thread regarding upcoming product releases - https://camunda.slack.com/archives/C03NFMH4KC6/p1698844956633039

**Comment by vsgoulart** [comment]
> Sounds like this is a typo, alpha1 to be released with alphas and patches on the 2nd Tuesday of the month. Adjusting the description.

hey @akeller , yeah, it's a typo
it should be fixed now

**Comment by christinaausley** [comment]
Hi @vsgoulart -- just want to confirm this is ready for merge next week upon release?

**Comment by vsgoulart** [comment]
> Hi @vsgoulart -- just want to confirm this is ready for merge next week upon release?

@christinaausley Yes, that's correct

**Pull request merged**
