### PR TITLE
Document REST API middleware

### LINKED ISSUE #4108: Document new Gateway custom middleware mechanism for the Zeebe REST API
Support for REST API custom middleware in the (Zeebe) Gateway is documented.

*AC:*

- Gateway configuration is documented
- A REST API filters guide is available (similar to the one about gRPC interceptors)
- Docs pages that link to gRPC interceptors also link to REST API filters.
- Remove notes that state "no REST API middleware support".

### LINKED ISSUE #4109: Document new Java client custom middleware mechanism for the Camunda REST API
Support for REST API custom middleware in the (Zeebe) Java client is documented.

**AC:**
- Docs pages that document gRPC `ClientInterceptors` also document REST API `AsyncExecChainHandlers` for the Java client.

### PR DESCRIPTION
**Pull request by koevskinikola**
## Description

Document support for REST API middleware for the Zeebe Gateway and the (Zeebe) Java client and Spring SDK.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [x] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

closes #4109
closes #4108

### CODE REVIEW

**Comment by megglos** [comment]
@koevskinikola do you consider it likely these docs make it into the docs till the alpha release next Tuesday?

**Comment by koevskinikola** [comment]
@megglos the PR is mostly done, I just need to go over the text one more time to confirm that everything is correct, and that the filter creation guide is completely functional.

The PR will likely be merged before next Tuesday.

**Comment by koevskinikola** [comment]
@tmetzke @christinaausley it would be good if we could merge this PR before next Tuesday (13.08.2024) so that we can link these docs in the alpha release blog post.

**Comment by christinaausley** [comment]
@koevskinikola I can get to this today if you're ready for final review. Upon approval I'll go ahead and merge and release.

**Comment by koevskinikola** [comment]
@christinaausley yes, the PR is done from my side. That's great, thanks! 🎉

**Review by christinaausley — COMMENTED** [review]
I've given this a general review, but want to have one more look over this Monday morning and have @tmetzke take a look. We can get this released Monday morning/afternoon in the US so you can link to the documentation if that works!

**Review by tmetzke — APPROVED** [review]
👍 The guide itself looks good from my end, really nice job! 🚀 
💭 We have this issue in the backlog. Do you think you could skim that one and assess if this influences the docs we have here? Looks like the advice to use JDK 11 isn't appropriate anymore (but the user may also simply be wrong).
⚠️ If you don't have that time currently, let's prioritize getting these docs here in first and assess the other issue later.

**Comment by tmetzke** [comment]
> @tmetzke thanks for the feedback. Regarding issue #17482, it's more focused on the gRPC interceptors API. The only thing related to the new REST API filters is the Java version. I think it would be good to document that a JDK version of 21 should be used for best compatibility with Zeebe.
> 
> I'll update the Java versions to 21 in both the Filter and Interceptor guides. 👍

Sounds good to me 👍

**Comment by koevskinikola** [comment]
@tmetzke @christinaausley I bumped the JDK versions in the REST API filter, and gRPC interceptor docs. The PR is ready for a final review now.

**Review by tmetzke — APPROVED** [review]

**Comment by christinaausley** [comment]
This is headed out now with https://github.com/camunda/camunda-docs/releases/tag/8.5.41 👍

**Pull request merged**
