### PR TITLE
chore(docs): document undo/redo functionality and limitations

### PR DESCRIPTION
**Pull request by marcellobarile**
## Description

Introduces the `undo` and `redo` buttons, and lists a few known limitations in the undo/redo management.

Closes https://github.com/camunda/web-modeler/issues/10935

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [x] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Review by HanselIdes — DISMISSED** [review]
LGTM

**Review by mesellings — APPROVED** [review]
@marcellobarile Happy to approve, nice job! 🚀 

I made some changes directly to the branch for general readability, formatting, and doc standards. I'd like to take a look through the whole Web Modeler docs at some point, but that will be another project/set of PRs. 👍

**Review by wollefitz — APPROVED** [review]
Lgtm, thanks!

**Comment by marcellobarile** [comment]
@mesellings the feature has been released to prod (SaaS); I'll proceed with merging the PR.

**Comment by akeller** [comment]
> @mesellings the feature has been released to prod (SaaS); I'll proceed with merging the PR.

@marcellobarile were you expecting a docs release too? I will do one now so it's available.

**Comment by marcellobarile** [comment]
yes please :)

**Pull request merged**
