### PR TITLE
add known issue for keycloak

### PR DESCRIPTION
**Pull request by christinaausley**
## Description

Closes https://github.com/camunda/developer-experience/issues/200.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [x] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by christinaausley** [comment]
I am largely struggling with **where** this should go, as it spans across all clients. Any insight is appreciated.

**Comment by akeller** [comment]
I wouldn't add this to Announcements, but I recommend adding it to the Troubleshooting section (Self Managed > Identity > Troubleshooting). I would follow the same pattern with `Problem: / Solution: `

Now, is this a topic for the [Overview](https://docs.camunda.io/docs/self-managed/identity/troubleshooting/troubleshoot-identity/) or [Common problems](https://docs.camunda.io/docs/self-managed/identity/troubleshooting/common-problems/)? Or could we consolidate these pages? I'm not sure I see the difference in what content should go where.

**Comment by dlavrenuek** [comment]
Thank you for adding the changes @christinaausley 🥇 I agree with @akeller that this should go to the common problems section, but also only in the 8.2 and 8.1 docs. A [fix for this behavior](https://github.com/camunda-cloud/identity/issues/2120) was released with 8.3 on our side, so 8.3+ should not be affected.

**Comment by christinaausley** [comment]
> Now, is this a topic for the [Overview](https://docs.camunda.io/docs/self-managed/identity/troubleshooting/troubleshoot-identity/) or [Common problems](https://docs.camunda.io/docs/self-managed/identity/troubleshooting/common-problems/)? Or could we consolidate these pages? I'm not sure I see the difference in what content should go where.

Agreed here. I can open a separate issue to consolidate these, unless @dlavrenuek or @Ben-Sheppard have different ideas.

**Review by dlavrenuek — APPROVED** [review]
Thank you for the changes, looks good from my perspective 💯

**Review by akeller — APPROVED** [review]

**Pull request merged**
