### PR TITLE
docs(java-client): add announcement of zeebe java client deprecation

### PR DESCRIPTION
**Pull request by nicpuppa**
## Description

Add an announcement regarding Zeebe Java Client deprecation in 8.7, to be replaced by Camunda Client

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

closes: #4047

### CODE REVIEW

**Comment by christinaausley** [comment]
@nicpuppa I see this is still in `draft`, is that because you have more changes coming, or this is most of it and you're ready for review? 😄

**Comment by nicpuppa** [comment]
> @nicpuppa I see this is still in `draft`, is that because you have more changes coming, or this is most of it and you're ready for review? 😄

Hey @christinaausley , I drafted this PR because we need to discuss if we took the right approach for the client. Later today I'm syncing with the team on this 🤞

**Comment by tmetzke** [comment]
As described in the [latest decision](https://github.com/camunda/camunda/issues/19479#issuecomment-2255047880), let's rewrite the announcement, stating that the Zeebe Client will be replaced by the more general Camunda Client with `8.7`.

**Review by tmetzke — CHANGES_REQUESTED** [review]
The announcement in 8.6 will only be a heads-up for 8.7, so it should use the future tense. Plus, some things we don't know yet so let's not promise them.

**Comment by nicpuppa** [comment]
Hey @christinaausley this PR is ready to be reviewed 👍

**Comment by christinaausley** [comment]
Would it be worth adding a brief note in https://docs.camunda.io/docs/apis-tools/java-client/ as well?

**Review by christinaausley — DISMISSED** [review]

**Comment by akeller** [comment]
@tmetzke @megglos can we get a review from either of you for this?

I also second what @christinaausley [said](https://github.com/camunda/camunda-docs/pull/4051#issuecomment-2260424972).

Will we have a blog or forum content on this topic?

**Comment by tmetzke** [comment]
> @tmetzke @megglos can we get a review from either of you for this?
> 
> I also second what @christinaausley [said](https://github.com/camunda/camunda-docs/pull/4051#issuecomment-2260424972).
> 
> Will we have a blog or forum content on this topic?

A heads-up note there that this will become the Camunda Client with 8.7 would be nice, I agree, good idea, @christinaausley 👍
It can link back to the announcement for further information.

No blog or forum post planned so far. A blog entry is too much here for the change from Zeebe Client to Camunda Client. Regarding the overall theme from component REST APIs to one consolidated C8 REST API and accordingly from component clients to one consolidated Camunda Client would definitely be worth a blog post. /cc @aleksander-dytko for visibility, not sure if anything is already planned in that direction.

**Comment by nicpuppa** [comment]
Hey @christinaausley @tmetzke I wrote an heads up as suggested, please have a look 💪

**Review by tmetzke — APPROVED** [review]
👍 Looks good to me 🚀

**Review by MaxTru — DISMISSED** [review]

**Review by christinaausley — APPROVED** [review]

**Comment by christinaausley** [comment]
🚀

**Pull request merged**
