### PR TITLE
Move the BPMN diagram to the expected folder

### PR DESCRIPTION
**Pull request by ingorichtsmeier**
## Description

The pull request #2627 puts a BPMN diagram into a wrong folder, so that it is not visible in the live system.

I found a 404 in my web console.

This pull request will repair the issue.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [X] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [X] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
@ingorichtsmeier I would expect you need to change the location in the markdown file as well. 

Currently:
`<div bpmn="best-practices/dealing-with-problems-and-exceptions-assets/custom-idempotency-handling.bpmn" />`

You'll need to point at the static directory. 

Somewhat related, it looks like other BPMN diagrams on this page may be in an unexpected place. CC @berndruecker @christinaausley

**Comment by ingorichtsmeier** [comment]
Hi @akeller,

when writing my small addition, I copied the location from other examples on the same page. I didn't take the time to run the preview before I created the first pull request.

Checking the release, I could not see the diagram and dived deeper. I found my mistake (and the other BPMNs referenced on the page) and now took the time to run the preview successfully.

I haven't found documentation how this magic BPMN.io integration in the best-practices works.

Maybe it's worth to spend a few sentences here: https://github.com/camunda/camunda-docs/blob/main/howtos/markdown-and-mdx-features.md.
* Drop your bpmn here here
* Reference it like this
* how to reference tasks or other BPMN elements in your text.

This pull request can be merged, I have checked the preview now.

**Comment by christinaausley** [comment]
I'll launch an issue to handle the additional BPMN details -- thank you @ingorichtsmeier

**Review by christinaausley — APPROVED** [review]

**Review by christinaausley — CHANGES_REQUESTED** [review]
@ingorichtsmeier I can merge this in, but can you make this particular adjustment across the supported versions as well?

**Comment by christinaausley** [comment]
I'll launch an issue to handle the additional BPMN details -- thank you @ingorichtsmeier

**Review by christinaausley — APPROVED** [review]

**Comment by akeller** [comment]
@christinaausley thank you. You can bring @berndruecker into the issue since he developed this integration. You can pair with him to make sure all the diagrams are correctly linked and we have documentation on how others can use this feature inside or outside of the Best Practices section.

**Pull request merged**
