### PR TITLE
docs(optimize): update task analysis docs

### PR DESCRIPTION
**Pull request by misiekhardcore**
related to OPT-7387

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — DISMISSED** [review]

**Comment by akeller** [comment]
@misiekhardcore we don't have a link to that Optimize ticket, so I'm not sure when we should merge and plan to release this change. Is this something that is going live in the Jan minor release?

**Comment by misiekhardcore** [comment]
> @misiekhardcore we don't have a link to that Optimize ticket, so I'm not sure when we should merge and plan to release this change. Is this something that is going live in the Jan minor release?

Hey, @akeller, [here](https://jira.camunda.com/browse/OPT-7387) is the optimzie ticket for this. These changes are going to be a part of 8.4 release, yes :)

**Comment by christinaausley** [comment]
I am going to place a `hold` label to ensure I don't merge here 😄

**Comment by misiekhardcore** [comment]
@christinaausley I had to update few things

**Review by OmranAbazid — APPROVED** [review]

**Review by christinaausley — APPROVED** [review]

**Comment by christinaausley** [comment]
@misiekhardcore Are you comfortable merging this into `next` for release next week?

**Comment by misiekhardcore** [comment]
@christinaausley yes

**Pull request merged**
