### PR TITLE
Add ES to update guide

### PR DESCRIPTION
**Pull request by akeller**
## Description

Adds ES guide link for updating.

These changes will only be in `/next/` or the `/docs` directory as they are the next version of the product.

## When should this change go live?

Coordinate merge & release via https://camunda.slack.com/archives/C04QG866E3Z.

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
I linked to the [current ES docs page](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes.html) that includes a list of all minor version update guides for ES 8.x.

This will be the easiest for us to maintain long-term, but I'm open to suggestions of exact versions of ES 8 for compatibility with Camunda Platform 8.3, although it looks like there could be multiple, so I link to supported environments.

**Review by christinaausley — DISMISSED** [review]
Do you have any additional changes to make here? These changes look good to me 👍

**Comment by akeller** [comment]
> Do you have any additional changes to make here? These changes look good to me 👍

Great question - I'm still waiting for an Engineering review, someone working the technical implementation on the Epic. I'll keep it in draft for now.

**Comment by akeller** [comment]
@jwulf can you have a look at this PR and review for clarity? Would you understand from the link and text provided how to update Elasticsearch?

**Review by christinaausley — APPROVED** [review]
Approving from technical perspective but will wait on approval from @jwulf before squash and merge.

**Comment by akeller** [comment]
I'm actively discussing this with @MaxTru - since many components will be impacted by the ES update, he would like DevEx to run through this guide even though most of the content is owned by ES, not Camunda. I'll add the `hold` label for now.

**Review by christinaausley — DISMISSED** [review]

**Review by christinaausley — APPROVED** [review]
Just had to update Camunda 8 references 👍

**Pull request merged**
