### PR TITLE
Add spring boot test annotation

### PR DESCRIPTION
**Pull request by ingorichtsmeier**
Make the template runnable

## Description
When you just copy the snippet, the Zeebe engine won't start.

You have to add the `@SpringBootTest` annotation as well.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [x] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by akeller** [comment]
Hi @ingorichtsmeier, we actually [removed this](https://github.com/camunda/camunda-docs/pull/3780) in April based on a request from Support. Is there something else going on here with either the docs or code?

**Comment by ingorichtsmeier** [comment]
@akeller, unfortunately, Emma didn't give a reason for her change request. 

I tried to run the example that I copied (without `@SpringBootTest`) and the Zeebe engine didn't start. Hmm...

After looking at the complete Twitter example on GitHub, I found the missing annotation.

I think it depends on the developers' expectation. If you want a Spring integration test, starting the Zeebe engine in the background and executing the tests on it, you need this annotation.

I don't know, which test would run without it. Maybe @epollum has more background?

There isn't anything else than my confusion. I tried to reduce my mental load by adding the annotation to the copy-template.

**Review by pepopowitz — APPROVED** [review]
I confirmed locally that the tests require this attribute in order to pass. 

@ingorichtsmeier @akeller what do you think about waiting a day or so for @epollum to provide feedback on why we removed this attribute in #3780 and then merging? (We can always revert if we have a good reason to after merging.)

**Comment by akeller** [comment]
Thanks @pepopowitz! Can you also ping Emma on Slack? I'm not sure how often she's on GitHub.

**Comment by pepopowitz** [comment]
For what it's worth, I think we should merge this, and revisit if we get feedback about the original removal.

**Comment by akeller** [comment]
> For what it's worth, I think we should merge this, and revisit if we get feedback about the original removal.

Good enough for me! 🟢

**Comment by epollum** [comment]
@ingorichtsmeier ,

I just tried this again with the @SpringBootTest and it does not work, it doesn't either the embedded or test containers that [zeebe-process-test](https://github.com/camunda/zeebe-process-test) should use and instead tries to connect to an external zeebe cluster

Please see https://github.com/epollum/c8-kind/tree/main/zeebe-application for example.

**Comment by ingorichtsmeier** [comment]
After taking a look at my example and the given twitter example, I will close my pull request by now.

Reasons:
* spring-boot-starter-camunda-sdk is not an option to replace the community driven spring-boot-starter-camunda right now. In version 8.5.6 the sdk has a dependency to the community library, which is a grey area for support.
* In version 8.5, no test support for the sdk is available. It's coming with 8.6-alpha4. Tests still require the community test library.
* The twitter example uses a lot of spring boot support (Instead of my example from the hackdays), for example the `@MockBean` for the twitter service. Rewriting it for `@ZeebeProcessTest` is an extensive change to the example.

My personal test class will work with `@ZeebeProcessTest` as well when I remove the `@Autowire` from the Zeebe client. 

It feels halfhearted to me to just remove `@SpringBootTest`annotation from the example for showing, that spring-zeebe is not officially supported. 

But it is easier to wait for the release of 8.6 when the spring SDK supports tests and removes the dependency to the community library completely. This would be a good point to improve the best practice (and the example) with full supported libraries.

**Pull request closed without merging**
