### PR TITLE
feat(connectors): add MSFT O365 Connector

### PR DESCRIPTION
**Pull request by igpetrov**
## Description

Adds doc related to Microsoft Office 365 Mail Connector.

## When should this change go live?

With release 2023-12-12.

- [x] This change is not yet live and should not be merged until 2023-12-12 (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — DISMISSED** [review]
Microsoft only refers to it as Microsoft 365 (formerly O365) so I adjusted those instances. Technical review in latest commit 👍

**Comment by igpetrov** [comment]
> Microsoft only refers to it as Microsoft 365 (formerly O365) so I adjusted those instances. Technical review in latest commit 👍

Thank you!

**Comment by christinaausley** [comment]
Weird. My commit wasn't pushed up. I'll plan to re-review this week 👍

**Comment by igpetrov** [comment]
> Weird. My commit wasn't pushed up. I'll plan to re-review this week 👍

Oh no, that's my fault! I am sorry! I likely overwrote it on rebase 😕

**Comment by christinaausley** [comment]
@igpetrov Any final changes here, or can we go ahead and merge?

**Comment by igpetrov** [comment]
@christinaausley let's merge this

**Pull request merged**
