### PR TITLE
docs(connectors): Add documentation and exemple for ConnectorRetryException

### PR DESCRIPTION
**Pull request by johnBgood**
## Description

Related issue: https://github.com/camunda/team-connectors/issues/630
Related PR: https://github.com/camunda/connectors/pull/2146

## When should this change go live?

- [x] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by christinaausley** [comment]
Hi @johnBgood -- should this be backported, or is this only for the next version of documentation?

**Comment by johnBgood** [comment]
> Hi @johnBgood -- should this be backported, or is this only for the next version of documentation?

Hey, it's only for the next version :)

**Comment by christinaausley** [comment]
@johnBgood cool, we can merge then. However:

> This functionality is already available but undocumented.

I noticed the related issue and PR have been completed. Can we remove the hold label, or is this for the upcoming release?

**Comment by johnBgood** [comment]
> @johnBgood cool, we can merge then. However:
> 
> > This functionality is already available but undocumented.
> 
> I noticed the related issue and PR have been completed. Can we remove the hold label, or is this for the upcoming release?

Sorry for the delay, I removed the `hold` label and added the `target` instead.

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
