### PR TITLE
docs(web-modeler): start forms in self-managed

### PR DESCRIPTION
**Pull request by vpellegrino**
## Description

Closes https://github.com/camunda/web-modeler/issues/7121

The feature itself was already available for SaaS users. However, it was wrapped with the "Publication" feature, which does not exist yet on Self-Managed.
In this PR, I have:
- Removed duplication around how to link a form with a none start event.
- Extracted the section above in a separate independent one (that is not targeted anymore to SaaS only).

Please let me know if we can improve anything.

## When should this change go live?

- [x] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — APPROVED** [review]

**Comment by wollefitz** [comment]
@vpellegrino Thanks for the contribution! I made a couple of changes with https://github.com/camunda/camunda-docs/pull/3066/commits/e87d3cfc145466105586bb2026c6a68d7272231b and where I renamed the "user task linking" page to "form linking" in order to be able to link there from both places that describe linking within start events and user tasks.

@christinaausley As I made a couple of changes (including adding a rewrite rule in `.htaccess`) could you please have another look?

**Review by christinaausley — APPROVED** [review]
Nice redirect @wollefitz 💪

**Comment by christinaausley** [comment]
If this is to be held until the `8.4` release, feel free to go ahead and add a `hold` label 👍

**Comment by wollefitz** [comment]
> If this is to be held until the `8.4` release, feel free to go ahead and add a `hold` label 👍

This can already be merged, thanks for the review!

**Pull request merged**
