### PR TITLE
Updated UI reference screenshots

### PR DESCRIPTION
**Pull request by camundom**
## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — APPROVED** [review]
This is excellent. Thank you, thank you, thank you!

**Comment by christinaausley** [comment]
@camundom Would you be able to add these to the `8.3` docs as well?

**Comment by akeller** [comment]
Are any of these screenshots covered under screenshot automation tooling? Or were these screenshots generated from screenshot automation tooling?

**Comment by christinaausley** [comment]
> Are any of these screenshots covered under screenshot automation tooling? Or were these screenshots generated from screenshot automation tooling?

@akeller I'm fairly confident none of these were covered with automation tooling, or we would have seen them updated with the component docs (unless they were just forgotten, which may have been the case 😞 )

Looping in @CatalinaMoisuc regarding the Modeler-related docs here.

**Comment by akeller** [comment]
There are three Console screenshots. @ultraschuppi are these included in Console screenshot automation? Or could they be added?

**Comment by christinaausley** [comment]
@CatalinaMoisuc I'm surprised to hear this based on https://docs.google.com/document/d/1hsdMSCSzXG5Y2RvYijNIbX7yQ3yMG_29LFcTzveTGJQ/edit?usp=sharing -- is this outdated?

**Comment by akeller** [comment]
> @camundom Would you be able to add these to the `8.3` docs as well?

I see this as blocking still. Currently, this PR would only update `/next/`, which is the preview version for 8.4

**Comment by camundom** [comment]
> > @camundom Would you be able to add these to the `8.3` docs as well?
> 
> I see this as blocking still. Currently, this PR would only update `/next/`, which is the preview version for 8.4

Ah ok! In that case, I would need some guidance in adding these to the 8.3 docs please, as this is my first attempt at creating a branch/pr/ merge in Github 🙂

**Comment by christinaausley** [comment]
No problem 👍 You can find the 8.3 docs in the same repo -- under folder `versioned_docs` -> `version-8.3`

Let me know if you need more assistance!

**Comment by akeller** [comment]
@camundom do you need help with this?

**Comment by camundom** [comment]
> @camundom do you need help with this?

Thanks @christinaausley @akeller . I'll pick this up today. I'll get in touch if I need any help.

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
