### PR TITLE
docs(ootbc,slack): updated Slack doc with new property

### PR DESCRIPTION
**Pull request by igpetrov**
## Description

docs(ootbc,slack): updated Slack doc with new property

## When should this change go live?

Should go around next patch release - around 13th of March

- [x] This change is not yet live and should not be merged until 9th - 13th of March (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
@igpetrov would it be fair to label this with `8.5.0-alpha2`? The dates seem aligned to the alpha2 delivery.

**Comment by igpetrov** [comment]
> @igpetrov would it be fair to label this with `8.5.0-alpha2`? The dates seem aligned to the alpha2 delivery.

@akeller sure, that makes sense.

**Comment by christinaausley** [comment]
@igpetrov I've removed the `hold` label and pulled this out of draft -- are there any additional changes to make here given the draft environment? If not, let's go ahead and merge 👍

**Comment by igpetrov** [comment]
Hi @christinaausley 

No changes here, merging.

**Pull request merged**
