### PR TITLE
feat(updateGuides): add note for supported environments

### PR DESCRIPTION
**Pull request by MaxTru**
## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [x] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by MaxTru** [comment]
This is to drive further clarity on supported environemnts

**Comment by christinaausley** [comment]
We do have [this page](https://docs.camunda.io/docs/next/reference/supported-environments/), and could always link to it when users don't appear to have enough clarity. WDYT?

**Comment by christinaausley** [comment]
@MaxTru just for my own context, have users been complaining about this? We could certainly link to supported environments, but from the added text it seems that is not enough?

**Comment by MaxTru** [comment]
> @MaxTru just for my own context, have users been complaining about this? We could certainly link to supported environments, but from the added text it seems that is not enough?

Support highlighted this to me here: https://camunda.slack.com/archives/C02UMKN3DTL/p1702615635011049

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
