### PR TITLE
docs(connectors): Add Github Create workflow dispatch event section

### PR DESCRIPTION
**Pull request by ev-codes**
## Description

Document the GitHub OOTB connector's new Github Actions "Create workflow dispatch event" operation.

[Related issue](https://github.com/camunda/connectors/issues/1074)

[web-modeler release v8.4.6](https://github.com/camunda/web-modeler/releases/tag/v8.4.6) included this change.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [x] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [X] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [X] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [X] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by ev-codes** [comment]
This change is pending web-modeler release.

As suggested in the PR template, I will keep this PR in draft until the next web-modeler release.

**Comment by christinaausley** [comment]
> The feature documented in this PR will go live with the next web-modeler release. There is no set date for this yet.
> 
> I will keep this PR in draft until the documented feature goes live (as the PR template suggests).
> 
> [edit: re-word for clarity]

@ev-codes Cool, just let me know when you're ready for final review 👍

**Comment by ev-codes** [comment]
@akeller yes it does - I assigned @christinaausley for review.

Are there any other actions I should take?

**Comment by akeller** [comment]
@ev-codes, if this is ready to be released, coordinate with @christinaausley to review, merge, and release.

**Comment by ev-codes** [comment]
@akeller thank you, I just reached out to @christinaausley over Slack to make sure she doesn't miss this.

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
