### PR TITLE
docs(forms): add table component

### PR DESCRIPTION
**Pull request by vsgoulart**
## Description

Documents new table component in `form-js`

Closes https://github.com/bpmn-io/form-js/issues/940

## When should this change go live?

- [x] This change is not yet live and should not be merged until 2024-01-04 (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
@vsgoulart can I ask why Jan 4? We'll have the 8.4.0 release on Jan 9th. Does this need to go out Jan 4 exactly or should it go with the minor?

**Comment by vsgoulart** [comment]
> @vsgoulart can I ask why Jan 4? We'll have the 8.4.0 release on Jan 9th. Does this need to go out Jan 4 exactly or should it go with the minor?

@akeller it can go with the minor batch, I just put of when the the releases will be done on the HTO team side

**Review by Skaiir — COMMENTED** [review]
Some extra documentation on the data structure / configuration would be nice here, as going by just the input window alone can be a bit esoteric.

**Comment by christinaausley** [comment]
@vsgoulart are you planning to have this ready for release next week? Let me know if you need additional review 👍

**Comment by vsgoulart** [comment]
> @vsgoulart are you planning to have this ready for release next week? Let me know if you need additional review 👍

@christinaausley yes, I plain o taking of this tomorrow. I was on FTO and this was sort of abandoned for a while, sorry for the delay

**Comment by akeller** [comment]
> 👋 🤖 🤔 Hello! Did you make your changes in all the right places?
> 
> These files were changed only in _docs/_. You might want to duplicate these changes in _versioned_docs/version-8.3/_.
> 
> * docs/components/modeler/forms/form-element-library/forms-element-library-table.md
> * docs/components/modeler/forms/form-element-library/forms-element-library.md
> * docs/components/modeler/forms/sidebar-schema.js
> 
> You may have done this intentionally, but we wanted to point it out in case you didn't. You can read more about the versioning within our docs in our [documentation guidelines](https://github.com/camunda/camunda-docs/blob/c666b7e5e35bfe31468ce4ac679ea7b62ab86d73/howtos/documentation-guidelines.md#versions).

No backport required; this is only available in 8.4 per the PR description/scope.

**Review by christinaausley — APPROVED** [review]

**Comment by vsgoulart** [comment]
@christinaausley I added an extra page as requested by @Skaiir , you can check the last commit to see the changes

I'll ask @Skaiir to prioritize this review tomorrow morning

**Review by Skaiir — APPROVED** [review]
Thanks for the extra context, will definitely help some folks out I believe 😃

**Pull request merged**
