### PR TITLE
docs(identity): note the intention of the Identity UI in 8.4

### PR DESCRIPTION
**Pull request by Ben-Sheppard**
## Description

There has been some confusion about the status of the Identity UI in the current 8.4 release when configuring an OIDC provider. I have added in a visible admonition to try to clear up the current status.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [x] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — COMMENTED** [review]
Should this be noted elsewhere in the docs? Update guides and/or announcements in relevant documentation?

**Comment by Ben-Sheppard** [comment]
@christinaausley I don't believe so - if you were running 8.3 with Keycloak and then use 8.4 with Keycloak then everythign remains the same. This limitation is only (currently) with the 8.4 version when you intentionally configure the OIDC connection, and the OIDC feature is first found in 8.4.

**Review by christinaausley — APPROVED** [review]

**Review by akeller — CHANGES_REQUESTED** [review]
Please remove package-lock.json from this PR.

**Review by akeller — APPROVED** [review]
Thank you 🧡

**Pull request merged**
