### PR TITLE
doc(marketplace): Rename mentions of "process blueprints" to "blueprints"

### LINKED ISSUE #3906: Reflect "Browse blueprints" modal UI changes in Web Modeler > Camunda Marketplace page
Reflect changes made as part of [this Product Hub epic](https://github.com/camunda/product-hub/issues/2333) (Public Marketplace Blueprint Support for HTO & DMN).

This ticket should not be started until the changes for [the epic](https://github.com/camunda/product-hub/issues/2333) have been implemented (or are close to being merged).

### PR DESCRIPTION
**Pull request by ev-codes**
Closes #3906 

## Description

Update text and screenshots to "blueprints" name change coming in 8.6.0-alpha4

https://github.com/camunda/product-hub/issues/2333

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [x] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by ev-codes** [comment]
Note to reviewers - I'm creating this PR so my changes can be tested by a QA engineer.

I'll request review in late July/early August, closer to the 8.6-alpha4 release

**Comment by christinaausley** [comment]
@ev-codes Thank you for adding all of the details and proper labels!

**Comment by ev-codes** [comment]
@camunda/tech-writers this PR is now ready for review, then merge and release!

The Web Modeler changes reflected in this PR will be released as part of SaaS Web Modeler within the next few business days.

**Review by christinaausley — APPROVED** [review]

**Comment by christinaausley** [comment]
@ev-codes Just flag me when this is ready for release 👍

**Comment by ev-codes** [comment]
@christinaausley this is ready for release! Thanks 😄

**Comment by akeller** [comment]
I'll get a release out for you today @ev-codes 😄

**Pull request merged**
