### PR TITLE
Update supported-environments.md

### PR DESCRIPTION
**Pull request by toco-cam**
## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [x] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by MaxTru** [comment]
Hi @igpetrov,

see request from Tobias to update the docs. Are we already confident with that OS bump?

**Comment by igpetrov** [comment]
Hi @MaxTru 
I saw the request. We are not confident yet with all versions provided. For now, minimal version I checked was 2.9, I didn't cover 2.11 and 2.13. Let me prioritize this task and I can report next week on it. Would that work?

**Review by igpetrov — DISMISSED** [review]
@toco-cam 

LGTM. I am thinking whether it makes sense to call out `2.9.x+` instead of `2.9; 2.11; 2.13+` which sounds the same to me? Also, was there any agreement that we start from 2.9?

**Comment by toco-cam** [comment]
Hello @igpetrov,
> Also, was there any agreement that we start from 2.9?
We do not have good customer feedback on how long we should support an environment. The fact that AWS is not retiring environments does not make it easier. 

As the minor versions are upward compatible, "x.+," it is better for customers to support older versions as they are not forced to upgrade. Engineering requested changing to 2.9+ to use new features and reduce test efforts.

Regards Tobias

**Comment by igpetrov** [comment]
Hi @christinaausley @toco-cam,

Can we merge this one? Let's give the Customers as much time as we can to discover this. Thank you!

**Comment by akeller** [comment]
@igpetrov, I added @camunda/tech-writers as reviewers so we can merge this. I also updated the PR description based on what I see changed in the PR - no backporting required as this change is just for `/next/` or the preview for 8.6. If that's incorrect, please speak up!

**Review by christinaausley — APPROVED** [review]

**Review by christinaausley — DISMISSED** [review]

**Comment by igpetrov** [comment]
@akeller

> no backporting required as this change is just for `/next/` or the preview for 8.6. If that's incorrect, please speak up!

That's correct, it's for `/next` to let the Customers get familiar with the change. The  actual change will happen in 8.6.

**Review by igpetrov — APPROVED** [review]

**Comment by toco-cam** [comment]
@MaxTru 

Igor suggested:
> I am thinking whether it makes sense to call out 2.9.x+ instead of 2.9; 2.11; 2.13+

We had a brief call, and as we do not have dedicated test coverage for the different versions 2.9, 2.11, and 2.13, there is, IMO no value in calling them out specifically. WDYT?

**Comment by MaxTru** [comment]
> @MaxTru
> 
> Igor suggested:
> 
> > I am thinking whether it makes sense to call out 2.9.x+ instead of 2.9; 2.11; 2.13+
> 
> We had a brief call, and as we do not have dedicated test coverage for the different versions 2.9, 2.11, and 2.13, there is, IMO no value in calling them out specifically. WDYT?

I agree. Let's go for `2.9.x+`.

**Comment by akeller** [comment]
> > @MaxTru
> > Igor suggested:
> > > I am thinking whether it makes sense to call out 2.9.x+ instead of 2.9; 2.11; 2.13+
> > 
> > 
> > We had a brief call, and as we do not have dedicated test coverage for the different versions 2.9, 2.11, and 2.13, there is, IMO no value in calling them out specifically. WDYT?
> 
> I agree. Let's go for `2.9.x+`.

@christinaausley based on this comment, can you adjust this PR for @toco-cam so we can get it merged?

**Review by christinaausley — APPROVED** [review]
Done @akeller 👍

**Review by akeller — APPROVED** [review]
Based on the convo in this PR, I believe this reflects the intended change - approving.

**Pull request merged**
