### PR TITLE
fix(helm): added proxy-buffer-size in attempt to guide users to confi…

### PR DESCRIPTION
**Pull request by jessesimpson36**
…gure this parameter

## Description

This change will add a default proxy-buffer-size as an attempt to guide users to configure this parameter for their specific ingresses.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by jessesimpson36** [comment]
@jonathanlukas @Ben-Sheppard @plungu , this change will add the ingress proxy-buffer-size to the docs.  Let me know if this change is beneficial / consistent with what you've experienced when interacting with this header.

**Comment by christinaausley** [comment]
@jessesimpson36 please sign the CLA and add any necessary reviewers. Let me know when you are ready for final review and we can get this merged 👍

**Comment by christinaausley** [comment]
@jessesimpson36 Are you needing this merged in before release tomorrow?

**Comment by jessesimpson36** [comment]
Hey @christinaausley , there is no urgency to this PR.  In fact, I'm not entirely sure we need it.  I'm sorry I forgot about it and left it dangling here.

I'll ask for some recommendations, and get back to you.

**Comment by jessesimpson36** [comment]
I'm going to close this PR.  I don't have the time to deal with right now.

**Comment by christinaausley** [comment]
@jessesimpson36 Thanks for checking up on this regardless 👍 Let me know if I can assist in the future.

**Pull request closed without merging**
