### PR TITLE
adjust custom css for beta label

### PR DESCRIPTION
**Pull request by christinaausley**
## Description

Related to Slack discussion https://camunda.slack.com/archives/C026U8GBNSW/p1708422521980589. "Beta" CSS label should be "alpha".

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [x] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by akeller — CHANGES_REQUESTED** [review]
Unfortunately we'll still have the mismatch here with the Web Modeler API - it was released with `/beta/`.

I would not backport this change, but instead add a second badge for the alpha features and then remove "beta" in 8.5 when we drop support for the beta Web Modeler API. Please confirm with @christian-konrad that we can remove the beta Web Modeler API from all supported version docs.

**Comment by akeller** [comment]
> Unfortunately we'll still have the mismatch here with the Web Modeler API - it was released with `/beta/`.
> 
> I would not backport this change, but instead add a second badge for the alpha features and then remove "beta" in 8.5 when we drop support for the beta Web Modeler API. Please confirm with @christian-konrad that we can remove the beta Web Modeler API from all supported version docs.

Whoops, please confirm with @HanselIdes as the Web Modeler PM.

**Comment by HanselIdes** [comment]
@akeller I think that's the right approach to have separate tags for alpha and beta since the web modeler beta API is being removed with 8.5
I responded as well in [Slack](https://camunda.slack.com/archives/C026U8GBNSW/p1708552222828679?thread_ts=1708422521.980589&cid=C026U8GBNSW)

**Comment by christinaausley** [comment]
@akeller I've added a label for alpha moving forward and reverted the alpha changes in `8.1` back to "beta". Let me know if I'm missing anything else 👍

**Review by akeller — APPROVED** [review]
👍 I'm good with the scope of this PR - add alpha badge CSS.

**Pull request merged**
