### PR TITLE
docs(optimize): Add documentation maxNumDataSourcesForReport

### PR DESCRIPTION
**Pull request by matthewBearCamunda**
## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
@matthewBearCamunda is this part of today's alpha release?

**Comment by matthewBearCamunda** [comment]
@akeller - No, the change for Optimize has not been finished just yet

**Comment by matthewBearCamunda** [comment]
The change for optimize (https://github.com/camunda/camunda-optimize/pull/12018) has been merged and this PR is ready for review

**Comment by matthewBearCamunda** [comment]
@christinaausley - That'd be great. I added you as a reviewer

**Comment by christinaausley** [comment]
@matthewBearCamunda this is only for the `next` version of docs, yes? If you're ready to merge, feel free.

**Review by christinaausley — APPROVED** [review]

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
