### PR TITLE
docs(self-managed): console byo oidc

### PR DESCRIPTION
**Pull request by urbanisierung**
## Description

- Relates https://github.com/camunda-cloud/camunda-cloud-management-apps/issues/2752 https://github.com/camunda/product-hub/issues/2092
- Describes instructions how to use a different OIDC Provider for Console.
- Extends given structure in `Guides` for Console.
- Adds a reference to the guide in Console Config sections.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer.

### CODE REVIEW

**Comment by urbanisierung** [comment]
@ultraschuppi @theburi Please have a look into the docs for BYO OIDC. From my point of view we don't need that much additional docs. There is already a guide about a different OIDC provider.

The console sm implementation aligns with the global values described in the guide.

**Comment by ultraschuppi** [comment]
> @ultraschuppi @theburi Please have a look into the docs for BYO OIDC. From my point of view we don't need that much additional docs. There is already a guide about a different OIDC provider.
> 
> The console sm implementation aligns with the global values described in the guide.

I, for one, endorse piggybacking on existing docs instead of reinventing the wheel.

**Review by theburi — APPROVED** [review]

**Comment by urbanisierung** [comment]
@christinaausley Can you please have a final review on this PR? It's part of `next` and will be officially released with 8.6. Thanks!

**Review by christinaausley — APPROVED** [review]

**Comment by christinaausley** [comment]
Should this be merged in for alpha-3 tomorrow?

**Comment by urbanisierung** [comment]
> Should this be merged in for alpha-3 tomorrow?

@christinaausley waiting for green lights from QA :)

**Comment by urbanisierung** [comment]
@christinaausley We finally got green lights from QA. The changes will be part of 8.6 alpha4 - can I just merge this one?

**Pull request merged**
