### PR TITLE
docs(sm) - update secrets extraction for version 8.5

### PR DESCRIPTION
**Pull request by upgradingdave**
## Description

There is no longer a `camunda-postgresql` secret as of 8.5. Here's a suggestion to improve this page: 

https://docs.camunda.io/docs/self-managed/setup/upgrade/#secrets-extraction

I also updated the `Note`. Many of the components are customizable, and so this secrets extraction script will be different for each environment. So, rather than adding comments such as ("uncomment if using console"), I suggest we give a script including everything with a Note to remind folks to customize it as needed. 

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by aabouzaid** [comment]
I assign this to @jessesimpson36 as Jesse is working on the upgrade topic.

**Comment by christinaausley** [comment]
@jessesimpson36 I'll give this a final approval following your review 👍

**Comment by jessesimpson36** [comment]
I think this is a bit more nuanced. There is a secret named `camunda-postgresql` and a secret named `camunda-identity-postgresql`.  As dave pointed out, these two secrets are used for the same purpose; i.e. to provide credentials for postgresql. However, depending on your kind of installation, you might have one secret or the other. 

The reason for there being two secrets for the same purpose is that one is provided by the bitnami postgresql subchart. However, we also want customers to be able to access an external database (a postgresql server that exists outside of the cluster). For those situations, the subchart is disabled, but we still need a secret to provide credentials to the third party postgresql server. and that secret exists in the camunda chart  and  we disable it whenever the postgresql subchart is enabled.

Perfect world scenario is that these two secrets would be named the same thing and nobody would know the difference, however, I don't think it can be changed now, because if we changed the secret names it'd affect existing users installs.

For 8.7 and newer, we will be mandating that existingSecrets be created and managed outside the helm chart to remove this confusion, and also remove the secrets extraction from the upgrade process.  For 8.6, we will display a warning encouraging users to use existingSecrets.  

We  could favor  whichever secret name is provided for non-external postgresql instances for the time being, which should be `camunda-postgresql`.  

do you want to get on a call with me to discuss/confirm @upgradingdave ?

**Comment by upgradingdave** [comment]
Thanks for the explanation @jessesimpson36. Yeah, maybe we could jump on a quick call and I can update this PR to explain this more clearly. I'll catch up with you on slack, thanks!

**Comment by christinaausley** [comment]
@upgradingdave Also happy to hop on a call and help with any docs changes, just let me know 😄

**Comment by akeller** [comment]
Checking in on open PRs - we'll want to merge this well before our minor release. @upgradingdave what's the status? How can we get this over the finish line 🏁

**Comment by upgradingdave** [comment]
Hi @akeller - I simplified this down to just a small note reminding folks that the secrets extraction script is meant as a sample and will likely need to be customized for each environment. I think it should be good to go now.

**Review by jessesimpson36 — APPROVED** [review]

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
