### PR TITLE
Update screenshot of Play to contain the restart process button and improve instruction

### PR DESCRIPTION
**Pull request by huygur**
## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by huygur** [comment]
@HanselIdes @christinaausley 
I wasn't sure which checkbox to check in the issue description, but this doc is related to this feature being shipped: https://github.com/camunda/web-modeler/pull/7230

**Review by christinaausley — APPROVED** [review]

**Comment by christinaausley** [comment]
@huygur I see this is on `hold` -- can you provide additional details?

**Review by HanselIdes — APPROVED** [review]
LGTM. 
I initially thought about removing the part about returning to the definition view, but it's not intuitive enough to remove it from docs

**Comment by akeller** [comment]
@huygur @HanselIdes were you expecting these docs to be merged and released today with the alpha?

**Comment by huygur** [comment]
> @huygur @HanselIdes were you expecting these docs to be merged and released today with the alpha?

@akeller changes are not live yet, but they will be tomorrow morning: https://camunda.slack.com/archives/C0693F1NFK5/p1702397075049139

**Comment by huygur** [comment]
@christinaausley @akeller the changes are live now, we can merge this PR 🎉

**Pull request merged**
