### PR TITLE
8.7.0-alpha1 release notes

### PR DESCRIPTION
**Pull request by akeller**
## Description

https://github.com/orgs/camunda/projects/9/views/31

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by mesellings** [comment]
@akeller I've been through the release notes and made changes as follows:

- Checked those epics and all looks good, all the ones are there that should be
- Reworded all items for conciseness, technical, casing, readability etc
- Ordered items alphabetically and front-loaded titles
- Added badges and links to docs
- Added the alpha 1 table with date etc, I've guessed at the release blog URL for now
- Hidden the 7.0 table/heading - wasn't sure if we should display this as it will always be empty for the alphas and looks unfinished? I've just commented it out for now as I wasn't sure what you normally do with it.

**Comment by mesellings** [comment]
@akeller Just made a few grammar edits on the main release notes page as well, and added hyphens into the blank table cells for 8.7 on this page so it doesn't look incomplete/unfinished 👍

**Comment by MaxTru** [comment]
@mesellings @akeller can we please have this merged and deployed latest 4pm CET today? If not possible, please send me a note so that I can send an update to Support asking them to wait with release notification mail.

**Review by mesellings — DISMISSED** [review]
LGTM - approved 👍

**Comment by mesellings** [comment]
> @mesellings @akeller can we please have this merged and deployed latest 4pm CET today? If not possible, please send me a note so that I can send an update to Support asking them to wait with release notification mail.

@MaxTru I've taken it out of draft and approved so we can push quickly when we need to, but I don't want to merge it until @akeller is back online and is happy for it to go live (although there shouldn't be any issues that I can see).

**Review by mesellings — APPROVED** [review]
Approved

**Comment by mesellings** [comment]
@MaxTru @akeller Looking at the time differences between US <> CET, we don't have much room, so I'm going to publish the release notes, and then we can follow up with any amendments in quick PRs if required.

@MaxTru I'll update in Slack once the release notes are live 👍

**Comment by akeller** [comment]
Thank you @mesellings for getting this over the finish line.

> Hidden the 7.0 table/heading - wasn't sure if we should display this as it will always be empty for the alphas and looks unfinished? I've just commented it out for now as I wasn't sure what you normally do with it.

Let's sync on this in our 1:1, I'm not sure what you mean.

**Pull request merged**
