### PR TITLE
chore: update Desktop Modeler screenshots to v5.16.0

### PR DESCRIPTION
**Pull request by nikku**
## Description

This updates the modeler screenshots to v5.16.0.

## When should this change go live?

As soon as possible.

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
@nikku some of the screenshots have 8.0 and 8.1 in the footer. Some also have Zeebe 1.3, which is technically already unsupported.

Is this something that can be updated so all screenshots reference supported versions? Ideally, this is consistent, and they all show the latest version in the latest version of the docs.

**Comment by nikku** [comment]
@akeller We want to update the screenshots automation, [I created an issue](https://github.com/camunda/camunda-docs-modeler-screenshots/issues/66).

**Review by christinaausley — APPROVED** [review]

**Comment by christinaausley** [comment]
Feel free to merge when ready 👍

**Comment by nikku** [comment]
Follow up for outdated screenshots: https://github.com/camunda/camunda-docs/pull/2723.

**Pull request merged**
