### PR TITLE
docs(MT:tasklist): document MT-related changes for Tasklist

### PR DESCRIPTION
**Pull request by ce-dmelnych**
## Description
Closes: https://github.com/camunda/tasklist/issues/3431
In this PR we are documenting changes done during implementing multi-tenancy for Tasklist application.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by koevskinikola — CHANGES_REQUESTED** [review]
LGTM @ce-dmelnych :100: 

It would be good if you also copy over these changes to the `versioned_docs/version-8.3` since it was already released.

**Comment by ce-dmelnych** [comment]
> LGTM @ce-dmelnych 💯
> 
> It would be good if you also copy over these changes to the `versioned_docs/version-8.3` since it was already released.

Oh, thanks for highlighting this!
porting it for v`8.3` also.

**Comment by ce-dmelnych** [comment]
@ koevskinikola
I copied changes to v`8.3` also.

**Review by koevskinikola — APPROVED** [review]
LGTM :+1:

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
