### PR TITLE
feat(connectors,sagemaker): introduce AWS SageMaker connector

### PR DESCRIPTION
**Pull request by igpetrov**
## Description

This PR introduces documentation to the AWS SageMaker Connector.

## When should this change go live?

This connector will be 'released' in `8.6` however, users would still be able to download it from the Connectors marketplace or repository. This means, that we have to keep it in `/next/` until `8.6` stable release.

Otherwise, it is ready to be reviewed any time and merged just after @slolatte gives a sign-off as QA. Once sign-off is given, I will remove `hold` label and notify separately.

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineerring DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer.

### CODE REVIEW

**Comment by igpetrov** [comment]
> 👋 🤖 🤔 Hello! Did you make your changes in all the right places?
> These files were changed only in docs/. You might want to duplicate these changes in versioned_docs/version-8.5/.

---

Thank you, robot 🤖 . I need my changes only in `/next/` until `8.6` stable release.

**Comment by igpetrov** [comment]
The connector passed QA successfully. The element template was submitted to Connectors Marketplace.

@crobbins215 - please give guidance whether we should merge this documentation. Please note, that the connector will be available officially with 8.6 but with the upcoming 8.6-alpha, customers can use it too.

**Comment by crobbins215** [comment]
If its on the marketplace, which is should be soon, just reviewing, we should include it in the next docs

**Review by christinaausley — APPROVED** [review]
This is really clean! Nice work.

**Pull request merged**
