### PR TITLE
docs: changing ES supported versions

### PR DESCRIPTION
**Pull request by marcosgvieira**
## Description

This PR is updating supported versions of ElasticSearch as we found a bug in ElasticSearch that may impact importers on version 8.7.1. For this reason changing from version 8.7 to 8.8. 

**References:**
https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-8.7.1.html
https://github.com/elastic/elasticsearch/issues/96078

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by marcosgvieira** [comment]
@RomanJRW @johanwelgemoed @megglos I'm updating from version 8.7 to 8.8, can you please check if I missed any page?

**Comment by megglos** [comment]
@marcosgvieira you also need to add these changes to the versioned docs https://github.com/camunda/camunda-docs/tree/main/versioned_docs/version-8.3 to make them available if someone selects `8.3` explicitly in the docs.

**Review by megglos — DISMISSED** [review]
LGTM! Pre-approving but we need to add the change to the versioned docs too.

**Review by christinaausley — APPROVED** [review]
Added to versioned docs and merging 👍

**Review by christinaausley — APPROVED** [review]

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
