### PR TITLE
add spring support policy

### PR DESCRIPTION
**Pull request by christinaausley**
## Description

Related to https://github.com/camunda/camunda-docs/issues/4036.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [x] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by christinaausley** [comment]
@felix-mueller @megglos I assume this should also be backported to `8.5`? Ideally I'd like a statement/example that we don't need to change for every version of the docs. Would it be sufficient to just say "For new minor releases, Camunda typically automatically updates to new minor releases of our dependencies when they are released. This general rule also applies to Spring."?

If not, I may revisit some of the phrasing here, unless we want to default to a specific version comparison with `8.5`, for example.

**Review by akeller — COMMENTED** [review]
We reference [clients](https://docs.camunda.io/docs/next/reference/supported-environments/#clients) on the supported environment page, but don't include the Spring SDK. 

I don't love the phrasing here and have concerns similar to @christinaausley's comment about changing this for every new version. We can be more definitive here and update the table per minor version but also consider moving this content to the supported environment page, a page we already know changes for each minor.

**Comment by felix-mueller** [comment]
@akeller @christinaausley - from my perspective we can be more generic, my message was just an example for 8.6.
we can also add spring sdk to supported environments and link back to the version matrix (similar to helm cli). 
let's keep the statement itself spring specific for now since it might have more implications and i dont see the need to go through it right now.

**Comment by christinaausley** [comment]
@felix-mueller I think I'm following correctly here -- let me know based on my latest changes.

**Comment by felix-mueller** [comment]
@christinaausley lgtm

**Review by felix-mueller — APPROVED** [review]

**Comment by christinaausley** [comment]
@akeller Can I get one final review from you here? 😄

**Review by akeller — APPROVED** [review]

**Pull request merged**
