### PR TITLE
chore(element-templates): add new group options

### PR DESCRIPTION
**Pull request by marstamm**
## Description
This PR adds documentation for new Element template options.

related to https://github.com/camunda/camunda-modeler/issues/3807

## When should this change go live?

This should not be merged before the funcitonality is integrated into the modeler, cf. https://github.com/camunda/camunda-modeler/issues/3807

- [x] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] ~~I have added changes to the relevant `/versioned_docs` directory, or~~ they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`)~~, or they are not for **future versions**.~~
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by christinaausley** [comment]
Added a `hold` label until this can go live, but let me know when you are ready for review 👍

**Comment by marstamm** [comment]
This is getting integrated with https://github.com/camunda/camunda-modeler/pull/3939 and is ready for review now

**Review by barmac — APPROVED** [review]
Looks good to me.

**Review by christinaausley — APPROVED** [review]
No changes on this one 👍

**Pull request merged**
