### PR TITLE
refactor: migrate Tasklist API Explorer into versioned docs

### PR DESCRIPTION
**Pull request by pepopowitz**
~Blocked by #3566, which includes some refactoring of the generation process that this PR depends on. (I might be able to re-organize this PR so that it doesn't have that dependency...but I don't feel it's worth it.)~

## Description

This PR migrates the Tasklist REST API Explorer into the main docs, so that they can be versioned. This is a better reflection of how the API evolves over time, even though it maintains the moniker `v1` as it evolves. It also eliminates a confusing navigation situation, where we had users "bouncing out" of the main docs to explore the API, and then "bouncing back in". 

The moved docs live under a folder named `Specifications`, within the APIs-Tools/Tasklist REST API sections of the 8.4 and vNext docs.

## Included

1. The "v1" standalone Tasklist REST API Explorer is removed entirely.
2. The contents of the current Tasklist REST API Explorer are moved into the _current_ version of the docs (8.4). The OpenAPI spec that I originally used to generate these docs was based on an 8.4 cluster, so this is the appropriate version for them. 
   Screenshot:
   
   image

3. The Tasklist REST API Explorer is re-generated into the _next_ version of the docs (what will become 8.5). These docs are based on a spec that I captured from an 8.5.0.rc2 cluster running on https://console.cloud.ultrawombat.com/.
   Screenshot (notice the difference in possible values of the `state` property, which is one of the differences in the two versions' OpenAPI specs):
   
   image

4. Refactoring of the doc generation process for the Tasklist REST API, so that it can be fully automated.
5. Customizable server URLs in the Tasklist REST API Explorers. Previously I'd had these URLs hardcoded to a string that meant nothing, but was obviously not the server URL I grabbed the spec from. Now, the server URL is made dynamic before generation of the docs. This enables users to customize the URL in the request builder, so that they can copy more realistic code samples.
6. Redirects to account for the explorer URLs changing.

## Why do this now instead of waiting until after the release?

1. Tackling this now will save me from generating an additional version after the release (the 8.5 version).
2. It also assures us of having up-to-date 8.5 docs as soon as that version of the docs is shipped. Otherwise there'd likely be a gap between cutting the 8.5 docs and me getting a chance to re-generate the API Explorer.

Having said that, this is late in the release cycle for a substantial change like this, so if people are uncomfortable from a risk perspective I will wait until after the upcoming release.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [x] This change or page is part of a marketing blog, conference talk, or something else on a schedule. I'd like this merged before I cut the 8.5 docs next week.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — COMMENTED** [review]
Looks like there are just a few lingering sitemap links, but let me know when you're ready for final review 👍

**Comment by christian-konrad** [comment]
@pepopowitz 

2 small things (non-blocking):

1. There are now 2 introductions to the API:

Bildschirmfoto 2024-04-04 um 08 52 39

Bildschirmfoto 2024-04-04 um 08 51 24

I propose a follow-up issue to merge them. Same for Operate and Zeebe.

2. Imo, the specs should come before the migration page, as (especially new) readers should read the API docs first before the migration doc.

Bildschirmfoto 2024-04-04 um 08 54 30

**Review by christian-konrad — APPROVED** [review]
Asked for 2 changes in a prior comment that can be done in follow-ups

Awesome work!

**Comment by pepopowitz** [comment]
@christian-konrad 

> 1. There are now 2 introductions to the API:

Yes, this bothers me also. I assigned the follow-up issue to myself.

> 2. Imo, the specs should come before the migration page

I went back and forth on this order! Given your encouragement I will swap the order, in this PR, before merging. I'll push up a commit soon!

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
