### PR TITLE
move general availability section

### PR DESCRIPTION
**Pull request by christinaausley**
## Description

Closes https://github.com/camunda/developer-experience/issues/418 and moves GA from alpha features to release policy.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Review by conceptualshark — APPROVED** [review]
👍 I like this positioning, but I know it was my suggestion so I'm not sure if you'd like additional feedback - everything looks good to me though!

**Comment by akeller** [comment]
I don't know if we need other stakeholder input on this topic, or if it's linked in the product. Do you know? Did this come up organically within DevEx?

**Comment by christinaausley** [comment]
@akeller Yes, only discussed [here](https://github.com/camunda/camunda-docs/pull/4465#pullrequestreview-2375372997) within DevEx.

**Comment by christinaausley** [comment]
Sorry @camunda/tech-writers -- resolved some merge conflicts and need one more approval 👍

**Review by conceptualshark — APPROVED** [review]
🙌

**Pull request merged**
