### PR TITLE
Link table data binding to data source

### PR DESCRIPTION
**Pull request by falko**
## Description

Link to the table data binding where it is most needed. It took me a second careful read through the entire page to find the most important information on how to use the Table component.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by akeller** [comment]
@camunda/tech-writers please review this change and backport it as appropriate

**Comment by mesellings** [comment]
@falko I will review this for you 👍

**Review by mesellings — APPROVED** [review]
Hi @falko, I have reviewed and made a small grammatical change, as well as porting the changes for the Next and 8.4 doc versions as well. Happy to approve 👍

**Comment by mesellings** [comment]
@falko will you merge this into the docs? We have a release going out Tuesday so it could go out then?

**Pull request merged**
