### PR TITLE
update misleading docs

### PR DESCRIPTION
**Pull request by Laksh47**
## Description
- Fix misleading docs, Zeebe API (REST) seems to be accidentally placed under the "Deprecated" section when there's a contradicting doc encouraging to use the rest API: https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/migrate-to-zeebe-user-tasks/#use-the-new-zeebe-task-api
- Fix is to move it out of the "Deprecated" sidebar

Screenshot 2024-10-17 at 11 23 03 AM

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [x] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

### CODE REVIEW

**Comment by akeller** [comment]
Hi @Laksh47, it looks like we need to make some updates to the [Migrate to Zeebe user tasks page](https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/migrate-to-zeebe-user-tasks/).

The [Camunda 8 REST API](https://docs.camunda.io/docs/apis-tools/camunda-api-rest/camunda-api-rest-overview/) replaces the Zeebe REST API, so the structure in the docs is correct. 

FYI @aleksander-dytko

**Comment by Laksh47** [comment]
@akeller Thanks a lot for the clarification, does this mean in 8.6, we'll be able to use the Tasklist API to assign/complete/unassign tasks? (and no need for the Zeebe Task API?)

Screenshot 2024-10-17 at 12 31 16 PM

**Comment by aleksander-dytko** [comment]
> does this mean in 8.6, we'll be able to use the Tasklist API to assign/complete/unassign tasks? (and no need for the Zeebe Task API?)

@Laksh47 I understand this is confusing so let me summarize the changes and plan forward:
* with 8.5 we have introduced a new User Task type - `Zeebe User Task` to enable us architecturally to build more advanced functionalities like User Task Listeners (react on task state changes)
  * To manage `Zeebe User Tasks` we have introduced Zeebe REST API
  * You can still query `Zeebe User Tasks` with Tasklist Query API
* with 8.6 we have introduced `Camunda 8 REST API` to manage and query process entities (processes, decisions, forms, user tasks)
  * you can use [Camunda 8 REST API](https://docs.camunda.io/docs/apis-tools/camunda-api-rest/specifications/complete-user-task/) to manage your user tasks 
  * in 8.6 you can still use Tasklist Query API to query for user tasks 
* with 8.7, we will replace Tasklist Query API with Camunda 8 REST API to query for User Tasks (`Zeebe User Tasks`)
  * You can manage and query User Tasks via a single REST API

In 8.5 or 8.6 if you use `Zeebe User Tasks`, Task Management endpoints in Tasklist API **won't work** 

Please let us know if you have other questions ;)

**Comment by aleksander-dytko** [comment]
> Hi @Laksh47, it looks like we need to make some updates to the [Migrate to Zeebe user tasks page](https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/migrate-to-zeebe-user-tasks/).
The [Camunda 8 REST API](https://docs.camunda.io/docs/apis-tools/camunda-api-rest/camunda-api-rest-overview/) replaces the Zeebe REST API, so the structure in the docs is correct.

@akeller fully agreed - we should rather update the migration guide to use C8API instead of Zeebe REST API

**Comment by akeller** [comment]
@Laksh47, I will close out this PR, because as discussed, the docs structure is correct. There are follow-ups here, so I will link to existing or new issues.

**Pull request closed without merging**
