### PR TITLE
elasticsearch-exporter: Add link to index templates

### PR DESCRIPTION
**Pull request by falko**
It took me quite a while to dig the index templates out of the source based on the given hint. So, let's add the actual link and also point out that "this module" actually means the exporter source code: https://github.com/camunda/zeebe/tree/main/zeebe/exporters/elasticsearch-exporter/src/main/resources

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [x] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineerring DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer.

### CODE REVIEW

**Comment by falko** [comment]
@christinaausley I don't have more time to work on this. Primarily, I wanted to report the documentation issue. Could your team please finish the versioned docs? This may also need special attention, when new releases come out.

**Review by akeller — CHANGES_REQUESTED** [review]
This is one of those cases where we need to link to the version-specific URL. @npepinpe do you have any recommendations? I was having trouble finding a stable branch for 8.4 or the right tagged version. 

Similar to my conversation on another PR - https://github.com/camunda/camunda-docs/pull/3795#discussion_r1598660096

**Comment by falko** [comment]
@npepinpe  The stable branches should work, right?
https://github.com/camunda/zeebe/tree/stable/8.5/zeebe/exporters/elasticsearch-exporter/src/main/resources

**Comment by npepinpe** [comment]
Yes, every supported version has a stable branch (e.g. `stable/8.4`, `stable/8.5`). However, once the version is not supported anymore, we remove this. For the docs, we seem to keep a copy of the unsupported versions, so the links would become broken eventually. As an alternative, using the tag would work better, e.g.

- 8.5.0: https://github.com/camunda/zeebe/blob/8.5.0/zeebe/exporters/opensearch-exporter/src/main/resources/zeebe-record-job-template.json
- 8.4.0: https://github.com/camunda/zeebe/blob/8.4.0/exporters/opensearch-exporter/src/main/resources/zeebe-record-job-template.json
- 8.3.0: https://github.com/camunda/zeebe/blob/8.3.0/exporters/opensearch-exporter/src/main/resources/zeebe-record-job-template.json

And so on.

The downside here is:

1. `main` always points to latest, so on every release we need to update those links to point to the new tag.
2. The tags point to specific patch versions. Though, I don't expect us to change these things much between patches, it's not impossible if we introduced something incorrect.

**Comment by falko** [comment]
Then a combination of linking to stable branches for maintained versions and to the last release tag for older unmaintained versions would work.

**Comment by christinaausley** [comment]
> #3795 (comment)

@akeller Unless you have immediate thoughts, let's discuss this (as in both PRs) and the solution in our 1:1 this week? Would be worth a style guide addition.

**Comment by christinaausley** [comment]
I'll make a note to myself to adjust the latest link per each release 👍

**Review by akeller — APPROVED** [review]

**Pull request merged**
